### ISSUE TITLE
core hangs when there is missing roms

### ISSUE THREAD

**Issue by ghost** [libretro/mame#100]
If you load a zip and it has missing roms the core hangs to reproduce copy a rom somewhere delete a file and try start the game

**Comment by c0d3h4x0r** [comment]
I can confirm that I've repro'd this as well.

**Comment by MarcoBorrini99** [comment]
Issue still exists with current 0.220 version.

**Comment by breisig** [comment]
This issue still exists with todays latest git version.

**Comment by tcamargo** [comment]
See https://github.com/libretro/mame/issues/158.
