### ISSUE TITLE
Vii, and jak_wall crash on libretro MAME, but not the standalone version

### ISSUE THREAD

**Issue by Sterophonick** [libretro/mame#102]
When booting the JungleTac Vii (vii) or JAKK's Pacific Wall-E (jak_wall), retroarch hangs and throws this error:

File: ../../../../../src/devices/cpu/drccache.cpp, Line 218

Expression: m_top - m_codegen < CODEGEN_MAX_BYTES

This does not happen on the standalone version of MAME.

**Comment by tcamargo** [comment]
Could you try again with a recent version of mame core? I guess #125 fixed it.
