### ISSUE TITLE
MAME core giving 0 refresh rate at 384 resolution using CRT Switchres

### ISSUE THREAD

**Issue by atylmo** [libretro/mame#105]
From https://github.com/libretro/RetroArch/issues/8753:

## Description
When you run a MAME game that's not 240p (say, Virtua Racing at 496x384), the refresh rate reported by `xrandr` is 0. Because of that, it fails to switch to the right resolution and reports `Configure crtc 0 failed`. It happens on LCDs as well as CRTs.

### Expected behavior

The resolution and refresh rate should switch.

### Actual behavior

It tries to switch refresh rates, and the notification pop-up says it did, but it's actually showing (what I believe to be) the last resolution used, which for me is usually 240p.

### Steps to reproduce the bug

1. Load the MAME core.
2. Turn on CRT Switchres and set it to Native (although I think other settings produce the same result).
3. Load a game that's a higher resolution than 240p, like Virtua Racing or Daytona USA.
4. When it loads, tab out of it, open a terminal and type `xrandr`. You should see that one of the resolutions added by Switchres is listed, but with a 0 refresh rate.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.7 / 1a3f16ded1

### Environment information

- OS: Ubuntu 19.04
- Compiler: GCC 8.3.0

Here's an example of `xrandr --verbose` showing the non-working modeline:
```
CRT2_496x384_115.05 (0x236)  0.000MHz -HSync -VSync Interlace
        h: width   496 start  523 end  557 total  656 skew    0 clock   0.00KHz
        v: height  384 start  176 end  182 total    0           clock   0.00Hz

```

This seems to be specific to only 384 horizontal/vertical resolution. Higher and lower are fine, except I did have some issue with scaling vertical games.

It works if I delete it, then use `cvt` to recalculate it and add it back again with the same name.

**Comment by sonninnos** [comment]
The core has been offering the proper refresh rate for a while, so this shouldn't be an issue anymore, or if it is, the core can't do much differently about it.
