### ISSUE TITLE
Update MAME 0.212

### ISSUE THREAD

**Issue by ToniBC** [libretro/mame#108]
It is rare that this core remains in 0.209, since it left earlier this month the 0.210 solving the problems of Neo-Geo CD among many others.

We are almost in the next, in 3 days will leave the 0.211.

This is more like a reminder, since several programmers told me that it will be left as an error, so anyone can see it pending and update.

As this is a fan, I guess the person who updated it will be busy and in the end thank everyone for the effort in this core which is that I always use for convenience.

**Comment by Sterophonick** [comment]
It has been done

**Comment by ToniBC** [comment]
Thank you very much, I saw it in the commit, now in theory the NeoGeo CD games would have to work again among the various improvements.

In two days the 0.212 leaves, but calmly, as long as it is updated, there is no problem.

Thank you very much for the effort.

**Comment by ToniBC** [comment]
Thank you very much for the effort to update it to 0.212.
