### ISSUE TITLE
(Request) Option to enable TATE mode in Mame 0.211

### ISSUE THREAD

**Issue by illando** [libretro/mame#114]
Would be great to have an option to enable TATE mode in MAME core setting, especially on mobile devices where you can play in portrait orientation (androind and ios).
Actually everything is scaled inside a landscape frame where the mame auto-rotation option places the vertical games centered leaving 2 black sidebar on the side. And that’s perfectly OK if you play using the mobile device in landscape mode.
But if you rotate the device, Retroarch is not able to adapt the video to portrait fullscreen, it scale the video by its width, including the 2 black sidebars, also if you select a vertical resolution in Retroarch video settings the black sidebars are still there influencing a proper fullscreen scaling.

**Comment by sonninnos** [comment]
The option has been added to stop internal rotation, or either let libretro rotate (by default).
