### ISSUE TITLE
Mame internal rotation problem

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/mame#12]
Rotating from Mame Gui keeps the previous framebuffer resolution with a wrongly scaled picture in its middle.

I tried to disable it for vertical games (as it is automatically applied for those) [from here](https://github.com/libretro/mame/blob/master/src/emu/emuopts.cpp#L100) but it gives the same result as using the GUI rotation = wrong scale.

This feature is great to put a vertical game in the right direction to have vertical scanlines with shaders and it can be applied to particular games/drivers/other with mame ini system.

I tried to modify [libretro.cpp](https://github.com/libretro/mame/blob/master/src/osd/libretro/libretro-internal/libretro.cpp) and swapped width/height but it got me nowhere.
It seems it's not that simple with this core.

**Comment by r-type** [comment]
can you provide some screenshot , one with  libretro core wrong aspect  and one with upstream correct aspect ?

**Comment by Tatsuya79** [comment]
[Guwange with Mame Stand alone.](https://postimg.org/image/bm19zo31f/)
[With libretro-mame-180.](https://postimg.org/image/rj01wdvfn/)

[And how it was with libretro-mame-170.](https://postimg.org/image/eqbxwgjtv/) The ratio had to be changed to 4:3 manually.

This is with Mame rotation CW90.

**Comment by r-type** [comment]
thanks I'll test and investigate.
on side note, for the resolution and aspect , all the magic are done in osd/libretro/window.cpp

**Comment by r-type** [comment]
can you try this patch (3 lines to add ) http://pastebin.com/4xxuj97N
it should solve your problem , but i want to be sure it doesn't break anything before apply.
and i don't have time to test mame a lot these days.

**Comment by r-type** [comment]
ok bad patch , please wait a minute a correct one.
I've change the link above to the correct one to test.

**Comment by Tatsuya79** [comment]
Working nicely, great!

Now vertical games are like Mame stand-alone when rotated = 4:3 for tate / portrait mode.

If I use the trick to rotate them again with Retroarch I must choose an aspect ratio of 3:4 manually.
Do you think we could do all this directly in the Mame core like it is done with FBA?

Perhaps disable [Mame auto rotation](https://github.com/libretro/mame/blob/master/src/emu/emuopts.cpp#L100) (this will give us portrait mode with vertical scanlines) then do the rotation on the retroarch side with the adequate ratio (we'll have vertical games adjusted for screen in landscape and with vertical scanlines).

**Comment by r-type** [comment]
for the vertical scanline trick, we have first to see what is the impact to the mame source code side.
and also look at how they deal it with their shader engine.

**Comment by Tatsuya79** [comment]
Yes it's probably better to not touch anything on the Mame side.
We could call mame ror and then Retroarch rotation inside window.cpp for vertical games if that's possible.

I don't know about the shader code in mame; there are so many different things with hlsl, glsl and bgfx now...

**Comment by Tatsuya79** [comment]
Could the shader rotation happen [along those lines?](https://github.com/libretro/mame/blob/master/src/emu/render.cpp#L1904)

**Comment by r-type** [comment]
could you post an screenshot of what should be the final result (rotated like now with vertical scanline ?).

**Comment by Tatsuya79** [comment]
[Mame 181 stand-alone standard.](http://postimg.org/image/6x6w4nd7r/)

[Retroarch Mame with fix for rotation + mame ror + retroarch rotation 90° + ratio 3:4.](http://postimg.org/image/ebw7x0z3b/)

Ideally we could use retroarch rotation to display on a screen in portrait mode, I mean the ratio should follow the rotation.

**Comment by Tatsuya79** [comment]
We could have vertical games with vertical scanlines by making a core option that would enable autoror (autoration of vertical games to the right).

Along a call to
```
unsigned rotation = 1; (or is it 3?)
environ_cb(RETRO_ENVIRONMENT_SET_ROTATION, &rotation);
```
when a vertical game is started (I couldn't get this part right).

And perhaps a change of aspect in src\osd\libretro\window.cpp is needed (when the core option is enabled).

**Comment by Tatsuya79** [comment]
[The rotation happens in render.cpp it seems.](https://github.com/libretro/mame/blob/master/src/emu/render.cpp#L2474)
I don't know how or where to use that and add libretro rotation.

**Comment by tcamargo** [comment]
@Tatsuya79 still relevant?

**Comment by Tatsuya79** [comment]
Yes, just try any vertical game with a crt shader you'll get horizontal scanlines instead of vertical.

**Comment by sonninnos** [comment]
I think this can be closed.
