### ISSUE TITLE
Tiger handhelds, only a bunch of them work.

### ISSUE THREAD

**Issue by Tasosgemah** [libretro/mame#123]
I updated to 214 and it still won't load most Tiger games, only some. About 1/3 of them.

I had the same issue in 212 but i thought it was because 212 didn't support the more recent ones but the same thing happens in 214, where all should work (they do in the standalone).

The ones that don't work don't give me any errors. The program just closes gracefully or doesn't load at all.

An example of a working game is Addams Family. An example of a non-working game is Batman.

All roms tested are from the 214 romset.

**Comment by tcamargo** [comment]
Could you please test a newer build? If problem persist, please reopen this issue.
