### ISSUE TITLE
Game & Watch extremely slow when using artwork

### ISSUE THREAD

**Issue by Tasosgemah** [libretro/mame#124]
When i play any Game & Watch game with their artwork, MAME becomes very slow, like only 50% speed. Meanwhile the system isn't using all of it's resources. MAME slows down internally for some reason.

Tried every possible option or driver, the speed is always around 50%. This doesn't happen in the standalone, Game & Watch is full speed with the artwork and the system doesn't break a sweat.

I'm using a Windows 7 machine with an i5 4670 CPU.

**Comment by tcamargo** [comment]
Could you please test a newer build? If problem persist, please reopen this issue.
