### ISSUE TITLE
4-way joystick simulation

### ISSUE THREAD

**Issue by BR4iNL355D35iGN5** [libretro/mame#129]
Like in the mame2003-plus core, a feature to enable/disable 4-way joystick simulation would be a big plus!

**Comment by tcamargo** [comment]
@BR4iNL355D35iGN5 have to tried to create INIs for games which need 4-way joysticks?
Anyway, I'm looking how to have an option to set the joymap.

**Comment by BR4iNL355D35iGN5** [comment]
Nice! Thanx.
