### ISSUE TITLE
Crash on loading in Retroarch 1.8.2 in Ubuntu 18.04

### ISSUE THREAD

**Issue by emersonnovais** [libretro/mame#130]
Since the last update the core give me the following error message. The bios files and the other configuration are correctly set:

emula-os@emulaos-Vostro-3500:/Roms/MAME$ retroarch -f -L /usr/lib/x86_64-linux-gnu/mame_libretro.so tmnt.zip
[WARN] --libretro argument "/usr/lib/x86_64-linux-gnu/mame_libretro.so" is neither a file nor directory. Ignoring.
[INFO] RetroArch 1.8.2 (Git cf97f39)
[INFO] Redirecting save file to "./tmnt.srm".
[INFO] Redirecting savestate to "./tmnt.state".
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i5 CPU       M 460  @ 2.53GHz
[INFO] Capabilities:  MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2
[INFO] Built: Dec 26 2019
[INFO] Version: 1.8.2
[INFO] Git: cf97f39
[INFO] =================================================
[ERROR] Frontend is built for dynamic libretro cores, but path is not set. Cannot continue.
[ERROR] Fatal error received in: "init_libretro_symbols()"

**Comment by telanus** [comment]
I get the similar problem trying to run the core. 

`
./retroarch: relocation error: ~/retroarch/cores/mame_libretro.so: symbol _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev version GLIBCXX_3.4.26 not defined in file libstdc++.so.6 with link time reference`

I'm on Kubuntu 18.04.3

**Comment by telanus** [comment]
looks like a few people is getting the same problem :https://forums.libretro.com/t/mame-libretro-status/25718/12

**Comment by tcamargo** [comment]
Builildbot probably got updated and is linking against a newer glibc.

**Comment by inactive123** [comment]
This is correct, yes.

**Comment by inactive123** [comment]
We had to upgrade specifically too because of MAME and some other emulators that started to require newer compilers. While this is not our preference and we would prefer things to be as backwardscompatible as possible, if people want newer versions of those emulators we are forced to move in lockstep with them unfortunately.

**Comment by emersonnovais** [comment]
The MAME 2016 core has the same problem. The 2014 version runs correctly and with no errors.

**Comment by emersonnovais** [comment]
I made the update to new GCC version and now works. Thanks, @telanus for the tip.

Open a terminal and type:

**_sudo add-apt-repository ppa:jonathonf/gcc-9.0
sudo apt-get update
sudo apt upgrade_**

Now works. I will close the issue.
