### ISSUE TITLE
segac2.cpp driver doesn't work anymore!

### ISSUE THREAD

**Issue by r3tro80** [libretro/mame#133]
All the games using segac2.cpp driver aren't working anymore.

Games are BORENCH, COLUMNS, STACK COLUMNS, THUNDER FORCE AC, SONIC FIGHTER, SONIC CAR PATROL, etc...

**Comment by tcamargo** [comment]
could you please post some logs?

**Comment by r3tro80** [comment]
The final error is: **double free or corruption (!prev)**

[runcommand.log](https://github.com/libretro/mame/files/4135961/runcommand.log)

**Comment by tcamargo** [comment]
Could you please test on mame? I’m on vacation and only check in 2 weeks.

**Comment by r3tro80** [comment]
I will install mame standalone later and i will let you know... Anyway i always used this core for these games... seems the problem has been introduced on one of the last commits.

**Comment by r3tro80** [comment]
In mame standalone works OK! The problem is only in libretro core.

**Comment by tcamargo** [comment]
> In mame standalone works OK! The problem is only in libretro core.

thx! gonna check in 2w.

**Comment by Tatsuya79** [comment]
They work fine on recent RA nightly, 0.218 core on win7 x64.

**Comment by r3tro80** [comment]
It doesn't work on latest Debian x64 with RetroPie's RetroArch 1.7.5 and 1.8.4.

**Comment by r3tro80** [comment]
I reinstalled Debian 10.3 from scratch and now it works. It was a fault of my installation. Thanks.
