### ISSUE TITLE
Activate the plugins

### ISSUE THREAD

**Issue by illando** [libretro/mame#135]
Would be possible to activate the MAME plugins?
I tried to copy the Plugins folder in system/mame and in saves/mame, and to copy the file plugin.ini and mame.ini system/mame/ini but nothing happen.

Any help?

**Comment by 1985a** [comment]
YES, it is possible. I did it. The only thing is that when you finish a game it goes crash.

**Comment by illando** [comment]
@1985a How did you do it???

**Comment by 1985a** [comment]
it's a large process. I will write a mini-guide. Stay tune for it.

**Comment by 1985a** [comment]
@illando Hi. Last night I wrote the tutorial on my personal blog. The only thing is that it is in Spanish. I still learning English I need to improve more my writing.
[page here](https://wp.me/p9kgmz-lZ)

Perhaps if you use Google translator you can read it.
Furthermore, there are some pictures and code, if you have problems to deal with Spanish.

**Comment by illando** [comment]
@1985a Hey! I'm Italian, so it's not a problem to read Spanish tutorial.
But the link you posted seems to be offline!

**Comment by 1985a** [comment]
Due to the firewall you can't reach that page. I will open until tomorrow night.
