### ISSUE TITLE
Mame crash when no mouse

### ISSUE THREAD

**Issue by Immersion95** [libretro/mame#136]
The older Mame core don't crash but the newest does.

Is that already known ?

**Comment by tcamargo** [comment]
No clue. Could you provide some logs?

**Comment by Immersion95** [comment]
I edited the title, it crashes when there is no mouse.

Some games work without it (ZN based games but others don't like CPS, Neo-Geo).

I added a mouse and it works now :) !

**Comment by tcamargo** [comment]
Dup of https://github.com/libretro/mame/issues/41.
