### ISSUE TITLE
Build fails on RetroPie 4.5.1 (Raspbian Stretch) on RPi3B+ due to only having clang 6

### ISSUE THREAD

**Issue by c0d3h4x0r** [libretro/mame#139]
The version of Raspbian that RetroPie is built on top of does not support clang 7.  Someone updated this project to require clang 7 to build, so it is no longer possible to successfully install this core from source code from the RetroPie-Setup menus.

**Comment by tcamargo** [comment]
Hi. You should report this upstream. Mame updated the compilers requirements sometime ago. It is failing even with clang8 for me. Compiling fine with clang11.

**Comment by c0d3h4x0r** [comment]
They rudely closed it in under 20 minutes: https://github.com/mamedev/mame/issues/6409#issuecomment-596034086

**Comment by rb6502** [comment]
Sorry about the rudeness, but the answer remains the same: we ride close to the bleeding edge of portable modern C++, so the required compiler keeps moving forward.  The Pi 3 is hilariously underpowered for modern MAME so you aren't missing anything, but if you really want to make it work it should be possible to install the current Clang 9 release.

**Comment by cuavas** [comment]
I test each MAME release on Linux with clang 6.0.1 – it works just fine with both GNU libstdc++ and libc++ – so it’s either an issue with ARM targets or something else screwy in the RetroPie environment.

**Comment by tcamargo** [comment]
@cuavas Thanks for the feedback. Did you test with clang8?

`Compiling src/devices/machine/nsc810.cpp...
clang++    -MMD -MP -MP -D__LIBRETRO__ -DNDEBUG -DPTR64=1 -DCRLF=2 -DLSB_FIRST -DFLAC__NO_DLL -DPUGIXML_HEADER_ONLY -DNATIVE_DRC=drcbe_x64 -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -I"../../../../../src/osd" -I"../../../../../src/emu" -I"../../../../../src/devices" -I"../../../../../src/mame" -I"../../../../../src/lib" -I"../../../../../src/lib/util" -I"../../../../../3rdparty" -I"../../../../generated/emu" -I"../../../../generated/emu/layout" -I"../../../../../3rdparty/asio/include" -I"../../../../../3rdparty/expat/lib" -I"../../../../../3rdparty/libflac/include"  -O2 -m64 -fPIC -arch x86_64 -pipe -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wundef -Wformat-security -Wwrite-strings -Wno-sign-compare -Wno-conversion -Wno-error=deprecated-declarations -Wno-cast-align -Wno-tautological-compare -Wno-unused-value -Wno-constant-logical-operand -fdiagnostics-show-note-include-stack -Wno-unknown-warning-option -Wno-extern-c-compat -Wno-unknown-attributes -Wno-ignored-qualifiers -Wno-pragma-pack -m64 -DHAVE_IMMINTRIN_H=1 -std=c++14 -Woverloaded-virtual -include ../../../../libretro/obj/x64/libretro/emu.h -include /Users/buildbot/buildbot/osx/libretro-mame/src/osd/libretro/retroprefix.h -o "../../../../libretro/obj/x64/libretro/src/devices/machine/nsc810.o" -c "../../../../../src/devices/machine/nsc810.cpp"
../../../../../src/devices/machine/netlist.cpp:342:10: error: no viable conversion from returned value of type 'unique_ptr<std::__1::basic_istringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >, arena_deleter<[...], std::__1::basic_istringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >>>' to function return type 'unique_ptr<std::__1::basic_istream<char>, arena_deleter<[...], std::__1::basic_istream<char>>>'
                return MOVE_UNIQUE_PTR(ret);
                       ^~~~~~~~~~~~~~~~~~~~
../../../../../src/devices/machine/netlist.cpp:36:28: note: expanded from macro 'MOVE_UNIQUE_PTR'
#define MOVE_UNIQUE_PTR(x) (x)
                           ^~~`

Full log: http://paste.libretro.com/184049

I saw a macro workaround for old clang versions. Unfortunately, i can't test. That log is from libretro buildboot. My setup has clang11 (macosx).

**Comment by rb6502** [comment]
Apple's Clang version numbers are inflated to match the Xcode versions. Clang 11 on MacOSX is branched from somewhere between Clang 8 and 9 on the mainline, I believe.

**Comment by c0d3h4x0r** [comment]
> The Pi 3 is hilariously underpowered for modern MAME so you aren't missing anything

Incorrect.  There are plenty of accuracy fixes in newer MAME versions for older games, as well as newly-added support for older games, that still run just fine on a Pi 3B+, and those are desirable to have.

**Comment by tcamargo** [comment]
Ok, but please use clang9.

**Comment by c0d3h4x0r** [comment]
I hear you, but I don't have control over that.  RetroPie uses whatever it uses when the user chooses to "Install module from source".  Sounds like maybe you should open an issue on RetroPie to upgrade the version of clang they use for building `lr-mame` from source?  You'd make a more persuasive case for that to Jools Wills than I would.
