### ISSUE TITLE
Crash at launch

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/mame#14]
Now mame will build, but i got those errors : 

Error: attempt to free untracked memory 0x1169f50 in (null)(0)!
Ignoring MAME exception: Error: attempt to free untracked memory
retroarch: src/lib/util/delegate.h:513: delegate_mfp::delegate_mfp(_MemberFunctionType, _MemberFunctionClass*, _ReturnType*, _StaticFunctionType) [with _MemberFunctionType = void (osd_common_t::*)(); _MemberFunctionClass = osd_common_t; _ReturnType = void; _StaticFunctionType = void (*)(delegate_generic_class*)]: Assertion `sizeof(mfp) == sizeof(*this)' failed.

**Comment by twinaphex** [comment]
Can we close this now?

**Comment by barbudreadmon** [comment]
Yes
