### ISSUE TITLE
Add a core option to disable Retroarch Hotkey Binds

### ISSUE THREAD

**Issue by cometjo** [libretro/mame#140]
I'm trying to play Apple II (apple2c) games and the keyboard input is conflicting with the Hotkeys.

**Comment by tcamargo** [comment]
Core is set for arcade games. Not sure it is the best option for computer games. Can't you use another core/emu?

**Comment by Sanaki** [comment]
You can press scroll lock in retroarch for game focus mode (disables hotkeys), but I'm pretty sure mame has some internal hotkeys that'll still trigger.

**Comment by tcamargo** [comment]
@Sanaki thx for the workaround. I will close this issue.
