### ISSUE TITLE
Linux: make error

### ISSUE THREAD

**Issue by guoyunhe** [libretro/mame#142]
```
> make -f Makefile.libretro  
make RETRO=1 REGENIE=1 VERBOSE=1 NOWERROR=1 OSD="retro" NO_USE_MIDI=1 NO_USE_PORTAUDIO=1 PYTHON_EXECUTABLE=python2 CONFIG=libretro  PTR64=1  LIBRETRO_OS="unix" ARCH="" LIBRETRO_CPU="x86_64" -static-libgcc -static-libstdc++  TARGET=mame
make: invalid option -- 'a'
make: invalid option -- 'c'
make: invalid option -- '-'
make: invalid option -- 'a'
make: invalid option -- 'c'
make: invalid option -- '-'
```

**Comment by tcamargo** [comment]
@twinaphex could you please revert?

**Comment by jstolarek** [comment]
Ugh. Sorry. It would be much easier if CI wasn't broken :-/

**Comment by inactive123** [comment]
You should test this locally in the future.

**Comment by jstolarek** [comment]
The problem is I can't test this locally, most likely for the same reason why I can't run a core downloaded from a buildbot, i.e. dependency on stdlib version that I simply don't have on my system.

**Comment by tcamargo** [comment]
> The problem is I can't test this locally, most likely for the same reason why I can't run a core downloaded from a buildbot, i.e. dependency on stdlib version that I simply don't have on my system.

You can build libretro-mame with an old libc. -static-libc is a gcc/ld option. Not a make option.

**Comment by jstolarek** [comment]
Ugh. I just realized that to build a core I need to run `make -f Makefile.libretro` and not `make` like the readme says. That also explains why the CI is failing. And yes @tcamargo , you're right that I can build the core locally. I'll devise a proper tested fix and maybe update the CI and readme while I'm at it.

**Comment by guoyunhe** [comment]
Solved in latest master. Closing.
