### ISSUE TITLE
D-pad working with lr-mame2010 and lr-mame2003plus but not lr-mame

### ISSUE THREAD

**Issue by yepyepyep4711** [libretro/mame#154]
Hello,

I use an 8bitdo NES30 Gamepad and see the following behaviour:
With lr-mame2010 and lr-mame2003plus, there is no issue. With lr-mame, all buttons keep working but I lose the D-pad.
It doesn't matter whether it's connected with bluetooth or usb cable, it's the same behaviour.
I've tested this with retroarch 1.8.6 on batocera and retroarch 1.8.8 standalone on win7 64.
I discovered this behaviour while searching for a core that would display mame overlays like the clutch in Outrun in a high resolution. The alternate renderer in the current lr-mame does this, but then I can't steer :/
Note that the D-pad works fine in the retroarch menus themselves. It's once in the game that it stops working.

**Comment by tcamargo** [comment]
That was corrected long ago. Do you use mapping cfgs? Please check https://github.com/libretro/mame/pull/126.

**Comment by yepyepyep4711** [comment]
I'm not quite sure what you mean. I see this is a similar issue, but what should I check?

I've had another look today, and here's what I found. On Retroarch 1.8.8 win 7 64bit, I can nearly solve the issue by changing the controller driver from the pre-configured xinput to dinput. If I do this, then all is fine with mame 2003 plus and mame 220, but mame 2010 still has no d-pad.

With xinput, the keys were getting mapped under retroarch, but always with the mention (N/A). Manually would assign key numbers to all buttons, while auto would assign descriptors (select, etc.), but the result would be the same.

With that in mind, I assume I could achieve a similar result with the correct driver under batocera linux. The options available are udev, linuxraw, parport, sdl2, hid and null, do you have any recommendation what _should_ work? It's set on udev at the moment, but changing it seems to need a restart to work and somehow that configuration change won't save, so I first need to find out how to make it stick before I can test it.

While we're at it: there is an input driver and a controller driver. What's the difference? How do these interact?
EDIT: I found this. The libretro docs say controller driver is gamepads and joysticks, input is any other input. They also say udev is recommended, but not much else sadly.

**Comment by yepyepyep4711** [comment]
After further testing, I have found out that it's some digital to analogue issue. A four-way game like berzerk will run fine with xinput. Arkanoid or OutRun will not, they will need dinput. Is there a reason for xinput being default?

**Comment by yepyepyep4711** [comment]
More testing: so xinput will only accept analogue input for analogue devices, while dinput will accept digital input and convert it. So it's either switch to dinput or to an older core if you don't have an analogue input device. Now I know. Maybe this will help someone else.
