### ISSUE TITLE
version bump 0.221

### ISSUE THREAD

**Issue by HoJo215** [libretro/mame#156]
Is there a chance we can get a version bump of 0.221 before 0.222 releases?
Mame4Rage2's new source is based off 0.221 and I wanted to build a libretro version.

**Comment by breisig** [comment]
The latest version (currently 0.222) would be great.

**Comment by HoJo215** [comment]
..and 0.222 is released. Well I guess that is that. I had a feeling this was going to happen.

**Comment by tcamargo** [comment]
https://github.com/libretro/mame/pull/159
