### ISSUE TITLE
Pause not working as expected

### ISSUE THREAD

**Issue by johnodon** [libretro/mame#157]
Ubuntu 18.04.4 running latest RetroPpie (v4.6.2)

[INFO] RetroArch 1.8.8 (Git 9552f87)
[INFO] Redirecting save file to "/home/pi/RetroPie/roms/mame-libretro/defender.srm".
[INFO] Redirecting save state to "/home/pi/RetroPie/roms/mame-libretro/defender.state".
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i7-4785T CPU @ 2.20GHz
[INFO] Capabilities:  MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX
[INFO] Built: Jul  2 2020
[INFO] Version: 1.8.8
[INFO] Git: 9552f87

If I load a ROM (defender.zip) in this case and press 'p' to pause, the game pauses as expected.  However, pressing 'p' again does not unpause the game.  Rather, the screen just dims lightly.  I have to press the 'p' key 2 more times to unpause.

John

**Comment by sonninnos** [comment]
This was because keyboard states were being used, resulting in P being sent to both RA and the core, which then both pause. It can no longer happen.
