### ISSUE TITLE
Rad Rally problem

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/mame#16]
Rad Rally (radr) isn't working here while it's OK on Mame 0.181 stand-alone (0.181 romset).

Pretty strange as other segas32 games seem to work fine.
Haven't seen a recent commit or issue about it on Mame Tester/source.

**Comment by r-type** [comment]
Hi, 
I did not know this game , nice! 
BTW it works fine on linux, I ll try it on windows if i can.

**Comment by r-type** [comment]
Strange on windows i  only see the gearbox . rest is black

**Comment by Tatsuya79** [comment]
Exact same here.
And you can go into the menu, change the display, move the gear box left or right... but no game.

**Comment by Tatsuya79** [comment]
Get ready for this one.
So this game doesn't launch BUT if you start an internet access in Retroarch then it works.
I start Retroarch, got to Online Updater, select Core Updater just to launch an access to the buildbot index, then I launch radr...
...and it works! 

WTF?

**Comment by r-type** [comment]
Crazy but true. I've just try and the trick works also with wine!

**Comment by Tatsuya79** [comment]
It works even if you start the game (black screen) then go to online updater to do the trick, go back to Mame the game is starting.

I also noticed Mame joystick deadzone and saturation aren't working.
Is that still a limitation on Retroarch end (I think there were issues with analog..?) or something that can be fixed?

**Comment by Enverex** [comment]
(not a fix or anything, just a note for anyone that stumbles over this but wants to play the game)
This is the arcade port of a NES game, so playing the NES version should be virtually identical.

**Comment by Tatsuya79** [comment]
Nope, you're confused with Rad Racer or something.
http://www.progettoemma.net/gioco.php?&game=radru&lang=en

**Comment by Tatsuya79** [comment]
And it's magically working now with current build, I close this.

**Comment by Enverex** [comment]
Looks like you're right, not sure how I mixed the two up there. Sorry.
