### ISSUE TITLE
Compiling error on Retropie

### ISSUE THREAD

**Issue by jlopezvil** [libretro/mame#160]
There is a compiling last version 0.222  error on Retropie in an raspberri pi4b.

Error is there is not files for arm in 3rdparty/asmjit/src/asmjit/

Here build log with error ...

Archiving libascii.a...
Compiling 3rdparty/asmjit/src/asmjit/core/arch.cpp...
../../../../../3rdparty/asmjit/src/asmjit/core/arch.cpp:32:12: fatal error: ../arm/armarchdata_p.h: No existe el fichero o el directorio
   #include "../arm/armarchdata_p.h"
            ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [asmjit.make:1059: ../../../../libretro/obj/libretro/3rdparty/asmjit/src/asmjit/core/arch.o] Error 1
make[1]: *** [Makefile:82: asmjit] Error 2
make[1]: *** Se espera a que terminen otras tareas....
Compiling src/mame/drivers/caswin.cpp...
Archiving libaristocr.a...
make: *** [makefile:1385: linux] Error 2
Removing additional swap
/home/pi
Could not successfully build lr-mame - MAME emulator - MAME (current) port for libretro (/home/pi/RetroPie-Setup/tmp/build/lr-mame/mamearcade_libretro.so not found).

**Comment by rtissera** [comment]
AsmJit does not seem supported on arm so far, we need to disable it and associated MAME stuff making use of it on ARM platforms.

**Comment by tcamargo** [comment]
@rtissera it was working on arm before. It is something new or a problem in your last PR.

**Comment by rtissera** [comment]
@tcamargo this is new as mamedevs added asmjit dependency for drc x86 and x64 backends.
The bug does happen if trying to compile natively (not cross-building) on ARM (which RetroPie does) because asmjit tries to build for host platform and the ARM support is currently a stub even on their github repo...
I am testing a patch not to build asmjit if we use C DRC backend (which is the case except on x86/x64 platforms)

**Comment by jlopezvil** [comment]
Yes. Error is given with native compile on the raspberry. Not cross compile.
I will desire to make a native compile... Thanks.

here atach the sh file on retropie to compile

pams will be  "local params=(OSD=retro RETRO=1 NOWERROR=1 OS=linux TARGETOS=linux CONFIG=libretro NO_USE_MIDI=1 TARGET=mame SUBTARGET=arcade"

[lr-mame.sh.txt](https://github.com/libretro/mame/files/4873931/lr-mame.sh.txt)

**Comment by jlopezvil** [comment]
I will try to compile when your pull request will be commited.
