### ISSUE TITLE
Retropie lrmame doesnt run anygame

### ISSUE THREAD

**Issue by jlopezvil** [libretro/mame#163]
I have been playing mame games on retropie with lastest lr-mame compilation v220

Now i have compiled v222 and anygames get to start ... No log avaiable also ... Only run command

As i Say compilation v220 runs good a lot of games...   New v222 not runs anygame ...

Some trouble with files?

**Comment by breisig** [comment]
I am having the exact same issue.

**Comment by bluestang2006** [comment]
RetroPie’s Retroarch log file for reference on this issue - https://pastebin.com/zMQtmSTK

**Comment by rtissera** [comment]
Looking into it right now ;)

**Comment by bluestang2006** [comment]
> Looking into it right now ;)

Here is the compile log from the RetroPie Setup script - https://pastebin.com/h8mxUE7n

It seems like the amount of projects compiled seems rather low. Time to compile is about ~ 4 hrs which is rather short for a Pi 4 build.

**Comment by jlopezvil** [comment]
Games are running .. At least some I have tested ....
Close the bug.
