### ISSUE TITLE
the newest nightly build get stuck on WIndows 10

### ISSUE THREAD

**Issue by ghost** [libretro/mame#166]
the mame 0.220 core worked fine with this configuration.But the newly updated 0.222 core nightly build does not work on WIndows 10 for me.
I have MAME 0.222 and the romsets  are updated.
when I use the work lrmame core to load the game, it only gives me a blank white windows and loses response.the  task manager shows my CPU usage is at 25%,and it last ever after.
The only way I know to end this is to terminate it using the task manager.
The log is this https://pastebin.com/1UDu6igY
I notice that it's last line is declaring the manufacturer, and no further infomation.I don't know what is wrong.
I've tried this on my surface pro 7 and my working computer(also using Windows 10),the situations are the same.
Besides, I've tried the new lrmame on Linux(I'm using the Manjaro),and it works fine.

**Comment by inactive123** [comment]
Yeah we're aware of this. I think @tcamargo and @rtissera are trying to get to the bottom of it.

**Comment by cubatilles** [comment]
I was experiencing the same problem. Thanks for the clarification. As the "fix" pull request is merged I didn't know if it was the build not being built yet by the buildbot or if it's still broken. I'll have patience. Thanks fot he work.

**Comment by tcamargo** [comment]
"Fix" PR is not in yet. I redid the whole merge.
Check https://github.com/libretro/mame/tree/mame-0.222. That branch will be promoted as soon as I finish some tests.

**Comment by tcamargo** [comment]
Master updated.

**Comment by ghost** [comment]
the new nightly build works fine.
