### ISSUE TITLE
Enable core for android-aarch64

### ISSUE THREAD

**Issue by tcamargo** [libretro/mame#173]

**Comment by tcamargo** [comment]
Test build: https://camargo.batocera.org/libretro-mame/android-aarch64/mame_libretro_android-pacman_only.so
**Only pacman driver is active.**

**Comment by tcamargo** [comment]
New test build: https://camargo.batocera.org/libretro-mame/android-aarch64/mame_libretro_android.so
**All drivers** - **Broken**

**Comment by lim2222** [comment]
The pacman's build working great but the new test one not,when i try to load core it say no core.

**Comment by tcamargo** [comment]
> The pacman's build working great but the new test one not,when i try to load core it say no core.

Ok, thx! I had to modify some clang flags, -fno-integrated-as,  for the full build. I guess i can't do that.

**Comment by tcamargo** [comment]
`07-20 21:23:59.257 31592 31681 E RetroArch: Failed to open libretro core: "/data/user/0/com.retroarch.aarch64/cores/mame_libretro_android.so"
07-20 21:23:59.258 31592 31681 E RetroArch: Error(s): dlopen failed: "/data/data/com.retroarch.aarch64/cores/mame_libretro_android.so" has invalid shdr offset/size: 413212352/2240`

**Comment by tcamargo** [comment]
Opened bug in Android NDK: https://github.com/android/ndk/issues/1322

**Comment by tcamargo** [comment]
New beta build.
https://camargo.batocera.org/libretro-mame/android-aarch64/mame_libretro_android.so
