### ISSUE TITLE
[Android] Mame Current, crash after loading rom

### ISSUE THREAD

**Issue by Denshadego** [libretro/mame#174]
Mame (current) crashes Retroarch after loading a rom on Android (ra32), the same games run on Windows on the same core and I have the same bios on both setups. Here's the log:

> RetroArch 1.8.9 (Git 324eb4f)
> === Build =======================================
> Capabilities:  NEON VFPv3 VFPv4
> [INFO] Built: Jul 16 2020
> [INFO] Version: 1.8.9
> [INFO] Git: 324eb4f
> [INFO] =================================================
> [Environ]: SET_PIXEL_FORMAT: RGB565.
> [Overrides]: Redirecting save file to "/storage/emulated/0/RetroArch/saves/.srm".
> [Overrides]: Redirecting save state to "/storage/emulated/0/RetroArch/states/.state".
> Version of libretro API: 1
> [INFO] Compiled against API: 1
> [Audio]: Set audio input rate to: 48000.00 Hz.
> [Video]: Video @ 876x720
> [Video]: Starting threaded video driver ...
> Android EGL: GLES version = 2.
> [EGL] Falling back to eglGetDisplay
> [EGL]: EGL version: 1.4
> [GL]: Found GL context: android
> [GL]: Detecting screen resolution 0x0.
> [EGL]: Current context: 0xe0bdd640.
> [GL]: Vendor: Qualcomm, Renderer: Adreno (TM) 512.
> [GL]: Version: OpenGL ES 3.2 V@269.0 (GIT@dcd4b96, I568c71768a) (Date:04/30/18).
> [GL]: Using resolution 1920x1200
> [GL]: Default shader backend found: glsl.
> [Shader driver]: Using GLSL shader backend.
> [GL]: Stock GLSL shaders will be used.
> [GLSL]: Found GLSL vertex shader.
> [GLSL]: Found GLSL fragment shader.
> [GLSL]: Linking GLSL program.
> [GLSL]: Found GLSL vertex shader.
> [GLSL]: Found GLSL fragment shader.
> [GLSL]: Linking GLSL program.
> [GLSL]: Found GLSL vertex shader.
> [GLSL]: Found GLSL fragment shader.
> [GLSL]: Linking GLSL program.
> [GL]: Using 4 textures.
> [GL]: Loaded 1 program(s).
> [Joypad]: Found joypad driver: "android".
> [Font]: Using font rendering backend: stb-unicode.
> [Video]: Found display server: android
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/composite.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTCOMP_256.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTCOMP_480.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTCOMP_DOWNSAMPLE_240.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTPC.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTRGB1_256.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTRGB1_480.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTRGB1_DOWNSAMPLE_240.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTRGB2_256.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTRGB2_480.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTRGB2_DOWNSAMPLE_240.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTSTAT1_256.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTSTAT1_480.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTSTAT1_DOWNSAMPLE_240.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTSTAT2_256.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTSTAT2_480.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTSTAT2_DOWNSAMPLE_240.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTVHS_256.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTVHS_480.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/deband.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/fakelottes_curve.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/fakelottes_dotmask.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/fakelottes_dotscan.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/fakelottes_dotscan_vert.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/fakelottes_scanlines.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/film_noise_simple.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/gb-palette.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/gba-color.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/gbc-color.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/grain_noise.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/lcd-grid-v2.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/LCD.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/lcd1x.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/lcd3x.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/LCD_GBA.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/LCD_GBC.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/LCD_NDS.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/LCD_PSP.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/LCD_VB.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/nds-color.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/ntsc-colors.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/psp-color.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/response-time.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/retroarch.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/scanline.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/scanlines-sine-abs.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/stock.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/STOCK_240.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/tvout-tweaks.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/vhs.glsl"
> [OpenSL]: Requested audio latency: 128 ms.[OpenSL]: Setting audio latency: Block size = 768, Blocks = 32, Total = 24576 ...
> [Display]: Found display driver: "gl".
> [Font]: Using font rendering backend: stb-unicode.
> [Font]: Using font rendering backend: stb-unicode.
> [Font]: Using font rendering backend: stb-unicode.
> [Display]: Found display driver: "gl".
> [LED]: LED driver = 'null' 0xccba54d8
> [MIDI]: Input disabled.
> [MIDI]: Output disabled.
> [MIDI]: Initialized "null" driver.
> [SRAM]: SRAM will not be saved.
> [Playlist]: Loading history file: [/data/user/0/com.retroarch.ra32/content_history.lpl].
> [Playlist]: Loading history file: [/data/user/0/com.retroarch.ra32/content_music_history.lpl].
> [Playlist]: Loading history file: [/data/user/0/com.retroarch.ra32/content_image_history.lpl].
> [Playlist]: Loading favorites file: [/data/user/0/com.retroarch.ra32/content_favorites.lpl].
> [core updater] Download of core list 'http://buildbot.libretro.com/nightly/android/latest/armeabi-v7a/.index-extended' failed: Internal error.
> WindowFocusChanged: 0xde15b880 -- 0
> WindowFocusChanged: 0xde15b880 -- 1
> [CORE]: Using content: /storage/emulated/0/RetroArch/_ROMS/CAVE SH3/espgal2.zip.
> Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
> [CORE]: Unloading core..
> [CORE]: Unloading core symbols..
> Threaded video stats: Frames pushed: 1904, Frames dropped: 0.
> RetroArch 1.8.9 (Git 324eb4f)
> [Overrides]: Redirecting save file to "/storage/emulated/0/RetroArch/saves/espgal2.srm".
> [Overrides]: Redirecting save state to "/storage/emulated/0/RetroArch/states/espgal2.state".
> === Build =======================================
> Capabilities:  NEON VFPv3 VFPv4
> [INFO] Built: Jul 16 2020
> [INFO] Version: 1.8.9
> [INFO] Git: 324eb4f
> [INFO] =================================================
> jni_thread_destruct()
> [CORE]: Loading dynamic libretro core from: "/data/user/0/com.retroarch.ra32/cores/mame_libretro_android.so"
> [Overrides]: No core-specific overrides found at /storage/emulated/0/RetroArch/config/MAME/MAME.cfg.
> [Overrides]: No content-dir-specific overrides found at /storage/emulated/0/RetroArch/config/MAME/CAVE SH3.cfg.
> [Overrides]: No game-specific overrides found at /storage/emulated/0/RetroArch/config/MAME/espgal2.cfg.
> [Environ]: SET_VARIABLES.
> [Remaps]: remap directory: /storage/emulated/0/RetroArch/config/remaps
> [Overrides]: Redirecting save file to "/storage/emulated/0/RetroArch/saves/MAME/espgal2.srm".
> [Overrides]: Redirecting save state to "/storage/emulated/0/RetroArch/states/MAME/espgal2.state".
> [Environ]: GET_LOG_INTERFACE.
> [Environ]: SYSTEM_DIRECTORY: "/storage/emulated/0/RetroArch/system".
> SYSTEM_DIRECTORY: /storage/emulated/0/RetroArch/system
> [Environ]: CORE_ASSETS_DIRECTORY: "/storage/emulated/0/RetroArch/downloads".
> CONTENT_DIRECTORY: /storage/emulated/0/RetroArch/downloads
> [Environ]: GET_SAVE_DIRECTORY.
> SAVE_DIRECTORY: /storage/emulated/0/RetroArch/saves/MAME
> [Environ]: SET_PIXEL_FORMAT: XRGB8888.
> [CONTENT LOAD]: Content loading skipped. Implementation will load it on its own.
> Joystick map: disabled
> [Environ]: SET_INPUT_DESCRIPTORS:
> [SRAM]: Skipping SRAM load..
> Version of libretro API: 1
> [INFO] Compiled against API: 1
> Joystick map: disabled
> [Environ]: SET_INPUT_DESCRIPTORS:
> AV_INFO: width=640 height=480
> AV_INFO: max_width=640 max_height=480
> AV_INFO: aspect_ratio = 1.333333
> AV_INFO: fps = 60.000000 sample_rate = 48000.000000
> [Cheats]: Load game-specific cheatfile: /storage/emulated/0/RetroArch/cheats/MAME/espgal2.cht
> [Audio]: Set audio input rate to: 48000.00 Hz.
> [Video]: Video @ 1752x1440
> [Video]: Starting threaded video driver ...
> Android EGL: GLES version = 2.
> [EGL] Falling back to eglGetDisplay
> [EGL]: EGL version: 1.4
> [GL]: Found GL context: android
> [GL]: Detecting screen resolution 0x0.
> [EGL]: Current context: 0xe0bdd640.
> [GL]: Vendor: Qualcomm, Renderer: Adreno (TM) 512.
> [GL]: Version: OpenGL ES 3.2 V@269.0 (GIT@dcd4b96, I568c71768a) (Date:04/30/18).
> [GL]: Using resolution 1920x1200
> [GL]: Default shader backend found: glsl.
> [Shaders]: Specific shader preset found at /storage/emulated/0/RetroArch/config/global.glslp.
> [Shader driver]: Using GLSL shader backend.
> [Shaders]: Found #pragma parameter Composite Sharp (Tuning_Sharp) 0.200000 0.000000 1.000000 0.050000 in pass 0
> [Shaders]: Found #pragma parameter Red Persistence (Tuning_Persistence_R) 0.075000 0.000000 1.000000 0.010000 in pass 0
> [Shaders]: Found #pragma parameter Green Persistence (Tuning_Persistence_G) 0.050000 0.000000 1.000000 0.010000 in pass 0
> [Shaders]: Found #pragma parameter Blue Persistence (Tuning_Persistence_B) 0.050000 0.000000 1.000000 0.010000 in pass 0
> [Shaders]: Found #pragma parameter Composite Bleed (Tuning_Bleed) 0.500000 0.000000 1.000000 0.050000 in pass 0
> [Shaders]: Found #pragma parameter Composite Artifacts (Tuning_Artifacts) 0.500000 0.000000 1.000000 0.050000 in pass 0
> [Shaders]: Found #pragma parameter NTSC Artifacts (NTSCLerp) 1.000000 0.000000 1.000000 1.000000 in pass 0
> [Shaders]: Found #pragma parameter NTSC Artifact Scale (NTSCArtifactScale) 255.000000 0.000000 1000.000000 5.000000 in pass 0
> [Shaders]: Found #pragma parameter Animate NTSC Artifacts (animate_artifacts) 1.000000 0.000000 1.000000 1.000000 in pass 0
> [Shaders]: Found #pragma parameter TVOut Signal Resolution (TVOUT_RESOLUTION) 256.000000 0.000000 1024.000000 32.000000 in pass 1
> [Shaders]: Found #pragma parameter TVOut Composite Enable (TVOUT_COMPOSITE_CONNECTION) 0.000000 0.000000 1.000000 1.000000 in pass 1
> [Shaders]: Found #pragma parameter TVOut TV Color Levels Enable (TVOUT_TV_COLOR_LEVELS) 1.000000 0.000000 1.000000 1.000000 in pass 1
> [Shaders]: Found #pragma parameter TVOut Luma (Y) Resolution (TVOUT_RESOLUTION_Y) 256.000000 0.000000 1024.000000 32.000000 in pass 1
> [Shaders]: Found #pragma parameter TVOut Chroma (I) Resolution (TVOUT_RESOLUTION_I) 83.199997 0.000000 256.000000 8.000000 in pass 1
> [Shaders]: Found #pragma parameter TVOut Chroma (Q) Resolution (TVOUT_RESOLUTION_Q) 25.600000 0.000000 256.000000 8.000000 in pass 1
> [Shaders]: Found #pragma parameter warpX (warpX) 0.031000 0.000000 0.125000 0.010000 in pass 2
> [Shaders]: Found #pragma parameter warpY (warpY) 0.041000 0.000000 0.125000 0.010000 in pass 2
> [Shaders]: Found #pragma parameter shadowMask (shadowMask) 3.000000 0.000000 4.000000 1.000000 in pass 2
> [Shaders]: Found #pragma parameter maskDark (maskDark) 0.900000 0.000000 2.000000 0.100000 in pass 2
> [Shaders]: Found #pragma parameter maskLight (maskLight) 1.500000 0.000000 2.000000 0.100000 in pass 2
> [Shaders]: Found #pragma parameter CRT Gamma (crt_gamma) 2.200000 1.000000 4.000000 0.050000 in pass 2
> [Shaders]: Found #pragma parameter Monitor Gamma (monitor_gamma) 2.200000 1.000000 4.000000 0.050000 in pass 2
> [Shaders]: Found #pragma parameter Scanline Intensity (SCANLINE_SINE_COMP_B) 0.400000 0.000000 1.000000 0.050000 in pass 2
> [Shaders]: Found #pragma parameter Scanline Sine Comp A (SCANLINE_SINE_COMP_A) 0.000000 0.000000 0.100000 0.010000 in pass 2
> [Shaders]: Found #pragma parameter Scanline Base Brightness (SCANLINE_BASE_BRIGHTNESS) 0.950000 0.000000 1.000000 0.010000 in pass 2
> [GLSL]: Found GLSL vertex shader.
> [GLSL]: Found GLSL fragment shader.
> [GLSL]: Linking GLSL program.
> [GLSL]: Found GLSL vertex shader.
> [GLSL]: Using GLSL version 300 es.
> [GLSL]: Found GLSL fragment shader.
> [GLSL]: Using GLSL version 300 es.
> [GLSL]: Linking GLSL program.
> [GLSL]: Found GLSL vertex shader.
> [GLSL]: Found GLSL fragment shader.
> [GLSL]: Linking GLSL program.
> [GLSL]: Found GLSL vertex shader.
> [GLSL]: Found GLSL fragment shader.
> [GLSL]: Linking GLSL program.
> [GL]: Loaded texture image from: "/storage/emulated/0/RetroArch/shaders/artifacts.png" ...
> [GL]: Loaded texture image from: "/storage/emulated/0/RetroArch/shaders/mask.png" ...
> [GLSL]: Found GLSL vertex shader.
> [GLSL]: Found GLSL fragment shader.
> [GLSL]: Linking GLSL program.
> [GL]: Using 6 textures.
> [GL]: Loaded 3 program(s).
> [GL]: Creating FBO 0 @ 1024x1024
> [GL]: Creating FBO 1 @ 1024x1024
> [Joypad]: Found joypad driver: "android".
> [Font]: Using font rendering backend: stb-unicode.
> [Video]: Found display server: android
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/composite.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTCOMP_256.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTCOMP_480.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTCOMP_DOWNSAMPLE_240.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTPC.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTRGB1_256.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTRGB1_480.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTRGB1_DOWNSAMPLE_240.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTRGB2_256.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTRGB2_480.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTRGB2_DOWNSAMPLE_240.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTSTAT1_256.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTSTAT1_480.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTSTAT1_DOWNSAMPLE_240.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTSTAT2_256.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTSTAT2_480.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTSTAT2_DOWNSAMPLE_240.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTVHS_256.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/CRTVHS_480.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/deband.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/fakelottes_curve.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/fakelottes_dotmask.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/fakelottes_dotscan.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/fakelottes_dotscan_vert.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/fakelottes_scanlines.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/film_noise_simple.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/gb-palette.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/gba-color.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/gbc-color.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/grain_noise.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/lcd-grid-v2.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/LCD.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/lcd1x.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/lcd3x.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/LCD_GBA.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/LCD_GBC.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/LCD_NDS.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/LCD_PSP.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/LCD_VB.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/nds-color.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/ntsc-colors.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/psp-color.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/response-time.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/retroarch.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/scanline.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/scanlines-sine-abs.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/stock.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/STOCK_240.glslp"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/tvout-tweaks.glsl"
> [Shaders]: Found shader "/storage/emulated/0/RetroArch/shaders/vhs.glsl"
> [OpenSL]: Requested audio latency: 128 ms.[OpenSL]: Setting audio latency: Block size = 768, Blocks = 32, Total = 24576 ...
> [Display]: Found display driver: "gl".
> [Font]: Using font rendering backend: stb-unicode.
> [Font]: Using font rendering backend: stb-unicode.
> [Font]: Using font rendering backend: stb-unicode.
> [LED]: LED driver = 'null' 0xccba54d8
> [MIDI]: Input disabled.
> [MIDI]: Output disabled.
> [MIDI]: Initialized "null" driver.
> [Shaders]: Found #pragma parameter Composite Sharp (Tuning_Sharp) 0.200000 0.000000 1.000000 0.050000 in pass 0
> [Shaders]: Found #pragma parameter Red Persistence (Tuning_Persistence_R) 0.075000 0.000000 1.000000 0.010000 in pass 0
> [Shaders]: Found #pragma parameter Green Persistence (Tuning_Persistence_G) 0.050000 0.000000 1.000000 0.010000 in pass 0
> [Shaders]: Found #pragma parameter Blue Persistence (Tuning_Persistence_B) 0.050000 0.000000 1.000000 0.010000 in pass 0
> [Shaders]: Found #pragma parameter Composite Bleed (Tuning_Bleed) 0.500000 0.000000 1.000000 0.050000 in pass 0
> [Shaders]: Found #pragma parameter Composite Artifacts (Tuning_Artifacts) 0.500000 0.000000 1.000000 0.050000 in pass 0
> [Shaders]: Found #pragma parameter NTSC Artifacts (NTSCLerp) 1.000000 0.000000 1.000000 1.000000 in pass 0
> [Shaders]: Found #pragma parameter NTSC Artifact Scale (NTSCArtifactScale) 255.000000 0.000000 1000.000000 5.000000 in pass 0
> [Shaders]: Found #pragma parameter Animate NTSC Artifacts (animate_artifacts) 1.000000 0.000000 1.000000 1.000000 in pass 0
> [Shaders]: Found #pragma parameter TVOut Signal Resolution (TVOUT_RESOLUTION) 256.000000 0.000000 1024.000000 32.000000 in pass 1
> [Shaders]: Found #pragma parameter TVOut Composite Enable (TVOUT_COMPOSITE_CONNECTION) 0.000000 0.000000 1.000000 1.000000 in pass 1
> [Shaders]: Found #pragma parameter TVOut TV Color Levels Enable (TVOUT_TV_COLOR_LEVELS) 1.000000 0.000000 1.000000 1.000000 in pass 1
> [Shaders]: Found #pragma parameter TVOut Luma (Y) Resolution (TVOUT_RESOLUTION_Y) 256.000000 0.000000 1024.000000 32.000000 in pass 1
> [Shaders]: Found #pragma parameter TVOut Chroma (I) Resolution (TVOUT_RESOLUTION_I) 83.199997 0.000000 256.000000 8.000000 in pass 1
> [Shaders]: Found #pragma parameter TVOut Chroma (Q) Resolution (TVOUT_RESOLUTION_Q) 25.600000 0.000000 256.000000 8.000000 in pass 1
> [Shaders]: Found #pragma parameter warpX (warpX) 0.031000 0.000000 0.125000 0.010000 in pass 2
> [Shaders]: Found #pragma parameter warpY (warpY) 0.041000 0.000000 0.125000 0.010000 in pass 2
> [Shaders]: Found #pragma parameter shadowMask (shadowMask) 3.000000 0.000000 4.000000 1.000000 in pass 2
> [Shaders]: Found #pragma parameter maskDark (maskDark) 0.900000 0.000000 2.000000 0.100000 in pass 2
> [Shaders]: Found #pragma parameter maskLight (maskLight) 1.500000 0.000000 2.000000 0.100000 in pass 2
> [Shaders]: Found #pragma parameter CRT Gamma (crt_gamma) 2.200000 1.000000 4.000000 0.050000 in pass 2
> [Shaders]: Found #pragma parameter Monitor Gamma (monitor_gamma) 2.200000 1.000000 4.000000 0.050000 in pass 2
> [Shaders]: Found #pragma parameter Scanline Intensity (SCANLINE_SINE_COMP_B) 0.400000 0.000000 1.000000 0.050000 in pass 2
> [Shaders]: Found #pragma parameter Scanline Sine Comp A (SCANLINE_SINE_COMP_A) 0.000000 0.000000 0.100000 0.010000 in pass 2
> [Shaders]: Found #pragma parameter Scanline Base Brightness (SCANLINE_BASE_BRIGHTNESS) 0.950000 0.000000 1.000000 0.010000 in pass 2
> [Playlist]: Loading history file: [/data/user/0/com.retroarch.ra32/content_history.lpl].
> [Playlist]: Loading history file: [/data/user/0/com.retroarch.ra32/content_music_history.lpl].
> [Playlist]: Loading history file: [/data/user/0/com.retroarch.ra32/content_image_history.lpl].
> [Playlist]: Loading favorites file: [/data/user/0/com.retroarch.ra32/content_favorites.lpl].
> Starting game:/storage/emulated/0/RetroArch/_ROMS/CAVE SH3/espgal2.zip
> Game name: espgal2, Game description: Espgaluda II (2005/11/14 MASTER VER)
> System not found: CAVE SH3
> Driver CAVE SH3 not found -1
> Creating frontend for game: espgal2
> Softlists: 1
> SOURCE FILE: ../../../../../src/mame/drivers/cv1k.cpp
> PARENT: 0
> NAME: espgal2
> DESCRIPTION: Espgaluda II (2005/11/14 MASTER VER)
> YEAR: 2005
> MANUFACTURER: Cave (AMI license)

**Comment by tcamargo** [comment]
Coud you please try this build? **Only pacman driver is active.**

https://camargo.batocera.org/libretro-mame/android-arm/mame_libretro_android-symbols-libunwind-pacman_only.so

**Comment by Denshadego** [comment]
Tested it and indeed loads, only Pac-man, but loads.

**Comment by tcamargo** [comment]
Nice. I limited to pacman due to bundling all debug symbols. Otherwise, it would be a +2GB core. ;)
Wait a bit and I will provide a new build.

**Comment by tcamargo** [comment]
Please test: https://camargo.batocera.org/libretro-mame/android-arm/mame_libretro_android.so

All drivers enable.

**Comment by Denshadego** [comment]
Loads perfectly, thank you!
