### ISSUE TITLE
BGM vs SFX volume balance core option

### ISSUE THREAD

**Issue by eadmaster** [libretro/mame#179]
Is some games i've found BGM and SFX volumes are unbalanced: e.g. SFX plays too loud.

I'd like to suggest adding a core option to rebalance them.

If not doable at core level, maybe adding individual channels volume control could work as alternative?

**Comment by tcamargo** [comment]
Do your notice the same difference in standalone mame?

**Comment by tcamargo** [comment]
No reply.

**Comment by eadmaster** [comment]
yep, it is the same in vanilla mame, sometimes i can fix this by adjusting individual audio chips volumes, but not all games have them.

**Comment by tcamargo** [comment]
Not sure libretro API provides something to control channel volumes. Also, mame core is kind of a black box to retroarch. So, not an easy thing to do.
