### ISSUE TITLE
ADD pgm2 support in latest MAME?

### ISSUE THREAD

**Issue by eddiebrook** [libretro/mame#18]
Hello is posible add pgm2 drivers in latest mame?

Knight of valour 3 and others games pgm2 working 

https://www.youtube.com/watch?v=gFEhxoooIn4

**Comment by Enverex** [comment]
This core should match upstream (as of 11 days ago). Is there some specific issue you're having here?

**Comment by rb6502** [comment]
PGM2 is not supported in upstream.  There is a binary-only Chinese hack of MAME that runs those games poorly with a lot of bugs; this does not make MAMEdev happy.  Feel free to close this issue.

**Comment by inactive123** [comment]
OK, since the point of the upstream MAME core is to stay in lockstep with upstream, I agree that we can close this issue.
