### ISSUE TITLE
Button Profiles - Missing games on the list

### ISSUE THREAD

**Issue by Immersion95** [libretro/mame#187]
There are some missing games on the [button profiles list](https://github.com/libretro/mame/blob/master/src/osd/modules/input/input_retro.cpp)

Capcom CPS-1 and CPS-2 6-button fighting games : 

Parent roms -->
- sfz2al
- vhunt2
- redearth
- "starglad" should be removed from this list as it has a [4 buttons layout](http://gamesdbase.com/Media/SYSTEM/Arcade/commands/Commands_Star_Gladiator_-_1996_-_Capcom.htm) 

This list should be renamed "6-button fighting games" with those games added to that list : 

- astrass
- brival
- btlkroad
- dragoona
- fghthist
- fgtlayer
- groovef
- kaiserkn

**Comment by tcamargo** [comment]
Thx! Coud you send a PR for that?

**Comment by Immersion95** [comment]
You know what, I'm gonna try to do it for the first time !

**Comment by tcamargo** [comment]
Thx. Really appreciate that!

**Comment by Immersion95** [comment]
I think I did correctly. I'll wait and see if it worked and then I'll close it :).

**Comment by Immersion95** [comment]
The pull request failed, would you mind helping there ?

make[2]: Leaving directory '/home/runner/work/mame/mame/build/projects/retro/mametiny/gmake-linux'
makefile:1374: recipe for target 'linux_x64' failed
make[1]: *** [linux_x64] Error 2
make[1]: Leaving directory '/home/runner/work/mame/mame'
Makefile.libretro:180: recipe for target 'build' failed
make: *** [build] Error 2
##[error]Process completed with exit code 2.

**Comment by tcamargo** [comment]
Look for "error" in raw logs.

`2020-08-07T08:55:59.2726941Z ../../../../../src/osd/modules/input/input_retro.cpp: In function ‘void Input_Binding(running_machine&)’:
2020-08-07T08:55:59.2728257Z ../../../../../src/osd/modules/input/input_retro.cpp:346:15: error: expected ‘)’ before ‘!’ token
2020-08-07T08:55:59.2728922Z                !core_stricmp(machine.system().name, "astrass") ||
2020-08-07T08:55:59.2729346Z                ^`

**Comment by Immersion95** [comment]
Thanks :)
