### ISSUE TITLE
[windows]Mame compile issues:

### ISSUE THREAD

**Issue by ghost** [libretro/mame#19]
mame build in buildbot is late. last build is dated 1-24-2017 and is still on 181. i did a local repo and compiled it but its not compiling:

https://hastebin.com/ewatutiqet.go

**Comment by Alcaro** [comment]
>   template<class _DeviceClass> bool interface(_DeviceClass *&intf) { intf = dynamic_cast<_DeviceClass *>(this); return (intf != nullptr); }

On Windows, 'interface' is a #define to struct.

Easiest fix would be adding a #undef.

**Comment by r-type** [comment]
the change that can break is 
https://github.com/libretro/mame/commit/b47ec24df6e2fd64ff4757dc5661fb9249dce617

they remove #define WIN32_LEAN_AND_MEAN and put it in lua script.
So could you try to add  this 
```
 "WIN32_LEAN_AND_MEAN",
```
after in line 55 in
https://github.com/libretro/mame/blob/master/scripts/src/osd/retro_cfg.lua
to have something like

```
if _OPTIONS["targetos"]=="windows" then
	configuration { "mingw* or vs*" }
		defines {
			"UNICODE",
			"_UNICODE",
			"main=utf8_main",
			"_WIN32_WINNT=0x0501",
                         "WIN32_LEAN_AND_MEAN",
		}
```
and see what going on ...

**Comment by ghost** [comment]
that was fast... as soon as i compiled my local repo with the "WIN32_LEAN_AND_MEAN", buildbot also got updated.

tested and working here. thanks

feel free to reopen if there's stuff to add.
