### ISSUE TITLE
About the core MAME update

### ISSUE THREAD

**Issue by alexb3d** [libretro/mame#192]
This is not an error, it is more a query. Do you plan to make the kernel in each version of MAME?

It is to know if I can update my romset or keep it at 0.222. Is that MAME comes out monthly and sometimes the kernel is updated immediately and other times it takes up to two versions.

An idea that I [proposed](https://forums.libretro.com/t/about-the-core-mame-update/29666) is to release the core every 3 or 4 versions (months). It could be less work for you and more happiness for users, I don't know.

**Comment by Immersion95** [comment]
There is a current pull request for 0.223 so it should be soon.

What I do is keep the romset of the current core and monitor when it's updated. The roms shouldn't change a lot for each revision.

**Comment by tcamargo** [comment]
We update core as soon as possible. 0.223 will hit repository as soon as we fix some issues in our build system.

**Comment by alexb3d** [comment]
Mame releases a new version monthly, usually at the end of the month. Updating MAME is a headache, and monthly it is a tragedy.

There are many changes of names and locations, it is the same rom without changes but it affects the emulation. One of the changes in 0.223 was, change location "sf2049" before they were together now separate, and so on.

I wait for the new version, I already update part of the romset, but consider making a stay in RetroArch every 3 or 4 versions, eg, April, August and December.

I know there is an option to freeze the core, but this may be better for you and us, less work.

Anyway, they didn't answer my question.

Do you plan to update MAME monthly in each version?

**Comment by tcamargo** [comment]
Yes, we do.

**Comment by alexb3d** [comment]
we already have 0.223  Thask! 

(the 0.224 came out a week ago)

**Comment by tcamargo** [comment]
> we already have 0.223 Thask!
> 
> (the 0.224 came out a week ago)

I update according to my free time. 0.224 is already available.

**Comment by alexb3d** [comment]
2.90 standard version
2.83.5 LTS version

**Comment by alexb3d** [comment]
I get it. Thank you.

We need a long-term version in RetroArch, like LTS so that it doesn't consume too much time and updating that set, it's a nightmare.

**Comment by tcamargo** [comment]
> I get it. Thank you.
> 
> We need a long-term version in RetroArch, like LTS so that it doesn't consume too much time and updating that set, it's a nightmare.

That's why we have mame 2013, 2016 and others. This core will always follow mainline.

**Comment by alexb3d** [comment]
0.225 is out and the core is still at 0.223. Now you understand when I recommend you get a core every 3 or 4 months.

**Comment by Immersion95** [comment]
The core is already updated, it's just that the updater is still broken from the previous hack. You can manually download the latest build there https://github.com/libretro/mame/releases

**Comment by alexb3d** [comment]
That was very fast.
Thank you!
