### ISSUE TITLE
The default layout is wrong when "Buttons Profile" is off

### ISSUE THREAD

**Issue by Immersion95** [libretro/mame#194]
The default layout (without profiling) is wrong.

Retropad is :

------X
Y----------A
------B

The default layout from the current Mame core is (without profiling) :

------3
4----------1
------2

It should be :

------4
3----------2
------1

I tried to find it myself but couldn't :p

What could it bring ? Using a more modern layout for Neogeo games : 

- Profile Off : Neo Geo CD Pad layout
- Profile On : DC/PSX layout for a specific list (which already exists furthermore)

**Comment by tcamargo** [comment]
@Immersion95 Could you please resubmit your PRs? Due to the libretro GH hack they got messed up.

**Comment by tcamargo** [comment]
Did https://github.com/libretro/mame/pull/199 solve this?

**Comment by Immersion95** [comment]
Unfortunately no, "input_retro.cpp" only handles the profile to my knowledge. The problem here is the wrong control layout when the profile is off.

**Comment by tcamargo** [comment]
Ok, could you please put a step by step how to reproduce? I dont know what you mean by profiling .

**Comment by Immersion95** [comment]
No problem !

In the MAME core, there is the option "Profile Buttons according to games" which use a custom profile per game.

When this option is off, it acts the same as standalone (what I use), you can change the controls with the MAME UI for an easier mapping layout.

The problem is that the control layout when the profile is off is wrong : 

Retropad is :

------X
Y----------A
------B

The default layout from the current Mame core is (without profiling) :

------3
4----------1
------2

It should be :

------4
3----------2
------1

**Comment by Immersion95** [comment]
Hi, thanks !

I'm gonna report this evening if it solves the issue :)

**Comment by Immersion95** [comment]
The problem isn't solved

**Comment by Immersion95** [comment]
Now solved thanks to @sonninnos :)

This allows RA MAME to use the same ctrlr file as standalone which is wonderful :)
