### ISSUE TITLE
SQLite issue with -ffast-math

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/mame#21]
I wonder if mame needs -ffast-math, but SQLite don't

```
3rdparty/sqlite3/sqlite3.c: In function 'sqlite3IsNaN':
3rdparty/sqlite3/sqlite3.c:22883:3: error: #error SQLite will not work correctly with the -ffast-math option of GCC.
 # error SQLite will not work correctly with the -ffast-math option of GCC.
   ^
```

https://launchpadlibrarian.net/198838678/buildlog_ubuntu-trusty-amd64.libretro-mame_0.02015.git%2Br31873~23~ubuntu14.04.1_BUILDING.txt.gz

**Comment by twinaphex** [comment]
Check if this solves it -

https://github.com/libretro/mame/commit/fbbe15a0d8bc36e7fd12ee23aa8b36f6aefdb9cb

**Comment by r-type** [comment]
Why not just remove CCOMFLAGS in sqlite3 rules in lib.mak .
It s what I have done so far and it works fine.

**Comment by sergiobenrocha2** [comment]
It's working now, but no problem to purge this -ffast-math?
