### ISSUE TITLE
Aarch64 is too slow!

### ISSUE THREAD

**Issue by falkor2k15** [libretro/mame#211]
Aarch64 @ 2.35 GHz is slower than x64 @ 1.44 GHz - can anyone explain why? 

Even though the devs are kind enough to provide the aarch64 build, is there a lack of optimizations for this architecture that might explain the lack of performance/speed?

**Comment by tcamargo** [comment]
JIT for arm/aarch64 is not in. It will probably be enabled with next version of mame.
