### ISSUE TITLE
No way to insert coin on 32-bit Android for airco22b and tokyowar 

### ISSUE THREAD

**Issue by CaptainKoloth554** [libretro/mame#213]
On Android on the 32-bit MAME core (just the plain “MAME” core, not 2003, 2010, etc.) there is no way to insert coin for certain games. Test games are Air Combat 22 and Tokyo Wars. I have tried using the touch overlays, a PS4 controller, an Xbox One controller, and even plugging in a full-size USB keyboard to my phone via a hub and breaking out to the Tab menu within MAME and remapping the Coin key. The core simply flat-out will not register a coin insertion for these games.

**Comment by tcamargo** [comment]
Could someone test this? I have no android device at hand.

Meanwhile, a fresh build of mame is out for armv7. Could you please test it?

**Comment by CaptainKoloth554** [comment]
I just tested with the latest build, same issue for me at least.

**Comment by sanchezmike01** [comment]
Just tested on my galaxy s9 phone 32bit core....select works as coin button

**Comment by CaptainKoloth554** [comment]
Select on what controller? Where in the core is it mapped?

**Comment by CaptainKoloth554** [comment]
Select on what controller? Where in the core is it mapped?

**Comment by sanchezmike01** [comment]
Usually I use the nvidia shield but right now at work so I can only test on the phone...the select button is always coin button by default unless you changed it and maybe the config file is somewhere in your files

**Comment by sanchezmike01** [comment]
Just downloaded the core and sf2.zip...loaded it up and hit select (phone on screen overlay) and immediately got coin credits to start the game

**Comment by sanchezmike01** [comment]
Maybe go to mame ctrlr folder and delete the config there for that game and try again...and check also the RetroArch config folders and remap folders in case u changed anything

**Comment by CaptainKoloth554** [comment]
It's definitely not working in my configuration, and I did several complete uninstall/reinstalls. Anybody have it on Android 10, Galaxy Note 10+, and/or these specific games?

**Comment by CaptainKoloth554** [comment]
OK, more info: sf2 does work for me, but airco22b and tokyowar do not. So it would seem to be an issue with some, but not all games. I will update the description.

**Comment by nemo93** [comment]
@CaptainKoloth554 I've raised another issue with more details #424. How we close that one off to keep things tidy? Feel free to add more games/details in the other ticket. Thanks!

**Comment by nemo93** [comment]
@CaptainKoloth554 a fix has been found. Please check #424 for details. I'm afraid I don't have an updated binary for your device at this time.
