### ISSUE TITLE
Any hope to MAME on Android 64bit Support JIT Dynarec?

### ISSUE THREAD

**Issue by vus7294** [libretro/mame#214]
It seems MAME only uses Software interpreter, so Many Games includes CV1000 have Painfully Slow Gameplay.
I saw Previous Issue that Too slow and That answer is JIT for MAME is On Work.
So I Hope to MAME with Dynarec, for More Good Game.(But Needs MAME Standalone Supports JIT Dynarec...) Thanks.

**Comment by tcamargo** [comment]
Need to wait for upstream devs to add it.

**Comment by vus7294** [comment]
i think... There's No Hope Before MAME Team Supports JIT Dynarec. Thanks Always.
