### ISSUE TITLE
[Windows x64] Core crashes and doesn't load any game

### ISSUE THREAD

**Issue by Immersion95** [libretro/mame#228]
The latest build doesn't work at all. Tried with latest RA nightlies and everything to default

**Comment by sanchezmike01** [comment]
Are the latest cores from a specific site or downloaded from the online updater?

**Comment by Immersion95** [comment]
> Are the latest cores from a specific site or downloaded from the online updater?

Online updater

**Comment by tcamargo** [comment]
Dupe of https://github.com/libretro/mame/issues/229.
