### ISSUE TITLE
Error compiling lr-mame v229

### ISSUE THREAD

**Issue by jlopezvil** [libretro/mame#233]
Get this error compiling today mame with last pull of version 229 on a pi4b

Attacched compiling log ....

[rps_2021-02-24_163019.log.gz](https://github.com/libretro/mame/files/6038517/rps_2021-02-24_163019.log.gz)

**Comment by tcamargo** [comment]
Those errors are not from libretro. Could you please try a newer gcc?

**Comment by jlopezvil** [comment]
must be updated on retropie? I compile it on retropie directly ....

**Comment by tcamargo** [comment]
I took a careful look in the logs you provided.

```
{entrada estándar}: Mensajes del ensamblador:
{entrada estándar}:1354662: Error: operandos inválidos (secciones *UND* y .ARM.extab.text._ZN22address_space_specificILi1ELi1ELi0EL12endianness_t1EE21install_write_handlerEjjjjjN3emu15device_delegateIFvR13address_spacehEEEyi) para «-»
{entrada estándar}:1354665: Error: operandos inválidos (secciones *UND* y .ARM.extab.text._ZN22address_space_specificILi1ELi1ELi0EL12endianness_t1EE21install_write_handlerEjjjjjN3emu15device_delegateIFvR13address_spacehEEEyi) para «-»
g++: fatal error: Terminado (killed) signal terminated program cc1plus
compilation terminated.
```

It basically means you ran out of memory. mame needs a lot of memory to compile, so I would advise to not try to compile it on a rpi4.

**Comment by MarcoBorrini99** [comment]
> I took a careful look in the logs you provided.
> 
> ```
> {entrada estándar}: Mensajes del ensamblador:
> {entrada estándar}:1354662: Error: operandos inválidos (secciones *UND* y .ARM.extab.text._ZN22address_space_specificILi1ELi1ELi0EL12endianness_t1EE21install_write_handlerEjjjjjN3emu15device_delegateIFvR13address_spacehEEEyi) para «-»
> {entrada estándar}:1354665: Error: operandos inválidos (secciones *UND* y .ARM.extab.text._ZN22address_space_specificILi1ELi1ELi0EL12endianness_t1EE21install_write_handlerEjjjjjN3emu15device_delegateIFvR13address_spacehEEEyi) para «-»
> g++: fatal error: Terminado (killed) signal terminated program cc1plus
> compilation terminated.
> ```
> 
> It basically means you ran out of memory. mame needs a lot of memory to compile, so I would advise to not try to compile it on a rpi4.

I've avoided out of memory errors on my pi400  by temporarily setting a swap file on an external SSD drive... better than nothing :-)
