### ISSUE TITLE
Vertical games with zfast-crt shader

### ISSUE THREAD

**Issue by rafaelmartines** [libretro/mame#234]
On current MAME 0.229 Core, the vertical games using zfast-crt shaders do not autocorrect the shader to show vertical scanlines like MAME 2003+ and FBNeo do.

Screenshots:
MAME 2003+
![Captura de tela de 2021-02-24 19-48-04](https://user-images.githubusercontent.com/8183691/109077071-5b33c680-76da-11eb-82ff-a395c55422d4.png)
![Captura de tela de 2021-02-24 19-48-36](https://user-images.githubusercontent.com/8183691/109077074-5c64f380-76da-11eb-9249-29fde4b38db2.png)
![Captura de tela de 2021-02-24 19-48-52](https://user-images.githubusercontent.com/8183691/109077076-5cfd8a00-76da-11eb-965d-257d18239c5a.png)

MAME 0.229
![Captura de tela de 2021-02-24 19-50-27](https://user-images.githubusercontent.com/8183691/109077131-74d50e00-76da-11eb-88f4-4bb523d06408.png)
![Captura de tela de 2021-02-24 19-52-11](https://user-images.githubusercontent.com/8183691/109077133-756da480-76da-11eb-8280-a65b94d1ddc8.png)
![Captura de tela de 2021-02-24 19-53-48](https://user-images.githubusercontent.com/8183691/109077136-76063b00-76da-11eb-8300-1d86b884fa54.png)

**Comment by barbudreadmon** [comment]
Directly related to https://github.com/libretro/mame/issues/261
