### ISSUE TITLE
games from namcona1.cpp and namconb1.cpp won't boot

### ISSUE THREAD

**Issue by Panderner** [libretro/mame#237]
I tried to run any namcona1/namconb1 games but it won't boot

namcona1: won't boot (stucks at black screen)
namconb2: stucks at startup screen
![ptblank-210313-111544](https://user-images.githubusercontent.com/37503397/111017309-9548dc00-83ed-11eb-8621-20ed1f54479c.png)
![machbrkr-210313-111610](https://user-images.githubusercontent.com/37503397/111017311-967a0900-83ed-11eb-97f4-d174cceb5c62.png)

**Comment by Panderner** [comment]
Note: Standalone and Libretro version of MAME works fine for PC. This issue only occurs for Android devices

**Comment by nemo93** [comment]
Hi. I do confirm such games won't pass the self-test screen on Raspberry Pi4 as well. Tested with [The Outfoxies](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=outfxies) from a proper .230 romset. This game specifically runs fine with the FBNeo core - which relies on same rom.

Raspberry Pi4 runs on a Retropie last version (4.7.12). Kernel 5.10.17-v7l+, 32-bit Raspberry OS and `fKMS` mode. Retroarch is 1.8.8 but the MAME core is up-to-date:

```
URL: https://github.com/libretro/mame.git
Branch: master
Commit: 98b0ba18a9109339c2ebf4f5945f6c3575301ba9
Date: 2021-04-12T17:53:19+02:00
```

**Note**: another game from a different driver (kaneko16.cpp) does suffer of a similar issue. It's [B.Rap Boys](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=brapboysp) (including Special clones). Game does run but it will be stuck in an endless loop on the self-test screen.

**Comment by Panderner** [comment]
Thank you @nemo93 for testing it on Raspberry Pi 4

**Comment by nemo93** [comment]
I've created new ticket given another driver also has similar issue. I'd recommend to close this ticket to keep things tidy.
