### ISSUE TITLE
Link fails on jetson-TK1 (armhf)

### ISSUE THREAD

**Issue by nkyriazis** [libretro/mame#238]
It seems I'm running into this error https://github.com/mamedev/mame/issues/3639 while trying to build the latest on a [Tegra Jetson TK1](https://elinux.org/Jetson_TK1). I have been able to build previous versions (not sure which one). GCC 9.

I can build with `SUBTARGET=arcade` without getting the link error, so, it must be the number of symbols itself.

**Comment by tcamargo** [comment]
The same happens on android. You need to build arcade and mess (softlist) targets separately. Sorry, can't do much.
