### ISSUE TITLE
Nvram issues Time Crisis Android

### ISSUE THREAD

**Issue by thatman84** [libretro/mame#24]
Hi,

Getting error when trying to load Time Crisis (timecris) 
"SUBCPU START WAIT = NG"

Game doesnt boot.

From research I believe this is related to Nvram but is unclear. Nvram folder/file is created.

Worked first time on windows setup with same rom & folder

**Comment by Enverex** [comment]
Is this specific to the libretro version of MAME, or does it also happen on the official MAME release? If it's the latter then I'd recommend reporting it upstream, as MAME specific issues with games wouldn't be fixed in this fork specifically (although that may be hard to test given that it's Android).

**Comment by thatman84** [comment]
i would have to test again but from memory it works on Windows retroarch. As I said in the op. That probably would have been my first test

**Comment by r-type** [comment]
look like this old bug 
http://mametesters.org/view.php?id=1992
does the F2/F3/F2 trick work ?
on android , you maybe have to define RA system directory somewhere the app can write in your sdcard.

**Comment by thatman84** [comment]
I remember reading this topic when testing but didn't have any joy. I will test it again in the next few days and report back. I think I struggled to get the right keys setup as F2 & F3 are not listed as the original assignment. But I will have to check again

**Comment by tcamargo** [comment]
Could you please confirm this problem on a newer build? If it is confirmed, I will reopen this issue. Thx.
