### ISSUE TITLE
MAME core hangs when files/roms missing in set.

### ISSUE THREAD

**Issue by jason-oliveira** [libretro/mame#244]
If you have an incomplete romset (for instance, you have an old 0.183 romset you're trying to use on mainline), when MAME freaks out about the files that are missing, the core dies, and Retroarch hangs and will only die with a kill -9.

MAME core confirmed working with updated romset, but this behavior should be more elegantly handled for what is definitely a common issue.

**Comment by tcamargo** [comment]
Dupe https://github.com/libretro/mame/issues/158.
