### ISSUE TITLE
ARM 32bit GLES - all games fail to load with "undefined symbol: driver_3kokushi"

### ISSUE THREAD

**Issue by mrfixit2001** [libretro/mame#248]
Maybe I'm missing a compiler flag or something? I've tried a dozen games and they all fail with the below:

[INFO] === Build =======================================
[INFO] Capabilities:  NEON VFPv3 VFPv4
[INFO] Built: Jun 12 2021
[INFO] Version: 1.9.0
[INFO] =================================================
[INFO] [Input]: Found input driver: "sdl2".
[INFO] [Core]: Loading dynamic libretro core from: "/usr/lib/libretro/mame_libretro.so"
[ERROR] Failed to open libretro core: "/usr/lib/libretro/mame_libretro.so"
Error(s): /usr/lib/libretro/mame_libretro.so: undefined symbol: driver_3kokushi
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading core symbols..

**Comment by mrfixit2001** [comment]
In additional testing I also sometimes see "undefined symbol: driver_bigdeal"

**Comment by tcamargo** [comment]
It works fine here.

**Comment by tcamargo** [comment]
Try to build with SUBTARGET=arcade.
