### ISSUE TITLE
recipe for target 'build/projects/retro/mame/gmake-android-arm64/Makefile' failed

### ISSUE THREAD

**Issue by 963431755** [libretro/mame#251]
makefile:1354: recipe for target 'build/projects/retro/mame/gmake-android-arm64/Makefile' failed
make[1]: *** [build/projects/retro/mame/gmake-android-arm64/Makefile] Error 255

Hi guys,How fix this issunes? It shows after execute "make -j4 -f Makefile.libretro platform=android-arm64",everyone help me please.

**Comment by tcamargo** [comment]
Make sure you set ANDROID_NDK_LLVM, ANDROID_NDK_ARM, and ANDROID_NDK_ROOT if NDK is not in /opt/ndk.
