### ISSUE TITLE
Sega virtua racing android.

### ISSUE THREAD

**Issue by 71knight** [libretro/mame#253]
Game graphics are mostly broken.  The track cannot be seen and cars randomly spin in circles!  Mame current core ver .232 on retroarch.

**Comment by tcamargo** [comment]
What does it work on standalone mame?

**Comment by 71knight** [comment]
> What does it work on standalone mame?

The only mame stand alone for Android is mame4droid based on mame .139.  I just tried it and it's messed up just like mame .232 core for retroarch Android.  Tried both the software renderer and the opengl renderer.  I'm using opengl on Android 10.  Guess nobody has addressed the mame driver for this model one game on Android.  From what I've seen it looks like the game would run full speed on my Snapdragon 855+ if graphics were fixed!

**Comment by tcamargo** [comment]
By standalone, i meant mame on windows or linux.

**Comment by nemo93** [comment]
Duplicate of  #347 I recommend closing this one.
