### ISSUE TITLE
Building with microsoft tools

### ISSUE THREAD

**Issue by vadosnaprimer** [libretro/mame#26]
Upstream mame can be compiled with msbuild from command line (`MSBUILD=1`) or from visual studio 2015 (`vs2015`). Neither of these seems to work for libretro mame. twinaphex said @bparker06 managed to make the buildbot use visual studio. Is there any info on that?

If no one did that for mame, can someone give me hints on how to change the makefiles to make it work?

The first error that appears is that it's missing `unistd.h` in `osdlib_retro.cpp`. The msbuild way hasn't even been considered since it's a unix header, and no way to skip it has been given in the code.

**Comment by andres-asm** [comment]
We have a few targets (prboom and retroarch) that can use visual studio  but we don't really have target for MAME.

ie: the buildbot can build with visual studio but mame builds only with mingw so far.

**Comment by vadosnaprimer** [comment]
But someone still added libretro and libretrodbg to visual studio targets (via GENie commands). I wonder if that ever worked.

**Comment by andres-asm** [comment]
ahh no idea, maybe @r-type knows

**Comment by vadosnaprimer** [comment]
Hmmm, viewing the [libretro patches](https://github.com/r-type/mame/commits/master?author=r-type), it looks like libretro targets going to the vs solution was just an artifact, not an intention.

Yet any help with fixing the build errors would be greatly appreciated.
