### ISSUE TITLE
missing libretro auto-rotation implementation

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/mame#261]
This core doesn't implement libretro's auto-rotation, instead it internally rotates the framebuffer of vertical games and present it to the libretro api saying "this game is horizontal". It's causing improper behavior with shaders and maybe some other libretro features.

This is how a shader like zfast-crt currently looks on this core : 
![1942-210905-094822](https://user-images.githubusercontent.com/10391265/132119602-1b927ef8-5ab9-442c-81bd-88b48db318e3.png)

This is how it should look, because a vertical game is a game with a physically rotated screen, meaning the scanlines must be rotated too : 
![1942-210905-095321](https://user-images.githubusercontent.com/10391265/132119680-305f1f92-b84c-4357-9b90-76f5059ad5f4.png)

Note that, afaik, mame and mame2016 are the 2 only cores handling arcade vertical games behaving wrongly

**Comment by riggles1** [comment]
Use a mame.ini, there's a #core render options setting in there. In the MAME core options you have to specify that MAME should read from the mame.ini.

To cofirm that it's reading the mame.ini you can adjust the pause brightness for example and see if it reads your change.

Personally had to set rotation settings in there for it to work for me, I use an Astro City and manually rotate the CRT in that, with CRTEmudriver and RA's MAME Core (CRTSwitchres), games are never auto rotated anymore after making those changes.

**Comment by ghost** [comment]
While this can be fixed, it seems its a frontend issue as we have no control over the shaders rotation.  Rotating the image and letting ra do the rotation for the shaders is the only hackish workaround it.

**Comment by barbudreadmon** [comment]
>it seems its a frontend issue as we have no control over the shaders rotation

It's not a frontend issue, it's a core issue, you have control over shaders rotation by sending the screen orientation, this core is just doing something else instead of properly implementing this, all other arcade cores except mame2016 are doing it properly

**Comment by ghost** [comment]
Well that just means they all let RA handle it as  a workaround. Shaders rotation  shouldn't be a concern of the core if it has no control over them. A workaround is like you said before doesnt mean its not a front end issue.

**Comment by barbudreadmon** [comment]
This is not a workaround, this is the proper way to do this, you send the unrotated display alongside the expected rotation, so that the frontend and user settings can decide if the rotation must be applied or not, and in which direction the shaders must be applied if there are shaders, **this is how the libretro api works with vertical games, this is the only way of doing it, CORES MUST NOT ROTATE THE DISPLAY INTERNALLY, THEY MUST LET THE USER DECIDE THE ROTATION HE WANTS THROUGH THE FRONTEND SETTINGS**.

Seriously, there is an api call, and there is a dozen of core using this api call to do it the proper way, and yet instead of accepting that mame and mame2016 core are simply not implementing this, **because they literally don't and are the only ones that aren't**, you prefer saying it's everything else's fault. Whether this is intentional or not, stop trolling.

**Comment by ghost** [comment]
Well this would  cause issues in the mame front end when setting the rotate there as well. It could be a option for both. I guess cause we cant fully implement the rotations in RA unless they add FLIP_X and FLIP_Y that the only thing stopping it atm. This core really needs a hardware render as well as per discussed on reddit for artwork and especially svg.  It would probably have to be a vulkan one after that discussion we had about gl. 

I think a maintainer is  indeed is needed like you said before. I thought this project was upstream so needs treated with consideration to these things. I hope someone does find a compromise to work for both mame ui rotations and RA at the same time. Right now we would need to rol or rol with mame to handle any flips that arent supported, then rotate with libretro for the shader scanlines in vertical games.

**Comment by LibretroAdmin** [comment]
@JasmiJiveBunny Please do not argue with @barbudreadmon here. He has a point here and you are getting dangerously close to spreading disinformation.

**Comment by ghost** [comment]
Well nothing to do here then no point in any drama lifes too short. Im not really interested in getting involved in the culture of picking sides over practicality of getting something done a sensible way.  Maybe someone else will hold the same views on this as yourselves for the project and get it moving.  I will put the fixes for the gnw at the weekend if you still want them with no major changes to current code and be done with this subject. There is no miss information in this subject if there is any please do point it out and ill retract as necessary.

**Comment by ghost** [comment]
After reading the recent post of reddit I will say im done with any involvement with this project. That is a terrible way you treated a former contributor that has supported your project over a year with the same misinformation speech. peace out

**Comment by barbudreadmon** [comment]
>Right now we would need to rol or rol with mame to handle any flips that arent supported, then rotate with libretro for the shader scanlines in vertical games.

**NO**, mame renders this unrotated and applies a software rotation internally according to what the game asks, example : 
https://github.com/libretro/mame/blob/0d935696dce53a13eaf0705f4a108ee348f3c613/src/mame/pacman/pacman.cpp#L8219

`ROT90` is for rotating 90°. 

What needs to be done here is to disable the software rotation and replace it by a `RETRO_ENVIRONMENT_SET_ROTATION` api call, as it was done in all other mame cores.

You kept arguing about everything while being clueless about mame, libretro, and dramas... i can't say i'll miss you.

**Comment by LibretroAdmin** [comment]
As @barbudreadmon said, what needs to be done here is simple and to the point. Less distractions, less noise, let's focus on the main issue.
