### ISSUE TITLE
Do not load games without a license. 

### ISSUE THREAD

**Issue by alexb3d** [libretro/mame#266]
Does not load the type games; 101 Games IN 1, 35 in 1 Super Twins, Retro Dance Mat, and others games without a license. 

Core 0.235 / Linux Ubuntu LTS.

**Comment by MarcoBorrini99** [comment]
> Does not load the type games; 101 Games IN 1, 35 in 1 Super Twins, Retro Dance Mat, and others games without a license.
> 
> Core 0.235 / Linux Ubuntu LTS.

Which license?

**Comment by alexb3d** [comment]
Publication license. Original developer.
101 Games IN 1, 35 in... etc. are pirate games.

**Comment by sonninnos** [comment]
So what is the issue here? Should they load or not, and what should be done about "licenses" and how?

**Comment by alexb3d** [comment]
If they are in the official romset and MAME Standalone can run them, I think it is best that RetroArch Core also runs them.

These pirated games are hack, clones, compiled or even, original games using unlicensed hardware. But they have a real physical machine, that's why they dumpe them. Something similar to No-Intro, now it's putting pirated games in, because they had a real edition.

**Comment by sonninnos** [comment]
The core is using the regular MAME list, so what should be done?

**Comment by alexb3d** [comment]
Don't do anything please, I had a confusion.

These games are not "arcade machines" they are "Handheld / Plug n' Play TV Game / Multi-Games".   

What I don't understand, is why they run on the Standalone and on the Core they don't work.

**Comment by alexb3d** [comment]
Last minute edition...
I am testing the "Handheld" games, both the pirated ones I mentioned and the original "Game & Watch" games, and they all work perfectly.

Sorry for the inconvenience.
