### ISSUE TITLE
[Android] can't load core

### ISSUE THREAD

**Issue by clondy999** [libretro/mame#269]
I tried to use retroarch to run MAME to play kov3, but I failed to load the MAME core all the time. My version is retroarch 1.90 / retroarch 1.9.10. The core of MAME is downloaded online. The version I use is 32-bit

My android version is 4.4 / 6.0. I have tried and failed to load

![8502ae27f3c5ee664e838a5d2fba227](https://user-images.githubusercontent.com/73311186/135076274-84fe584b-fe42-4a17-8cd5-94735ebe134a.jpg)

**Comment by sonninnos** [comment]
Is this still the case?
