### ISSUE TITLE
Overlapping core and frontend options

### ISSUE THREAD

**Issue by sm-Fifteen** [libretro/mame#27]
With the way the core is currently setup, there are times where one needs to access the MAME menu to remap the correspondence between a machine's input settings, some default retroarch bindings (such as P for pause and ESC for quit) overlap with MAME ones and in ESC's case, provided the front end isn't setup to quit immediately, the core drops you in what appears to be MAME's ROM selection menu.

Shouldn't options like these be disabled in the core, and the associated features left for the frontend to handle for the sake of consistency?

**Comment by Tatsuya79** [comment]
You've got 2 ways to get around that problem:

-configure an "enable hotkey" button that will disable all retroarch hotkeys while not pressed down
(settings->input->input hotkey binds)

-make a MAME core override with the binding that causes problem disabled or reassigned

**Comment by tcamargo** [comment]
Workaround available. See https://github.com/libretro/mame/issues/27#issuecomment-303979217
