### ISSUE TITLE
X-Arcade Dual Joystick : Some button doesn't work

### ISSUE THREAD

**Issue by mac1202** [libretro/mame#27]
I got a X-Arcade Dual Joystick that act like a keyboard but some button aren't detected by libretro mame.
For example the p2 third button who is reported like this by xev is not detected : 
KeyRelease event, serial 48, synthetic NO, window 0x2600001,
    root 0xac, subw 0x0, time 169317313, (1167,221), root:(1168,241),
    state 0x0, keycode 34 (keysym 0xfe52, dead_circumflex), same_screen YES,
    XLookupString gives 1 bytes: (5e) "^"
    XFilterEvent returns: False
In sdlmame is working fine by enabling keymap file in config file : 
keymap                    1
keymap_file               /usr/share/sdlmame/keymaps/km-fr.txt
But in libretro mame it doesnt work even when i put this line in System/mame/ini/mame.ini and enabling read config in core option.

**Comment by r-type** [comment]
Keymap file like in sdl OSD are not supported in libreto mame core. More generally SDL mame options are not supported by LIBRETRO  mame core .

**Comment by mac1202** [comment]
So there is no workaround for the moment ?

**Comment by twinaphex** [comment]
There shouldnt be a workaround. We have nothing to do with SDL.

**Comment by mac1202** [comment]
i was talking about a workaround to make the X-Arcade Dual Joystick work with libretro mame.
