### ISSUE TITLE
console and handheld games doesn't load on last mame version

### ISSUE THREAD

**Issue by apison** [libretro/mame#271]
I've used to play old handheld games like tomy caveman with mame on android, but with the latest release of mame it seems that the drivers of handheld and console games has been removed, above the log tha obtain with the latest version trying to load tcaveman :

Starting game from command line:/storage/1EB9-597E/roms/handheld/tcaveman.zip
ARGUV[0]=/storage/1EB9-597E/roms/handheld/tcaveman.zip
Searching for driver tcaveman
Driver tcaveman not found -1
Game not found: tcaveman
Searching for driver handheld
Driver handheld not found -1
Driver not found: handheld
RES:-2
MAIN FIRST

the same if a try to load a console game, the last mame that work correctly was 0.223, it seems that mame has been compiled to esclude all non arcade hardware, is this the case?

**Comment by tcamargo** [comment]
Console support is disabled on android builds. Linker doesn't like the enormous mame binary. It is possible to build a console only version.

**Comment by sonninnos** [comment]
Android indeed has arcade MAME stuff and other MESS stuff as separate cores.

**Comment by grant2258** [comment]
> Console support is disabled on android builds. Linker doesn't like the enormous mame binary. It is possible to build a console only version.

Its not an issue anymore when fixing the android builds I always compiled the full versions when testing. Its not really something I feel strongly about either way though.
