### ISSUE TITLE
Rotation broken (manual TATE monitor setup)

### ISSUE THREAD

**Issue by riggles1** [libretro/mame#275]
I'm using a switchres 15kHz CRT setup that I manually can rotate, with the newest core I have to set rotation to 90 degrees CW in the MAME GUI settings for every new vertical game I boot up. Before it would properly display vertical games with the proper orientation and aspect ratio with rotate set to "none" in the MAME settings.

In the RetroArch config Allow Rotation is set to off (necessary for a manual CRT rotation setup), updating from 0.235 to the 0.237 core broke it.

**Comment by riggles1** [comment]
Found that the "CORE ROTATION OPTION" section in the .ini has now changed values from 1 to 0.
In order to stop auto rotation, changing the .ini to the following disables it, allowing you to manually rotate the monitor instead.

rotate                    0
ror                       0
rol                       0
autoror                   0
autorol                   0
flipx                     0
flipy                     0

**Comment by MistyDreams** [comment]
you dont want to do the rotate 0. 

Load anything with a flip x or flip y like othunder kick ect  rotate 1 and autoror or autorol will fix you up
