### ISSUE TITLE
DPad Inputs no longer mapped by default (Regression from ~0.234 Core)

### ISSUE THREAD

**Issue by msheehan79** [libretro/mame#276]
It appears the default MAME input binds for dpad control are no longer mapped with the 0.237 update. 

Worked fine with the 0.234 build I was using previously - I can see when I check in the TAB menu that in 0.234 the input options for P1 Up shows as "UP or Joy 1 Up or Joy 1 D-Pad Up" while in 0.237 it only displays "UP or Joy 1 Up". I did not test on the 0.235 core so I am not sure at what point the regression occurred.

I understand we can simply bind those inputs in a cfg file or within the MAME Tab menu but it was nice to have them "just work" without an extra configuration step.

**Comment by Immersion95** [comment]
It was working on 0.235

**Comment by msheehan79** [comment]
That PR solved it, thanks!
