### ISSUE TITLE
[Feature Request] Enable 2+ lightguns

### ISSUE THREAD

**Issue by StormedBubbles** [libretro/mame#282]
Hello,

The current implementation of lightguns is great for one player. Would it be possible to enable multiple mice for 2+ lightguns? Plenty of gun games allowed 2-player simultaneous play, with a handful allowing up to 3.

**Comment by riggles1** [comment]
This is related the the rawinput not working issue I just submittted https://github.com/libretro/mame/issues/290

**Comment by StormedBubbles** [comment]
Feature added with above commit!
