### ISSUE TITLE
Compiled files

### ISSUE THREAD

**Issue by jlopezvil** [libretro/mame#286]
Only a question ...

I dont know if we can compile files for a rockchip rk3399. (its an arm64 i think).

There is someplace where we can get specific compiled output files by system? Or only is possible if we compile files ourselfs?

**Comment by tcamargo** [comment]
Please check the libretro-mame package in batocera-linux. It has the necessary instructions to compile an aarch64 binary yourself.

https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/emulators/retroarch/libretro/libretro-mame/libretro-mame.mk

**Comment by jlopezvil** [comment]
> Please check the libretro-mame package in batocera-linux. It has the necessary instructions to compile an aarch64 binary yourself.
> 
> https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/emulators/retroarch/libretro/libretro-mame/libretro-mame.mk

Sorry, could you address me to this instructions ...   I can compile for retropie because have a rpi4 with retropie installed. 
Give and address how can i compile batocera-linux, please ....   In my pc? Or where and how?

Need advice, please
