### ISSUE TITLE
Rawinput multimice support is broken

### ISSUE THREAD

**Issue by riggles1** [libretro/mame#290]
Can't assign multiple mice devices (2x spinners) with rawinput in the current mame 0.238 core, RA 1.10.0 (which has support for rawinput multimice itself).
Only way spinners work is through dinput and wiring spinner 1 connection as X-axis and spinner 2 for Y-axis, acting as the same device rather than separate devices.

Not having rawinput working makes it impossible to use 2x trackballs, as that would require X1Y1 and X2Y2 from the other device. 

the following are set in mame.ini (mame.ini itself is working/being read as other changes do affect things, in other words, the ini is enabled in the core options, and there's no core overrides active when I'm testing this)
mouse                    1
multimouse            1
mouseprovider       rawinput

**Comment by riggles1** [comment]
This same issue also makes it impossible to have more than 1 lightgun, or more than 1 mouse for the games that use those.

**Comment by StormedBubbles** [comment]
I have been having some fun exploring the code of various emulators and adapted the Sinden Lightgun creator's code for an older MAME version to lr-mame (.241) in my own fork of this emulator. 

The RetroArch lightgun API's "screen_x" and "screen_y" coordinates are mapped to each joypad's right analog stick (mapped via the MAME Tab menu or per-game cfg files), and the mouse buttons for player 1 can then be mapped via that same Tab menu, with the remaining mouse buttons for players 2-6 mapped to joypad buttons in that same Tab menu and then to the corresponding mouse buttons via the RetroArch menu. It's actual lightgun control from both RetroArch's perspective and MAME's, but the control data are communicated to MAME as right analog sticks in the code to get around the lack of multi-mouse support.

This is a very inelegant solution, but my understanding is that MAME's raw input is incompatible with Linux systems. A core option by someone more talented than me could help decide if the right analog stick gets mapped to the lightgun or the actual joypad.

Further, the code I used could be adapted to regular mice if you wanted to use multiple mice, spinners, or trackballs. I could make a branch of my fork specific to mice, but, again, while the code works, my solution is very hacked together and could be made more user friendly by a more talented programmer 😆

**Comment by riggles1** [comment]
How does this work out with spinners in that case? Since with spinners and trackballs you can accelerate infinitely in one direction, there's no upper limit unlike with lightgun+mouse.

I've been looking forward for multimice to be fixed, I do like regular MAME too, but RetroArch's CRTSwitchres implementation (either generation or video modeline picking), and DSP (custom sound EQ+other sound presets that you can make per game, just like shaders but for sound), and the way I have the UI set up on my Astro City. There's some other features that aren't in vanilla MAME either. So hopefully rawinput multimice gets properly implemented.

Soon RA is going to get real lightgun support for use with CRT's, there are Linux and soon Windows Guncon2 drivers, and a Guncon1 adapter that's coming that transforms it into a mouse device. 
The problem is that real lightgun games have a screen flash, but fixed guns and IR gun games didn't have this, and light guns need to be able to see phosphors on light up on the screen. But there are workarounds:

The only thing that's missing for RA to have full support for the Guncon's is a custom shader that triggers when you pull the lightgun trigger (single flash, on until you let go of the trigger, or strobing). 
Optionally white flashes or even better, a LUT shader that lights up black and darker color shades only, even a dark gray is enough.

Hopefully we're able to find someone who can change the RA shader backend to give it that kind of functionality where it activates on a device input. This is super off topic, I'll submit a feature request for this later.

**Comment by StormedBubbles** [comment]
As far as I can tell, RetroArch has pointer (touch screen), lightgun, and mouse devices as the only candidates for spinner input, and spinners with infinite spin I guess would be handled as mice on the RetroArch side.

Do the guns always need the flash to track? GunCon games, at least on PS1, allow you to check your calibration in game without constantly firing. Even the NES Zapper is capable of tracking without shooting, as evidenced by the homebrew game Zap Ruder. That game and Chiller even allow two Zappers to work simultaneously and as separate input devices!

I am actually looking for a shader that does the opposite: I hate the flash! 😄

I created a branch of my lr-mame fork (0.241) specifically for mice if you want to try it out. The branch is called [0.241_multimouse](https://github.com/StormedBubbles/mame/tree/0.241_multimouse)

As I mentioned above, this is a pretty inelegant solution, but you should be able to use up to 6 separate mice by mapping each player's axes to the corresponding joypad's right analog axis. For example, to get the X axis mapped for player 2, you'd clear out that part of the config in the "Input (this game)" menu by selecting it with a keyboard and hitting Escape, and then you'd manually edit the .cfg file for the game so that the X axis for player 2 is mapped to "JOYCODE_2_RXAXIS" (and then have "JOYCODE_2_RYAXIS" for the second player's Y axis, etc.). Also make sure that the mouse indices are set appropriately in the RetroArch menu.

To get mouse buttons for multiple mice, do the same trick as above with the MAME input menu, but set whatever button you need to an actual joypad button, and then map the desired mouse button to the corresponding joypad button in the RetroArch menu.

**If you are just looking to use two spinners, perhaps the vanilla lr-mame will still work for you if you assign one of the spinners to the X axis and the other to the Y axis and use the RetroArch menu to assign both of them to port 1.**

**Comment by riggles1** [comment]
That's the only way multi spinners work, yes, and requires to rewire one of the spinners for a different axis, but the issue extends to trackballs and mice as well, you need X1 Y1 X2 Y2 for that, since you need the infinite direction acceleration for these games to play well.

Also, flash is necessary or it won't work due to there being no lit phosphor (or a too dim phosphor) in certain areas of the screen depending on what's being displays. SNES super scope games instead had no black or dark shades and were really bright colorful games, like Yoshi's Safari, everything you point and shoot at is a bright thing.

NES doesn't need scanline timing, it just checks if the thing it shoots is bright or not, hence the boxes. The Zap Ruder homebrew you mentioned isn't precise enough, because it lacks the scanline timing and instead estimates what this timing would be (later lightguns like guncon1 or 2 had an RCA connector in order to grab the video sync signal necessary for this timing calculation, so that's what makes them exact).

PS1 calibration screens have all lit phosphors, no dark areas  so that's why that works, but in game it needed a screen flash to allow the game to use darker shaders and blacks for the game graphics.

You don't need a white flash, just something that turns black and dark shades into something brighter, so that the lightgun "can see" where you're pointing.

If shaders could detect and react on a device input, you could make a shader that turns blacks into gray (and dark shaders into brighter shades), one that stays on until you let go of the trigger, or one that strobes on and off every frame.

On the flipside, this functionality would also make it possible to make a shader that reacts on the trigger pull, and then copies the previous frame before the screen flash, and displays that instead. Bypassing the white frame flash that way.

**Comment by StormedBubbles** [comment]
After familiarizing myself better with the code, I realize that it should be very straightforward to add multi-mouse and multi-lightgun support within the framework of what is already here. I have already done something similar for lr-mame2010, but here, the structure is already set up (and much, much better than what I did for 2010 😆). I know there's an odd game here and there that could potentially use 8 mice, but 3 seems to be the max for lightguns from what I can think of. I can definitely add these features, but my coding structure is rudimentary. 

Does this libretro core make use of .ini files? If not, I guess multimouse would have to be forced ON in /src/emu/emuopts.h.

**Comment by riggles1** [comment]
This kinda stuff isn't my expertise sadly, however I'm very familiar with RA as far as functionality goes at least. The MAME core has a mame.ini file that you can use, identical to standalone mame, you have to set the "read from file" option on in the MAME core quick menu options in RA for it to read the settings from there, the mame.ini file is placed in the retroarch.exe folder. 

https://i.imgur.com/TGesPfk.mp4 Beardypigs guncon2 driver in action, many games play great with it, in the future we'll need a shader that triggers a screen flash/brightening upon trigger pull though, but one step at a time.

Multimice not working is affecting more people and peripherals though. Good luck on fixing the issue, would be amazing! :D

**Comment by StormedBubbles** [comment]
Awesome! Thanks for the info! The issue with the code here is that exactly 1 mouse device and exactly 1 lightgun device are mapped. I am practicing adjusting the code to add more of each on an older version of MAME that takes considerably less time to compile. 

Do you happen to know if there is any disadvantage to having multimouse enabled?

**Comment by riggles1** [comment]
Don't think so, can't think of a scenario where you wouldn't want multimouse support. It'll still work for people who set their spinners as X and Y instead, thanks to MAME's button mapping flexibility.

Sounds good!

**Comment by StormedBubbles** [comment]
Hi again.

I have multimouse and multilightgun up and running in lr-mame. I also fixed the issues with the mouse buttons. There was no third mouse button (middle click) in the code, while the second mouse button (right click) was there but was not activated correctly.

In my build, you can have up to 4 mice or 4 lightguns. Each mouse has 3 unique buttons, while each lightgun has 2 unique buttons. Is that enough? I don't know of any lightgun games that use more than 3 guns. I know that Atari's Football uses 4 trackballs and that there is a game called "Sprint 8" that has 8 steering wheels. Are 8 separate mice needed for that? I figure 8 could be combined to 4 using the RetroArch menu, but adding additional mice/lightguns is trivial. Getting from 1 to 2 was the tricky part. Going from 2 to whatever higher number involves just switching a few numbers here and there.

One glitch that I am experiencing that is confusing me involves the player 1 X axis in mouse/lightgun games. It seems that the mouse is blocked from moving along the X axis when "Player 1 LSX" is a part of that axis's mapping. If I clear that out and only include "Mouse 1 X" or "Gun 1 X," then the movement is fine. This glitch does not affect the other players at all! Do you experience this? I can't find anything in the code that may be causing this.

**Comment by StormedBubbles** [comment]
Sorry for the double post. It turns out that the joypad will override the X axis for every player and block the mouse movement unless either (a) there is no controller mapped to that particular port, or (b) the stick movement is cleared from the MAME mapping. I will see if there is something in the code causing this.

EDIT: joystick drift may have been the culprit for me here. I am having trouble reproducing this issue consistently.

**Comment by StormedBubbles** [comment]
Multimouse/lightgun added with above commit. Enjoy (and comment if any issues arise)! 😀

**Comment by tempt187** [comment]
From a lightgun perspective I just wanted to say ty very much for this! I've tested every light gun game and can successfully use single or dual light guns now!
