### ISSUE TITLE
Error with RetroArch loading LCD games unless boot_from_cli option is enabled. 

### ISSUE THREAD

**Issue by slaminger** [libretro/mame#299]
[retroarch.log](https://github.com/libretro/mame/files/8351751/retroarch.log)
this first log is when the issue is happening, and the second log is where it is not.
[retroarch (1).log](https://github.com/libretro/mame/files/8351756/retroarch.1.log)

In the non working log it appears to be attempting to use the folder name to determine the machine type, and in the log where it works I see: [libretro INFO] SOURCE FILE: ../../../../../src/mame/drivers/hh_sm510.cpp 

the logic determining this seems to happen here: https://github.com/libretro/mame/blob/master/src/osd/libretro/libretro-internal/retro_init.cpp#L216

 Edit: We could modify the way it handles this. Where it has the if/else condition we can modify this, so it tries to use the folder name as machine type, and if this fails it then resorts to acting as if boot from cli is enabled to try and load the game, and then if both of those fail it exits. This should fix the problem without creating tons of work or huge re-writing of things.

**Comment by sonninnos** [comment]
I believe this issue is no more.
