### ISSUE TITLE
Issues building on Debian 8 with clang 

### ISSUE THREAD

**Issue by mdeguzis** [libretro/mame#3]
Having a bit of trouble building this. Is there a lot WIP yet? I'm aware that the libretro nighly build PPA hasn't updated this core binary since June of this year. I'm ok being patient, but wanted to make sure there wasn't something I was doing wrong. Maybe I am missing a package such as `libc++`?

```
override_dh_auto_build:
	# MAME
	make OVERRIDE_CXX="clang++-3.8" OVERRIDE_CC="clang-3.8" USELIBCO=1 SUBTARGET=arcade $(PLATFORM)
	# MESS
	make OVERRIDE_CXX="clang++-3.8" OVERRIDE_CC="clang-3.8" USELIBCO=1 SUBTARGET=mess $(PLATFORM)
```

* [build log](http://sprunge.us/haES)
* [debian files](https://github.com/ProfessorKaos64/LibreGeek-Packaging/blob/brewmaster/retroarch/libretro-mame/debian)

**Comment by Enverex** [comment]
Keep in mind that this isn't the same repo anymore, the repo for that core was moved to https://github.com/twinaphex/mame-old - this repo is the new resync with upstream for 0.179.

**Comment by mdeguzis** [comment]
That explains it, I appreciate it. By that account, I then should just be patient for the work here to be done and keep an eye on the nightlies for an update? If I am provided a package for the old core, should I continue to do so? I see TwinAphex updated it 15 days ago.

**Comment by Enverex** [comment]
Probably for the best. I don't think this actually builds right now (as per https://github.com/libretro/mame/issues/4) but R-Type is working on it. Lots has changed upstream though so it's proving to be a problem reintegrating libretro.

As far as I'm aware the mame-old core isn't really worked on anymore. The only changes for months were minor cleanups and my nag-screen patch so new packages for it wouldn't really be something to worry about. It'll probably change name to MAME-2016 at some point though (like the existing 2003, 2010 and 2014 MAME cores).

**Comment by mdeguzis** [comment]
Got. I really appreciate the input. The only other cores I have to check out with broken builds are ppsspp and mupen64plus. Sometimes 1 or 2 just have issues building with pbuilder.
