### ISSUE TITLE
[Linux] Build failing on i386

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/mame#31]
Do I need to parse something to i386 build? This is what I'm using for x86_64 and ARM64:

```
ifeq ($(ARCH),amd64)
	EXTRA_OPTS = PTR64=1
else ifeq ($(ARCH),arm64)
	EXTRA_OPTS = ARCHOPTS="-mabi=lp64" NOASM=1 FORCE_DRC_C_BACKEND=1
endif
```

The errors:

```
barcrest.make:609: recipe for target '../../../../libretro/obj/libretro/src/mame/drivers/mpu4.o' failed
make[4]: *** [../../../../libretro/obj/libretro/src/mame/drivers/mpu4.o] Error 1
Makefile:118: recipe for target 'barcrest' failed

bfm.make:739: recipe for target '../../../../libretro/obj/libretro/src/mame/drivers/bfm_sc4.o' failed
make[4]: *** [../../../../libretro/obj/libretro/src/mame/drivers/bfm_sc4.o] Error 1

Makefile:121: recipe for target 'bfm' failed
make[3]: *** [bfm] Error 2
```

https://launchpadlibrarian.net/321931544/buildlog_ubuntu-zesty-i386.libretro-mame_1%3A0.185-r201705311220-9f8a36a-57~ubuntu17.04.1_BUILDING.txt.gz

**Comment by sergiobenrocha2** [comment]
It's happening with gcc 5.4.0, 6.2.0 and 6.3.0

**Comment by r-type** [comment]
i see an virtual memory exhausted: Operation not permitted in your log

**Comment by r-type** [comment]
http://forums.bannister.org//ubbthreads.php?ubb=showflat&Number=109841#Post109841
I think we can close this one too. As it will not be fixed in upstream and they probably drop 32 bit support in a short time.

**Comment by inactive123** [comment]
I guess the older MAME cores will always remain a solution then for x86 32bit. Sad that they are doing artificial obsolescence like so many other projects but with RetroArch and libretro, people will always get choice.

**Comment by rb6502** [comment]
We're not doing this arbitrarily; there are real problems keeping 32-bit x86 builds compiling.  If you guys or someone else external can fix them we'll accept the pull request, but nobody on the team runs a 32-bit OS since MAME is 20% faster for free on x64.

**Comment by vadosnaprimer** [comment]
@rb6502 There's no list of them anywhere? One just needs to try and see, right?

**Comment by tcamargo** [comment]
Closing older issues. Please reopen if it is still relevant.
