### ISSUE TITLE
debug build mame224

### ISSUE THREAD

**Issue by claydonkey** [libretro/mame#311]
Steps to reproduce the problem
debug build mame0244 on MinGW (DEBUG=1)

Mame version
mame0244

Compiler and version
gcc 11.2.0 (Rev6, Built by MSYS2 project)

Operating system and version
x86_64-w64-mingw32

Other relevant information
```
{standard input}: Assembler messages:
{standard input}: Fatal error: ../../../../libretro/obj/x64/libretrodbg/src/emu/emumem_aspace.o: file too big
make[3]: *** [emu.make:2084: ../../../../libretro/obj/x64/libretrodbg/src/emu/emumem_aspace.o] Error 1
make[2]: *** [Makefile:85: emu] Error 2
```
Thought that adding the following to genie.lua would fix problem but it hasn't
```
configuration { "mingw*", "x64" }
buildoptions {
"-Wa,-mbig-obj"
}
```

**Comment by MistyDreams** [comment]
this is self explanatory

https://github.com/libretro/mame/blob/fdb7edfb0d142ddb93aa558daa6a771a40fe1c4e/Makefile.libretro#L77-L79

 SYMLEVEL=2  is causing it set it to 1

**Comment by claydonkey** [comment]
Thanks for that MistyDreams. I'll give it a spin
