### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by DocMAX** [libretro/mame#312]
Hi, strange issue: Starting MAME in Retroach 1.10.3 results in a big black window (approx. 1920x1080), and then nothing happens.
Same config on another PC after that window i get a smaller one like the retroarch resolution and i see the game.

Only difference: Non working PC is an AMD 4800U APU, an on my laptop where its working it is a i7 8650U CPU.

**Comment by riggles1** [comment]
Post a log file

Same config as in completely the same root directory with all the files identical? No mame.ini changes, overrides or other configurations that are different?

Keep in mind that you'll have to change the rom directory path in your MAME playlist, you can easily do so by ctrl-F the using the find and replace feature in notepad++, in case it's a path issue.

**Comment by DocMAX** [comment]
Strange, after an pacman update it suddenly works. Never mind for now... But how do i make logs? I can't see something special or crashs in the regular retroarch log (retroarch -v).

**Comment by riggles1** [comment]
In the RA settings there's a Logging setting, you can save the log to a file which will then be found at RA root/logs.
