### ISSUE TITLE
Segfault on MacOS with 2nd load. 

### ISSUE THREAD

**Issue by palmerj** [libretro/mame#324]
With using the latest MAME core on an intel mac I can load one game and it runs ok. However, when I then close that and then start another rom within the same retroarch session the rom does't load and I only get a black screen. When I close retroarch I get a segfault. My guess is some memory is not being cleaned up.

See MacoS crash report [here](https://gist.github.com/palmerj/02bb98c79ec25734868e5d00098953c8)

**Comment by FlexingTiger** [comment]
Same issues #300

**Comment by FlexingTiger** [comment]
[master](https://github.com/libretro/mame) ([#372](https://github.com/libretro/mame/pull/372))

**Comment by estefan3112** [comment]
Exactly, resolved.

**Comment by palmerj** [comment]
Great stuff - thank you @warmenhoven
