### ISSUE TITLE
How to compile arcade-only libretro.mame?

### ISSUE THREAD

**Issue by crashGG** [libretro/mame#327]
In the standalone version of mame, the parameter " make SUBTARGET=arcade" can be used, if want to compile arcade-only libretro.mame, how to modify the "make" file?

**Comment by FlexingTiger** [comment]
make -f Makefile.libretro -j$(nproc) SUBTARGET=arcade

**Comment by crashGG** [comment]
> make -f Makefile.libretro -j$(nproc) SUBTARGET=arcade

Thank you, your suggestion is very useful. The parameters compiled are the same as the original MAME
