### ISSUE TITLE
Poor rendering of vector games

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/mame#34]
I think stand-alone Mame uses HLSL for that, but we probably can make them look better?

Using alternate render and bumping up the resolution helps, but it's limited to 960*720.
Perhaps add more resolutions? 1080p 1440p 2160p

Or allow reading of ini files resolution setting to be used by the alternate renderer?
We could then make a vector.ini with whatever resolution and settings.

**Comment by r-type** [comment]
yes maybe we can think about this , add an core option ,if alt-render on  and config_resolution on , use the res set by the ini file.

**Comment by Tatsuya79** [comment]
The new resolutions for the alt renderer seem to work well.
I tried 1080p and 4k, that's smooth.

**Comment by Awakened0** [comment]
I tried Asteroids, Black Widow and Tempest at 1440x1080 and they all look great. I don't need the AA shader on top anymore :D. There's a crt/vector-glow shader that I should try, but it's only available in slang ATM.
