### ISSUE TITLE
[Bug]The core doesn't read the system/mame files with latest RA build (stable/nightlies)

### ISSUE THREAD

**Issue by Immersion95** [libretro/mame#343]
The system/mame files are ignored so no cheats/ctrl/dats/hash/ini are working

**Comment by riggles1** [comment]
quick menu>core options>read configuration on (enable as a global option, check any individual game .opt files in the config folder where it might be "off" instead).

Every mame related file such as cheats are working here with 0.251, windows 10 64bit. Make sure you also have a mame.ini file in the same folder as retroarch.exe, containing this: https://pastebin.com/raw/Ttsn6N8U

(change the directory paths to your paths) and check what other options there you might want to change, I have my stuff set up for CRTSwitchres use. But yeah, check that file out, make changes to it and you'll get it working for your particular setup.

**Comment by Immersion95** [comment]
> quick menu>core options>read configuration on (enable as a global option, check any individual game .opt files in the config folder where it might be "off" instead).
> 
> Every mame related file such as cheats are working here with 0.251, windows 10 64bit. Make sure you also have a mame.ini file in the same folder as retroarch.exe, containing this: https://pastebin.com/raw/Ttsn6N8U
> 
> (change the directory paths to your paths) and check what other options there you might want to change, I have my stuff set up for CRTSwitchres use. But yeah, check that file out, make changes to it and you'll get it working for your particular setup.

The mame.ini file alongside retroarch.exe is only needed if you need custom paths. It should default to system/mame without it. Only needed option is Read Config in the core menu.

It now works, problem was the latest RA nightlies from today. I reverted from an oldest version and it now works.

**Comment by Immersion95** [comment]
I'm reopening the issue as it's now present with latest RA build - Stable or nightlies. It works perfectly with older RA builds.

Here is the log, it seems that it search the system files insides the save folder.
[retroarch__2023_02_02__11_08_01.log](https://github.com/libretro/mame/files/10567758/retroarch__2023_02_02__11_08_01.log)

**Comment by Immersion95** [comment]
Found the commit that broke it, i opened an issue in the RA git.
