### ISSUE TITLE
Support for Switch/ libnx possible?

### ISSUE THREAD

**Issue by eberhab** [libretro/mame#344]
Hi all, I am interested to use MAME/MESS current on the Switch. It seems that the CI build-file already envisions this option here: https://github.com/libretro/mame/blob/master/.gitlab-ci.yml#L278
However it seems that one would need to add an appropriate `platform` section to the [Makefile](https://github.com/libretro/mame/blob/master/Makefile.libretro), which I can't seem to figure out. Anyone keen to give this a try? Thanks for great work! Any help would be much appreciated :)

**Comment by foreversos** [comment]
i need too.
if it can work,please nofity me

**Comment by eberhab** [comment]
It seems to be difficult: https://github.com/libretro/mame/issues/111

As a workaround one can install android on the switch and use the new android64 mame core ...

**Comment by sonninnos** [comment]
Indeed one issue is enough.
