### ISSUE TITLE
Reduce compiled size with STRIP_SYMBOLS

### ISSUE THREAD

**Issue by zach-morris** [libretro/mame#345]
MAME is one of the largest cores for obvious reasons.  In testing, I've found though that I can reduce the size of the compiled core by about 50MB using STRIP_SYMBOLS.

Example, compiling on OSX with :
```
make -f Makefile.libretro
```
Results in:
```
mame_libretro.dylib 337.7MB
mame_libretro.dylib.zip 88.2MB
```

But if i use STRIP_SYMBOLS:
```
make -f Makefile.libretro STRIP_SYMBOLS=1
```
Results in:
```
mame_libretro.dylib 291.8MB
mame_libretro.dylib.zip 79.1MB
```

I didn't test other options, but other optimizations/reductions may be possible.  Ref here:
https://github.com/mamedev/mame/issues/5161

**Comment by sonninnos** [comment]
I recently commented out the adding of any symbols, so stripping is no longer necessary, even though stripping was already happening at some stage in buildbot.
