### ISSUE TITLE
Mame 252 files

### ISSUE THREAD

**Issue by jlopezvil** [libretro/mame#346]
Maybe update files to compile last mame 252? Thanks

**Comment by riggles1** [comment]
Been waiting for this as well, but best to be patient, it'll happen. The libretro mame user base has gotten bigger with groovyarcade CRT users and the likes, and game console users.

Can't wait to finally play VS Captain Flag!

**Comment by joepogo** [comment]
Was just wondering the same thing as jlopezvil. Usually they sync pretty quickly with mame and bump versions so I hope it's not some sort of issue. 

I do know mame .252 did make a couple substantial changes so I'm hoping that's not the issue. 

My hopes went up when I saw it was updated today but it wasn't a sync with upstream.

**Comment by crashGG** [comment]
Maybe you can update your title to 253 )

**Comment by RetroBoyCN** [comment]
waiting for  254 )

**Comment by LibretroAdmin** [comment]
We're waiting for someone to maintain this. I have asked stuken a few times to update it but there hasn't been any activity.

**Comment by riggles1** [comment]
Yeah seems like 254 is the one to do it with, Namco System 10!
