### ISSUE TITLE
Support hiscore.dat

### ISSUE THREAD

**Issue by gtranche** [libretro/mame#35]
Is there a way to have hiscore.dat working on this core ?
It's working on mame2016-libretro but not on this upstream version.

**Comment by rb6502** [comment]
The previous patch implementation of hiscore.dat was destructive to MAME's internals and would cause random crashes and could corrupt your .CFG file in extreme cases.  This is why MAMEdev didn't support it and were pretty aggressive about telling people not to use it.

The new Lua implementation in recent MAME / recent MAME RA cores is clean and sandboxed; it may still cause bugs in games, but they stay isolated to the games now.

**Comment by gtranche** [comment]
Ok, but i was talking about the new implementation avaible in the official branch. 
I didn't find any solution to have the hiscore working on it.

**Comment by rb6502** [comment]
Oh, gotcha.  I don't know if the RA core version of MAME supports the Lua scripting engine.

**Comment by r-type** [comment]
It works as expected here.
I only have to enable hiscore in plugin.ini (hiscore                   1)
then the log show me stuff about hiscore
and i endup with a hi folder containing some gamename.hi files.
I reloaded these games and the new hiscore are loaded fine.

```
RetroArch [libretro INFO] :: ChangeAV: w:640 h:480 ra:1.333333.
hiscore: scores read
hiscore: write_scores
hiscore: write_scores output
hiscore: write_scores end
Average speed: 100.01% (178 seconds)
Enter sdlwindow_exit
```

@gtranche maybe your pluginspath in mame.ini is incorrectly set.

**Comment by gtranche** [comment]
I don't have any plugin.ini or mame.ini, where do i have to put them ? And the ui directory ?
(I do not use mame-2016 or mame-2003 I usethe up to date version of this repository)
Thank you

**Comment by r-type** [comment]
In retroarch system directory , a mame folder should be created.
inside you should have ini folder with those file .
 (you have also to enable core option for read config/write config, i'm not sure why they aren't enable by default)
if you want the plugins stuff working , you have to copy from the upstream mame folder plugins in retroarch system directory in that mame folder.

hi folder are created in you retroarch save directory (if save directory is not set then it's set in the content dir directory)

I'm sure someone wrote an tutorial about this , but i can't remember who and where .

**Comment by gtranche** [comment]
I didn't have any mame.ini or plugin.ini in that folder. I had scv.ini. I tried to rename it to mame.ini.
I modified retroarch-core to enable read and write for ini.
Now when i launch pacman i have a pacman.ini file created but no plugins loaded.
In the ini file in coer misc options I have a "noplugins" line. But it seems that everytime I load the game a new file is created.
I searched on google if it can be a rocketlauncher issue, but in the ahk module i didn't fine anything relative on ini files or plugins.
Is there any way to generate mame.ini file ?
Have I missing something ?
Thank you again for your help :)

**Comment by r-type** [comment]
you can create mame.ini by cmdline or you can just load a game , hit esc and then 
go to 
![mame2](https://user-images.githubusercontent.com/3614417/28226031-e9108d70-68d4-11e7-90ee-ecc7299d41ba.png)
for plugins (if you have the plugin folder provide by upstream release)
you can enable it here
![mame](https://user-images.githubusercontent.com/3614417/28226064-06c178de-68d5-11e7-8c13-15d4ef500742.png)

**Comment by r-type** [comment]
Just to be clear , hiscore plugin work just like other lua plugins.
So your problem is only configuration problem , it's not an issue with the current core.

I think we can close this issue and if you need help to configure your plugins folder, I bet the forum will be a better place. just open a thread at libretro forum.

![consolelua](https://user-images.githubusercontent.com/3614417/28238940-8306d5ee-695f-11e7-9c54-a537442c9d53.png)


```

    _/      _/    _/_/    _/      _/  _/_/_/_/
   _/_/  _/_/  _/    _/  _/_/  _/_/  _/       
  _/  _/  _/  _/_/_/_/  _/  _/  _/  _/_/_/    
 _/      _/  _/    _/  _/      _/  _/         
_/      _/  _/    _/  _/      _/  _/_/_/_/    

mame 0.186	
Copyright (C) Nicola Salmoria and the MAME team

Lua 5.3	
Copyright (C) Lua.org, PUC-Rio

[MAME]>  

```

**Comment by gtranche** [comment]
yes it's seems it's a configuration problem.
Thank you very much @r-type. I know now where I have to search.

**Comment by r-type** [comment]
@gtranche  De rien, n’hésite pas a poster sur le forum Libretro si tu as toujours ton problème.

**Comment by obenguerah** [comment]
@gtranche , did you solved your issue? I can't even have my plugins to show up in the config menu... (windows 10)

**Comment by gtranche** [comment]
@BubsFr sorry i forgot to answer ... i've updated the mame core and everything worked fine !
