### ISSUE TITLE
enable cheats in mame current core?

### ISSUE THREAD

**Issue by ghost** [libretro/mame#351]
Hi

I have no idea how to enable cheats in mame.
I tried many settins in retroarch but it seems nothing works.

Can somebody explain?

**Comment by riggles1** [comment]
Core option > read config enabled

mame.ini file in root (same folder as retroarch.exe, you can get this file from mame standalone) https://pastebin.com/raw/P119NTX6 or grab it here, change the paths to your setup.

cheat  1 (enabled) in the mame.ini

then in your mame folder you place the cheat.7z (don't open the .7z file.)
\system\mame\   < your cheat.7z goes there

You can download the latest cheat0245.zip from here, the cheat.7z file is inside this zip.
http://www.mamecheat.co.uk/

**Comment by ghost** [comment]
Do you have any idea where the root folder is of retroarch on android?

**Comment by riggles1** [comment]
No idea how it works for android no, I assume it would be where your typical folders are (bios folder, roms folder, saves folder etc). Try drop the mame.ini there.

**Comment by Immersion95** [comment]
Cheats were working perfectly in my Shield.

This was my folder : /storage/emulated/0/RetroArch/system/mame/cheat + cheat zip file inside this folder

**Comment by grant2258** [comment]
Cheats are working fine you do need the plugin directory and the cheats though.

**Comment by sonninnos** [comment]
Let's close it then.
