### ISSUE TITLE
could it be synchronized with the upstream 0.254?

### ISSUE THREAD

**Issue by crashGG** [libretro/mame#352]
It has been more than 4 months since the last major version 0.251 was synchronized. We're all eagerly anticipating a new sync...

**Comment by riggles1** [comment]
Yeah, hope it happens with 254 with how significant of a release it is, can't wait to play 254 with CRTSwitchres, with all the new games that have improved, dumped and developed into working status.

If I had gotten into coding I would've loved to maintain this, only recently learned how to compile from source, but not enough to know what changes to make to keep it synched with upstream without ruining it.

My lack of knowledge of that I try make up with CRT repair and CRTEmudriver setup helping for RA CRTSwitchres, I help people with CRT's and CRTEmudriver setups every other day.

**Comment by joepogo** [comment]
There definitely has to be some sort of weird compiling issue or something else preventing this from being synced. 

Retroarch Mame current core was being synced with upstream pretty regularly up until  around 251. Hopefully whoever maintains this can sync soon but it's def concerning to not hear anything from any devs with this one.

**Comment by KamiLordus** [comment]
Definitely +1. Too bad MAME current core libretro doesn't have any active maintainer.

**Comment by MistyDreams** [comment]
The classes and some internal things changed a bit. Im sure someone will get to it someday.
