### ISSUE TITLE
Graphic bug when game starts (grey frame)

### ISSUE THREAD

**Issue by KamiLordus** [libretro/mame#356]
Many games have a border around the screen at launch. Can it be fixed?
For example, the frame appears in Killer Instinct 1 and 2.

![Bez tytułu](https://github.com/libretro/mame/assets/123302593/2d0151ee-e1a1-4717-afeb-65397d2d6f3b)

**Comment by sonninnos** [comment]
For some reason it does not happen with vulkan, but with every other video driver..

**Comment by KamiLordus** [comment]
@sonninnos Thanks a lot for fix and support mame core.
