### ISSUE TITLE
 Compilation of lr-mame and lr-mess in RetroPie fails

### ISSUE THREAD

**Issue by FollyMaddy** [libretro/mame#362]
One or more commits in May have broken something that causes to fail compilation.
More info can be found over here :
https://retropie.org.uk/forum/topic/34238/lr-mess-will-not-compile-17-may-2023

A commit from April the 2nd does work fine for both lr-mame and lr-mess.

@sonninnos 
Seems something has broken with your commits.
Can you have a look at this problem ?
Thanks.

**Comment by sonninnos** [comment]
Unfortunately I have no idea what change exactly could cause that..

**Comment by cmitu** [comment]
I think it's a RetroPie build issue.
We're building the core without `REGENIE=1` and I think some of commits since April 2 have modified the files used by `mame` build system (`genie`). Without re-generating the proper _makefiles_, the build fails.

I'm taking a look at this to see what's going on.

**Comment by sonninnos** [comment]
Aah, well I guess I have to create a new flag for skipping the makefile generation which takes an insane amount of time on every run when they already exist. Since normal makefile always sets `REGENIE` as 1, I decided to make 0 skip the step that is already done after run once with 1.

Stupid me didn't notice any difference on my system when it was 0, so therefore I thought it was safe to use.

**Comment by cmitu** [comment]
That may not be an issue. The Gitlab builds seem to work (apart from some failed jobs which error out for a different reason) - I think they already have `REGENIE=1` added in the build instructions.
FWIW `REGENIE=1` seems to fix the error reported by @FollyMaddy, I'll need to check the `arcade` only core to see how it behaves. 

Thanks for taking a look.

**Comment by sonninnos** [comment]
Okeydoke, should be fixed with the latest change. Sorry about that.

**Comment by FollyMaddy** [comment]
Thank you guys for all the effort 👍

**Comment by cmitu** [comment]
@sonninnos thank you for the fixes. 
The build works now also without `REGENIE=1`, just like before. I think the issue can be closed.
