### ISSUE TITLE
libretro-mame core installed from the testing ppa crashing on boot.

### ISSUE THREAD

**Issue by i30817** [libretro/mame#37]
Just installed it an tried to load the core (not launching a game).

uname -a
Linux AIVAS 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

> 
> XDG_CONFIG_HOME=/media/i30817/Huggin/Downloads  retroarch -v
> RetroArch [INFO] :: This is RetroArch version 1.6.1 (Git fb33dcf)
> RetroArch [INFO] :: === Build =======================================
> Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 
> Built: Jul  1 2017
> RetroArch [INFO] :: Version: 1.6.1
> RetroArch [INFO] :: Git: fb33dcf
> RetroArch [INFO] :: =================================================
> RetroArch [INFO] :: [Config]: Loading default config.
> RetroArch [INFO] :: [Config]: loading config from: (null).
> RetroArch [INFO] :: Looking for config in: "/media/i30817/Huggin/Downloads/retroarch/retroarch.cfg".
> RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: RGB565.
> RetroArch [INFO] :: Redirecting save file to "/media/i30817/Huggin/Downloads/retroarch/saves/.srm".
> RetroArch [INFO] :: Redirecting savestate to "/media/i30817/Huggin/Downloads/retroarch/savestates/.state".
> RetroArch [INFO] :: Version of libretro API: 1
> RetroArch [INFO] :: Compiled against API: 1
> RetroArch [INFO] :: [Audio]: Set audio input rate to: 29970.03 Hz.
> RetroArch [INFO] :: Found shader "/media/i30817/Huggin/Downloads/retroarch/shaders/retroarch.cgp"
> RetroArch [INFO] :: Found shader "/media/i30817/Huggin/Downloads/retroarch/shaders/retroarch.glslp"
> RetroArch [INFO] :: [Video]: Video @ fullscreen
> RetroArch [ERROR] :: [Wayland]: Failed to connect to Wayland server.
> RetroArch [INFO] :: [GLX]: GLX_OML_sync_control and GLX_MESA_swap_control supported, using better swap control method...
> RetroArch [INFO] :: [GL]: Found GL context: x
> RetroArch [INFO] :: [GL]: Detecting screen resolution 1366x768.
> RetroArch [INFO] :: [XINERAMA]: Xinerama version: 1.1.
> RetroArch [INFO] :: [XINERAMA]: Xinerama screens: 1.
> RetroArch [INFO] :: [GLX]: Using Xinerama on screen #0.
> RetroArch [INFO] :: [GLX]: X = 0, Y = 0, W = 1366, H = 768.
> RetroArch [INFO] :: [GLX]: Using windowed fullscreen.
> RetroArch [INFO] :: [GLX]: Found swap function: glXSwapIntervalMESA.
> RetroArch [INFO] :: [GLX]: glXSwapInterval(1)
> RetroArch [INFO] :: [GL]: Vendor: X.Org, Renderer: Gallium 0.4 on AMD RV710 (DRM 2.43.0 / 4.4.0-83-generic, LLVM 3.8.0).
> RetroArch [INFO] :: [GL]: Version: 3.0 Mesa 12.0.6.
> RetroArch [INFO] :: [GL]: Using resolution 1366x768
> RetroArch [INFO] :: [GL]: Default shader backend found: glsl.
> RetroArch [INFO] :: [Shader driver]: Using GLSL shader backend.
> RetroArch [INFO] :: [GLSL]: Checking GLSL shader support ...
> RetroArch [WARN] :: [GL]: Stock GLSL shaders will be used.
> RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
> RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
> RetroArch [INFO] :: [GLSL]: Linking GLSL program.
> RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
> RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
> RetroArch [INFO] :: [GLSL]: Linking GLSL program.
> RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
> RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
> RetroArch [INFO] :: [GLSL]: Linking GLSL program.
> RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
> RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
> RetroArch [INFO] :: [GLSL]: Linking GLSL program.
> RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
> RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
> RetroArch [INFO] :: [GLSL]: Linking GLSL program.
> RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
> RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
> RetroArch [INFO] :: [GLSL]: Linking GLSL program.
> RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
> RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
> RetroArch [INFO] :: [GLSL]: Linking GLSL program.
> RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
> RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
> RetroArch [INFO] :: [GLSL]: Linking GLSL program.
> RetroArch [INFO] :: [GL]: Using 4 textures.
> RetroArch [INFO] :: [GL]: Loaded 1 program(s).
> RetroArch [INFO] :: [GL]: Using GL_RGB565 for texture uploads.
> RetroArch [INFO] :: [Joypad]: Found joypad driver: "udev".
> RetroArch [INFO] :: [Font]: Using font rendering backend: freetype.
> RetroArch [INFO] :: [DBus]: Suspended screensaver via DBus.
> RetroArch [INFO] :: [PulseAudio]: Requested 24576 bytes buffer, got 18432.
> RetroArch [INFO] :: [Menu]: Found menu display driver: "menu_display_gl".
> RetroArch [INFO] :: [Font]: Using font rendering backend: freetype.
> RetroArch [INFO] :: [Font]: Using font rendering backend: freetype.
> RetroArch [INFO] :: SRAM will not be saved.
> RetroArch [INFO] :: Loading history file: [/media/i30817/Huggin/Downloads/retroarch/content_history.lpl].
> RetroArch [INFO] :: Loading history file: [/media/i30817/Huggin/Downloads/retroarch/content_music_history.lpl].
> RetroArch [INFO] :: Loading history file: [/media/i30817/Huggin/Downloads/retroarch/content_video_history.lpl].
> RetroArch [INFO] :: Loading history file: [/media/i30817/Huggin/Downloads/retroarch/content_image_history.lpl].
> RetroArch [INFO] :: [GL]: VSync => on
> RetroArch [INFO] :: [GLX]: glXSwapInterval(1)
> RetroArch [INFO] :: [PulseAudio]: Unpausing.
> RetroArch [INFO] :: [GL]: VSync => on
> RetroArch [INFO] :: [GLX]: glXSwapInterval(1)
> RetroArch [INFO] :: [PulseAudio]: Pausing.
> RetroArch [ERROR] :: Failed to open libretro core: "/usr/lib/x86_64-linux-gnu/libretro/mame_libretro.so"
> RetroArch [ERROR] :: Error(s): /usr/lib/x86_64-linux-gnu/libretro/mame_libretro.so: undefined symbol: _ZN13md_cons_state21screen_vblank_consoleEi
> RetroArch [INFO] :: [PulseAudio]: Unpausing.
> RetroArch [INFO] :: [PulseAudio]: Unpausing.
> RetroArch [INFO] :: [PulseAudio]: Unpausing.
> RetroArch [INFO] :: [Config]: Saved new config to "/media/i30817/Huggin/Downloads/retroarch/retroarch.cfg".
> RetroArch [INFO] :: [PulseAudio]: Pausing.
> RetroArch [INFO] :: [XINERAMA]: Xinerama version: 1.1.
> RetroArch [INFO] :: [XINERAMA]: Xinerama screens: 1.
> RetroArch [INFO] :: [XINERAMA]: Saved monitor #0.
> RetroArch [INFO] :: [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
> RetroArch [INFO] :: [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
>

**Comment by r-type** [comment]
the core not loading because it missing symbol.

RetroArch [ERROR] :: Error(s): /usr/lib/x86_64-linux-gnu/libretro/mame_libretro.so: undefined symbol: _ZN13md_cons_state21screen_vblank_consoleEi

BTW it works fine here with my own linux build and with the official buildbot one http://buildbot.libretro.com/nightly/linux/x86_64/latest/

So it's ppa build related , and no mame core related.

**Comment by i30817** [comment]
I don't know where to report a bug on the ppa though

**Comment by r-type** [comment]
maybe @sergiobenrocha2 can look at.

**Comment by sergiobenrocha2** [comment]
It's crashing here too, ubuntu 17.04

```
Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) 
(gdb) 
(gdb) bt full
#0  0x0000000000000000 in ?? ()
No symbol table info available.
#1  0x00005555555b0e94 in core_unload_game () at core_impl.c:384
No locals.
#2  0x00005555555ba1e5 in command_event_deinit_core (reinit=true) at command.c:1045
No locals.
#3  command_event (cmd=cmd@entry=CMD_EVENT_CORE_DEINIT, data=data@entry=0x0) at command.c:2054
        hwr = 0x555555cd70a0 <hw_render>
        boolean = false
#4  0x00005555555b57f0 in retroarch_main_init (argc=4, argv=argv@entry=0x7fffffffdf28) at retroarch.c:1293
No locals.
#5  0x00005555555c43b7 in content_load (info=0x7fffffffddf0) at tasks/task_content.c:276
        i = <optimized out>
        retval = true
        rarch_argc = 0
        rarch_argv_ptr = 0x7fffffffdf28
        rarch_argv = {0x0 <repeats 32 times>}
        argv_copy = {0x0 <repeats 32 times>}
        rarch_argc_ptr = 0x7fffffffddf0
        wrap_args = 0x5555566e3a80
#6  task_load_content (content_info=content_info@entry=0x7fffffffddf0, content_ctx=content_ctx@entry=0x7fffffffdd50, launched_from_menu=launched_from_menu@entry=true, launched_from_cli=launched_from_cli@entry=true, 
    error_string=error_string@entry=0x7fffffffdd48) at tasks/task_content.c:821
        name = "\000\066\240\"2\005\300\372\235\375\372\372\322\b>'I6\242\"4\005\300\372\235\375\372\372\320\b<'I6\244\"5\005\300\372\235\375\372\372\317\b:'I6\246\"6\005\300\372\236\375\372\372\315\b8'I6\250\"8\005\300\372\236\375\371\372\314\b6'J6\252\"9\005\300\372\236\375\371\372\312\b5'J6\254\";\005\300\372\237\375\371\372\310\b3'J6\256\"<\005\300\372\237\375\371\372\307\b1'J6\260\"=\005\300\372\237\375\371\372\305\b/'J6\262\"?\005\300\372\237\375\371\372\304\b-'K6\264\"@\005\300\372\240\375\370\372\302\b+'K6\266\"B\005\300\372\240\375\370\372\301\b*'K6\270\"C\005\300\372"...
        msg = "\000\066\277\"H\005\300\372\241\375\367\372\271\b 'L6\301\"J\005\300\372\242\375\367\372\267\b\037'L6\303\"K\005\300\372\242\375\367\372\266\b\035'L6\305\"M\005\300\372\242\375\367\372\264\b\033'L6\307\"N\005\300\372\243\375\367\372\262\b\031'M6\311\"O\005\300\372\243\375\367\372\261\b\027'M6\313\"Q\005\300\372\243\375\366\372\257\b\025'M6\315\"R\005\300\372\243\375\366\372\256\b\024'M6\317\"T\005\300\372\244\375\366\372\254\b\022'M6\321\"U\005\300\372\244\375\366\372\252\b\020'M6\323\"V\005\300\372\244\375\366\372\251\b\016'N6\325\"X\005\300\372\245\375\366\372\247\b\f'N6\327\"Y\005\300\372"...
        contentless = false
        is_inited = false
#7  0x00005555555c5349 in task_load_content_callback (content_info=0x7fffffffddf0, loading_from_cli=<optimized out>, loading_from_menu=true) at tasks/task_content.c:1473
        content_ctx = {subsystem = {data = 0x0, size = 0}, name_ips = 0x0, name_bps = 0x0, name_ups = 0x0, valid_extensions = 0x0, directory_cache = 0x0, directory_system = 0x0, is_ips_pref = false, is_bps_pref = false, 
          is_ups_pref = false, history_list_enable = false, block_extract = false, need_fullpath = false, set_supports_no_game_enable = false, patch_is_blocked = false, bios_is_missing = false, 
          check_firmware_before_loading = false, temporary_content = 0x7fffffffdf28}
        ret = false
        error_string = 0x0
        global = <optimized out>
        settings = 0x7fffde551010
#8  0x00005555555afd69 in rarch_main (argc=4, argv=0x7fffffffdf28, data=0x0) at frontend/frontend.c:115
        info = {argc = 4, argv = 0x7fffffffdf28, args = 0x0, environ_get = 0x5555555aedb0 <frontend_unix_get_env>}
        args = 0x0
#9  0x00007fffefc083f1 in __libc_start_main (main=0x5555555ab390 <main>, argc=4, argv=0x7fffffffdf28, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdf18) at ../csu/libc-start.c:291
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 6035910635776746143, 93824992596000, 140737488346912, 0, 0, 474716725111792287, 474751692211724959}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x7fffffffdf50, 
              0x7ffff7ffe168}, data = {prev = 0x0, cleanup = 0x0, canceltype = -8368}}}
        not_first_call = <optimized out>
#10 0x00005555555ad04a in _start ()
No symbol table info available.
```

**Comment by sergiobenrocha2** [comment]
> the core not loading because it missing symbol.
> 
> RetroArch [ERROR] :: Error(s): /usr/lib/x86_64-linux-gnu/libretro/mame_libretro.so: undefined symbol: _ZN13md_cons_state21screen_vblank_consoleEi

Are there any problem building only the arcade side?

```
dh_auto_build -- OSD="retro" verbose=1 RETRO=1 NOWERROR=1 OS="linux" TARGETOS="linux" CONFIG="libretro" NO_USE_MIDI="1" $(EXTRA_OPTS) TARGET=mame SUBTARGET=arcade
	mv mamearcade_libretro.so mame_libretro.so
```

**Comment by sergiobenrocha2** [comment]
Ok, after 5h building (no kidding), and it's working here. I guess it's something wrong with SUBTARGET=arcade

I'll update the package

**Comment by r-type** [comment]
@sergiobenrocha2 
look at here.

http://www.mameworld.info/ubbthreads/showthreaded.php?Cat=&Number=367314&page=0&view=expanded&sb=5&o=&fpart=1&vc=1

you have to apply this patch

https://git.redump.net/mame/commit/?id=f31efbf4d0a9e130c40e6d23c0bb0b109317d29a

and then arcade build will be fine.

**Comment by sergiobenrocha2** [comment]
Well, I'm building the whole core now, libretro-mess package is only a dummy package now. Anyway thanks!
