### ISSUE TITLE
Mame 255 update

### ISSUE THREAD

**Issue by Jimizan** [libretro/mame#373]
Please 255 update
Many fix snd new entry ( namco )
More good of actual 251 bugged

**Comment by RetroBoyCN** [comment]
I have upgraded to 0.255 , through synchronized the main branch code of mame directly. Some code of the libretro interface needs to be modified.Because mame refactored the input part of the code.

https://github.com/mamedev/mame/commit/c6650dc072144cb1d5ec3a7b411349c8b04a3a5b

**Comment by KamiLordus** [comment]
@LawawaR If you managed to update libretro core to 0.255 maybe share it.
Many people have been waiting a very long time for an update to the new version, which no one wants to do / or can't do :(

**Comment by sonninnos** [comment]
All hope is not lost, look what I have here: 
![image](https://github.com/libretro/mame/assets/45124675/0f7e01db-961c-4022-8279-54d4bd7280bd)

Will need to do final testing and stuff before pushing.

**Comment by KamiLordus** [comment]
@sonninnos wow i didn't think this day would come :)
great news.

**Comment by joepogo** [comment]
Wow! Amazing work @sonninnos!! This is awesome! Thank you for the great news!! Looking forward to it! 

 I use mame on Xbox series x, is there anything I could look into as to why certain games crash mame current like galaga, donkey Kong etc, but work just fine on mame 2015 core?

**Comment by guljam** [comment]
I tried to build by simply replacing the files of mame 0.255, but I get an error when compiling

If there is no mame core update manager, it would be nice to provide general guidelines on how to update the core on a wiki etc.

Anyway I'm waiting for an update, and your efforts are appreciated.

**Comment by sonninnos** [comment]
There can't really be a guideline, since when the source changes enough so that current libretro code also needs changing, you must improvise..

From 0.254 to 0.255 was just a simple merge without conflicts. From 0.251 to 0.254 required a bit of inspection and learning how the code used to work and how it works now.

**Comment by Jimizan** [comment]
so , hard to see a working libretro core mame again in short time...bad thing.

**Comment by riggles1** [comment]
Thank you a lot for the PR! From me and on behalf of all CRT users. Lots of us using CRTEmudriver RA CRTswitchres, RA in Groovyarcade, the customizability is too good with what you can do with configs, forcing scales, video modes, EQ and stuff so it'll be amazing to have all that with everything 255 has to offer : D

**Comment by RetroBoyCN** [comment]
@LibretroAdmin can update to 0.255.

**Comment by riggles1** [comment]
I found one issue with the 255 build, the inputs stop working after you go to the MAME menu "Tab">DIP switches and at the bottom when you pick Reset System.

"F3" resetting and RA Quick Menu resetting works as well, inputs continue working without issues there.

**Comment by sonninnos** [comment]
Yes I have noticed that too, and it only affects controllers, not keyboard. Did it work before?

Edit: No worries, I'll look into it.

**Comment by riggles1** [comment]
Yes, I would usually use that one as it's the fastest way to reset on my machine if I was already setting some stuff in the MAME menu.

Not the biggest deal, but it a bit strange. Appreciate it!

**Comment by sonninnos** [comment]
Ok, fixed.

**Comment by Jimizan** [comment]
can be update to 255 with RetroPie-Setup/retropie_setup.sh  (raspberry) ?
I think is always 251.

**Comment by sonninnos** [comment]
This will not be merged until buildbot pipeline builds. Patience. Nothing prevents you from building this manually though.

**Comment by Jimizan** [comment]
if was possible sure I just made from 252....

**Comment by hoshinota** [comment]
I was able to build for Raspberry Pi without any problems. thank you

**Comment by Jimizan** [comment]
prego

**Comment by nemo93** [comment]
@Jimizan Retropie will automatically update the MAME binary whenever [that PR](https://github.com/libretro/mame/pull/376) will be merged in the `main` branch. Please be patient. Do not ask here for Retropie stuff, it's best to discuss this on the dedicated forum instead. Thanks!

@sonninnos thanks to you and to everyone looking after that core. Can't wait to try 255!

**Comment by Jimizan** [comment]
> @Jimizan Retropie will automatically update the MAME binary whenever [that PR](https://github.com/libretro/mame/pull/376) will be merged in the `main` branch. Please be patient. Do not ask here for Retropie stuff, it's best to discuss this on the dedicated forum instead. Thanks!
> 
> "PREGO" > is for Hoshinota thank you   , no requests...

**Comment by grant2258** [comment]
@sonninnos i successfully build mame0256 for android locally just two minor fixes where required.

https://github.com/grant2258/mame/tree/libretro/mame-0.256
```
export PATH="$PATH:/opt/android-ndk-r25c"
export ANDROID_NDK=/opt/android-ndk-r25c
export ANDROID_NDK_HOME=/opt/android-ndk-r25c
make -f Makefile.libretro SUBTARGET=tiny  platform=android-arm64  SUBTARGET=tiny  -j6
```

**Comment by sonninnos** [comment]
Using the libretro android docker image?

Good at least that 0.256 goes easily on top of 0.255, but why not worry about that update later..

**Comment by grant2258** [comment]
Just a local build but there is a sdl logging issue just a define fix breaks the build in retromain put a pull request in for that though in the 255 branch (I had RETRO=1 set in the make file in case your wondering) the x86 build will probably fail as it has no RETRO ifdef and will just compile the sdl version instead. Ill compile the full arm64 mame256 in case people want to test it. It includes all your updates from 255.

**Comment by sonninnos** [comment]
It didn't go that far with the buildbot docker image, and it fails before it starts the actual compilation part. It stopped with `Clang version 6.0 or later needed` even though the same check exists in the current branch, and there it does not stop. Indeed I only tried x86_64 so far.

**Comment by grant2258** [comment]
try adding cc=gcc  or cc=clang (small cc not uppercase to the parameters). I  came across this and it mingw in the clang env because there  was no gcc 

0256 built fine for arm64 apart from one issue that was an easy fix. This is so people can test on android can delete if you don't want it there https://github.com/grant2258/mame/releases/tag/libretromame0256

make CC=clang CXX=clang++  worked for msys2 clang env because its the same host and target. The  mingw clang  cross compile needed a small cc to make the host compile (genie exe) properly when using clang not sure how the docker is setup but thats the only time I came across that problem.

**Comment by sonninnos** [comment]
The android docker image is not using msys2.

**Comment by grant2258** [comment]
The ndk I have has no gcc only clang the msys2 clang env doesnt have gcc installed and needs CC=clang and CXX=clang++
to bypass that same error your seeing thats why i mentioned it to you.

see 3rdparty/genie/build/gmake.linux/genie.make 
```
CC  = gcc
CXX = g++
AR  = ar
```

seems to be uppercase in the newer makefile build or im remembering wrong either that or explicitly add gcc to the docker because the makefile expects gcc to be present for the host unless its over ridden on 255 and 256 anyway

```
cd /opt/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin                                                                    ✔ 
    /opt/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin  tree                                                                                                                                  ✔ 
.
├── aarch64-linux-android21-clang
├── aarch64-linux-android21-clang++
├── aarch64-linux-android22-clang
├── aarch64-linux-android22-clang++
├── aarch64-linux-android23-clang
├── aarch64-linux-android23-clang++
├── aarch64-linux-android24-clang
├── aarch64-linux-android24-clang++
├── aarch64-linux-android26-clang
├── aarch64-linux-android26-clang++
├── aarch64-linux-android27-clang
├── aarch64-linux-android27-clang++
├── aarch64-linux-android28-clang
├── aarch64-linux-android28-clang++
├── aarch64-linux-android29-clang
├── aarch64-linux-android29-clang++
├── aarch64-linux-android30-clang
├── aarch64-linux-android30-clang++
├── aarch64-linux-android31-clang
├── aarch64-linux-android31-clang++
├── aarch64-linux-android32-clang
├── aarch64-linux-android32-clang++
├── aarch64-linux-android33-clang
├── aarch64-linux-android33-clang++
├── armv7a-linux-androideabi19-clang
├── armv7a-linux-androideabi19-clang++
├── armv7a-linux-androideabi21-clang
├── armv7a-linux-androideabi21-clang++
├── armv7a-linux-androideabi22-clang
├── armv7a-linux-androideabi22-clang++
├── armv7a-linux-androideabi23-clang
├── armv7a-linux-androideabi23-clang++
├── armv7a-linux-androideabi24-clang
├── armv7a-linux-androideabi24-clang++
├── armv7a-linux-androideabi26-clang
├── armv7a-linux-androideabi26-clang++
├── armv7a-linux-androideabi27-clang
├── armv7a-linux-androideabi27-clang++
├── armv7a-linux-androideabi28-clang
├── armv7a-linux-androideabi28-clang++
├── armv7a-linux-androideabi29-clang
├── armv7a-linux-androideabi29-clang++
├── armv7a-linux-androideabi30-clang
├── armv7a-linux-androideabi30-clang++
├── armv7a-linux-androideabi31-clang
├── armv7a-linux-androideabi31-clang++
├── armv7a-linux-androideabi32-clang
├── armv7a-linux-androideabi32-clang++
├── armv7a-linux-androideabi33-clang
├── armv7a-linux-androideabi33-clang++
├── bisect_driver.py
├── clang -> clang-14
├── clang++ -> clang
├── clang-14
├── clang-check
├── clangd
├── clang-format
├── clang-tidy
├── dsymutil
├── git-clang-format
├── i686-linux-android19-clang
├── i686-linux-android19-clang++
├── i686-linux-android21-clang
├── i686-linux-android21-clang++
├── i686-linux-android22-clang
├── i686-linux-android22-clang++
├── i686-linux-android23-clang
├── i686-linux-android23-clang++
├── i686-linux-android24-clang
├── i686-linux-android24-clang++
├── i686-linux-android26-clang
├── i686-linux-android26-clang++
├── i686-linux-android27-clang
├── i686-linux-android27-clang++
├── i686-linux-android28-clang
├── i686-linux-android28-clang++
├── i686-linux-android29-clang
├── i686-linux-android29-clang++
├── i686-linux-android30-clang
├── i686-linux-android30-clang++
├── i686-linux-android31-clang
├── i686-linux-android31-clang++
├── i686-linux-android32-clang
├── i686-linux-android32-clang++
├── i686-linux-android33-clang
├── i686-linux-android33-clang++
├── ld -> ld.lld
├── ld64.lld -> lld
├── ld.lld -> lld
├── lld
├── lldb
├── lldb-argdumper
├── lldb.sh
├── lld-link -> lld
├── llvm-addr2line -> llvm-symbolizer
├── llvm-ar
├── llvm-as
├── llvm-bolt
├── llvm-cfi-verify
├── llvm-config
├── llvm-cov
├── llvm-cxxfilt
├── llvm-dis
├── llvm-dwarfdump
├── llvm-dwp
├── llvm-lib -> llvm-ar
├── llvm-link
├── llvm-lipo
├── llvm-modextract
├── llvm-nm
├── llvm-objcopy
├── llvm-objdump
├── llvm-profdata
├── llvm-ranlib -> llvm-ar
├── llvm-rc
├── llvm-readelf -> llvm-readobj
├── llvm-readobj
├── llvm-size
├── llvm-strings
├── llvm-strip -> llvm-objcopy
├── llvm-symbolizer
├── llvm-windres -> llvm-rc
├── merge-fdata
├── remote_toolchain_inputs
├── sancov
├── sanstats
├── scan-build
├── scan-view
├── x86_64-linux-android21-clang
├── x86_64-linux-android21-clang++
├── x86_64-linux-android22-clang
├── x86_64-linux-android22-clang++
├── x86_64-linux-android23-clang
├── x86_64-linux-android23-clang++
├── x86_64-linux-android24-clang
├── x86_64-linux-android24-clang++
├── x86_64-linux-android26-clang
├── x86_64-linux-android26-clang++
├── x86_64-linux-android27-clang
├── x86_64-linux-android27-clang++
├── x86_64-linux-android28-clang
├── x86_64-linux-android28-clang++
├── x86_64-linux-android29-clang
├── x86_64-linux-android29-clang++
├── x86_64-linux-android30-clang
├── x86_64-linux-android30-clang++
├── x86_64-linux-android31-clang
├── x86_64-linux-android31-clang++
├── x86_64-linux-android32-clang
├── x86_64-linux-android32-clang++
├── x86_64-linux-android33-clang
├── x86_64-linux-android33-clang++
└── yasm
```

so for arm64 try
```
make -f Makefile.libretro  platform=android-arm64   RETRO=1 -j6 OVERRIDE_CC=clang OVERRIDE_CXX=aarch64-linux-android24-clang++
```
youll need to make sure you add the bin path as well depending where it is. 
```
export PATH="$PATH:/opt/android-ndk-r25c:/opt/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin"
```

```

clang and clang++  will compile for the default host is worth ruling out.

**Comment by grant2258** [comment]
managed to recreate your issue. Here is whats happening

```
make  android-arm  -j7 VERBOSE=1                                                                                                                        2 ✘ 
GCC 13.1.1 detected
makefile:1195: *** ANDROID_NDK_HOME is not set.  Stop.
```

```
make -f Makefile.libretro platform=android-arm -j7 VERBOSE=1                                                                                            2 ✘ 
make REGENIE=1 VERBOSE=1 NOWERROR=1 OSD="retro" NO_USE_MIDI=1 NO_USE_PORTAUDIO=1 PYTHON_EXECUTABLE=python3 CONFIG=libretro OVERRIDE_CC=clang ANDROID_NDK_HOME="/opt/ndk" android-arm  TARGET=mame
make[1]: Entering directory '/home/mappy/source/lrmame'
Clang 15.0.7 detected
3rdparty/genie/bin/linux/genie --distro=generic --CC='clang' --OPTIMIZE=3 --NOWERROR='1' --target='mame' --subtarget='mame' --build-dir='build' --NO_USE_MIDI='1' --NO_USE_PORTAUDIO='1' --PYTHON_EXECUTABLE='python3' --osd='retro' --targetos='linux' --PLATFORM='unknown' --gcc=android-arm --gcc_version= --osd=retro --targetos=android --PLATFORM=arm --NO_USE_MIDI=1 --NO_OPENGL=1 --USE_QTDEBUG=0 --DONT_USE_NETWORK=1 --NOASM=1 gmake
Clang version 6.0 or later needed
make[1]: *** [makefile:1219: build/projects/retro/mame/gmake-android-arm/Makefile] Error 255
make[1]: Leaving directory '/home/mappy/source/lrmame'
```
Its not showing the main makefiles path error because it fails before the check from lua when run from parent make. The mingw issues I had where the bins live in two different places on linux and in one place on msys2. So that should be the end if that mystery


and finally so android arm users and xbox and windows64 bit users can grab the binary https://github.com/grant2258/mame/releases/tag/Libretro_mame0256 just referencing @joepogo  since he uses the xbox build should keep most users happy until the official release
