### ISSUE TITLE
Primal Rage 2 boot loop bug

### ISSUE THREAD

**Issue by KamiLordus** [libretro/mame#375]
The game works (with problems) on the standard mame, on the libretro core the game displays an error (boot loop) right after starting.
https://www.youtube.com/watch?v=brInYEKhFkw

**Comment by sonninnos** [comment]
Even 0.255 says this:
![retroarch_2023_06_06_05_20_30_383](https://github.com/libretro/mame/assets/45124675/d501e84b-385d-4208-b3da-7078426f8bf8)

**Comment by KamiLordus** [comment]
The game has many problems on standard MAME (i tested 0.254). Is a rare, unfinished and unreleased game. However, it works and is playable.
![Bez tytułu](https://github.com/libretro/mame/assets/123302593/fa661c4a-c1cb-4653-8bf0-1fb6015e2dee)
![2](https://github.com/libretro/mame/assets/123302593/9940c7f9-c56d-4305-be59-4c403e4adee5)

On the libretro core 0.251, the game restarts itself endlessly as soon as it is launched.
![3](https://github.com/libretro/mame/assets/123302593/587bb968-1a6d-464e-a663-b9951cbb2347)

**Comment by litaniast** [comment]
Looks like you used the ARCADEUI instead of vanilla MAME. It used the hack for make primrag2 playable that doesn't admit in mainline MAME project. I tried that on standalone MAME 0.255, but it gets same WatchDog RESET boot loop error.

**Comment by KamiLordus** [comment]
Yes, you are 100% correct. Thanks for the info.

**Comment by sonninnos** [comment]
Surely the same patch can still be added here..?

**Comment by litaniast** [comment]
ARCADE64 binary file (that can be downloaded in https://arcade.mameworld.info/index.html) has the addon source for build ARCADE64 instead of vanilla MAME, So, maybe check the difference of Sony ZN hardware source and can be playable on libretro? 

Edit: That hack is only the fix for watchdog boot loop. The game itself isn't so stable for now because of unemulated copy protection.

**Comment by riggles1** [comment]
At that point mame4rage2 could be ported over, open source. But I don't know how different it is outside if machine modifications.
