### ISSUE TITLE
Compilation error?

### ISSUE THREAD

**Issue by nadavbh12** [libretro/mame#38]
Ran git clone, and complied. Got the error below:
``make -j11
GCC 5.4.1 detected
Compiling src/osd/modules/render/drawretro.cpp...
../../../../../src/osd/modules/render/drawretro.cpp: In member function ‘virtual int renderer_retro::draw(int)’:
../../../../../src/osd/modules/render/drawretro.cpp:77:6: error: unused variable ‘pitch’ [-Werror=unused-variable]
  int pitch = (width + 3) & ~3;
      ^
cc1plus: all warnings being treated as errors``

Running on Ubuntu 16.04.
Anything I'm missing?

**Comment by r-type** [comment]
It is not clear to me why you dont have NOWERROR=1 set.
Btw you should rebuild using make -f Makefile.libretro
Or pass the correct args like
make OSD="retro" verbose=1 RETRO=1 NOWERROR=1 OS="linux" TARGETOS="linux"
CONFIG="libretro" NO_USE_MIDI="1" PTR64=1 TARGET=mame -j10

**Comment by r-type** [comment]
You can look at here if you dont use makefile.libretro
https://github.com/libretro/mame/tree/master/src/osd/libretro/libretro-internal

**Comment by nadavbh12** [comment]
Ok, my bad.
`make -f Makefile.libretro` solved it. Thanks

**Comment by vadosnaprimer** [comment]
That part should be added to README.

**Comment by r-type** [comment]
what part ? like the majority of libretro core build with -f Makefile.libretro  ?
you can always look at libretro-super to see how particular recipe works.

BTW , we can add it in 
https://github.com/libretro/mame/blob/master/src/osd/libretro/libretro-internal/README.MD

but not on the main README which are the upstream README . I don't want to touch this file.

**Comment by nadavbh12** [comment]
@r-type 
That makes sense, though I've previously compiled 3 libretro cores SNES9X, Stella, Genesis-Plus and none required it. So maybe it makes sense to put it somewhere...

**Comment by r-type** [comment]
Yes im agree with this but not on the mame readme.
