### ISSUE TITLE
Update MAME core to ver.0256 for RetroArch / Lakka [Windows, Mac, Linux, Android].

### ISSUE THREAD

**Issue by RetroDevPR** [libretro/mame#384]
The MAME (Multiple Arcade Machine Emulator) core is an essential emulator component of RetroArch, enabling users to play classic arcade games on modern devices and on multiple platforms. MAME is known for its extensive library of supported games, accurately emulating various hardware platforms and providing an authentic retro gaming experience.

Based on my research and understanding, MAME version 0.256 includes significant improvements, bug fixes, and enhancements compared to the previous versions. By updating RetroArch's MAME core to this version, users would benefit from:

Expanded Game Library: 
Version 0.256 includes updates to the game database, allowing RetroArch users to access a wider range of arcade games. This would increase the variety of gaming experiences and cater to the diverse interests of RetroArch's user base.

Improved Compatibility: 
MAME 0.256 offers better compatibility with game ROMs, reducing issues related to compatibility and increasing the likelihood of successfully running older arcade titles within RetroArch.

Bug Fixes and Enhancements: 
Updating to MAME 0.256 would address known issues and bugs present in previous versions. Users would experience improved stability, smoother gameplay, and enhanced performance, resulting in an overall better gaming experience.

New Features and Options: 
MAME regularly introduces new features and options to enhance gameplay and customization. By incorporating MAME 0.256 into RetroArch, users would have access to these latest features, allowing them to personalize their gaming experience further.

I believe that incorporating the latest MAME version to 0.256 into RetroArch / Lakka updating the Mame core would be a highly valuable core update for the entire RetroArch community. It would demonstrate the commitment of the development team towards delivering the best possible emulation experience to users and attract new users interested in retro gaming.

**Comment by riggles1** [comment]
If you subscribed to this git with notifications you'd know that it's being worked on actively, request posts for already in progress development doesn't make things go faster. 

0.255 is already available if you compile it yourself, there are a few roadblocks that are being worked on namely android halting a buildbot update, 256 isn't significantly different and will happen when this roadblock is fixed. 

Do some browsing around here to read the discussions.
