### ISSUE TITLE
[.256] games not running on ARM / in progress

### ISSUE THREAD

**Issue by nemo93** [libretro/mame#395]
Hi, 

_thanks again_ for updating that core to latest MAME. I'm doing a sanity check on roughly **700 games** to see how things go. Below a list of games I can't get to run with the `0.256` release. Those were known to run on earlier version (`.220`-ish).

## Disclaimer

Please note that I'm using **only parent** from a non-merged set. I've triple-checked the roms by hands to be sure nothing is missing from the archive. I can't get a specific error message from the log just a standard `segmentation fault` upon starting any of the listed games below.

## Issues

* arbalest.7z / [Arbalester](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=arbalest)
* astorm.7z / [Alien Storm](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=astorm)
* brvblade.7z / [Brave Blade](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=brvblade)
* calibr50.7z / [Caliber .50](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=calibr50)
* cryptklr.7z | 420uaa04.chd / [Crypt Killer](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=cryptklr)
* desertbr.7z / [Desert Breaker](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=desertbr)
* more should be added as it takes time to test everything (I'm testing games in alphabetical order).

## Setup

Raspberry Pi4 on a vanilla Retropie (`4.8.4`). Kernel `5.10.103-v7l+`, 32-bit Raspberry OS in `fKMS mode`. Retroarch is `1.15.0` and the MAME core is up-to-date. I know it's a specific setup. It wouldn't surprised me that the aforementioned games are not working only on ARM.

**EDIT**: those games do run fine on MAMEUI (Windows).

```ini
URL: https://github.com/libretro/mame.git
Branch: master
Commit: 093209930f5fbdaee0d6f3a3666f3d70025d089f
Date: 2023-07-20
```

**Comment by Tasosgemah** [comment]
When was the core updated? I used the core downloader a few minutes ago and it's still version 0.251

**Comment by KamiLordus** [comment]
@Tasosgemah There was no update, there are still some problems with compiling on ios/android.
If you are using for example RA on pc then you can download mame 256 from here:
https://git.libretro.com/libretro/mame/-/pipelines

**Comment by nemo93** [comment]
Closing given:

1. compiling 7e51710f0e4f6b86c736e088a389c687f926f672 fix issues with astorm.7z / brvblade.7z / cryptklr.7z / desertbr.7z
2. issue is with `seta/downtown.cpp` driver (new ticket will be open shortly)
