### ISSUE TITLE
Problem with 3D games

### ISSUE THREAD

**Issue by KamiLordus** [libretro/mame#399]
I have a problem with 3D games for example:
Tekken series
Street Fighter EX series
Soul Edge
Rival Schools
When trying to start a game (Tekken 3 for example) retroarch turns on and off multiple times.
It seems a bit like RA is restarting on each of the individual screens in the game. The game starts after a while, but this restart is annoying.
Interestingly, enabling "alternate rendering" fixes this problem, but forces you to use a higher resolution of *640x480 or higher.
I'm currently using mame 256 for windows, but the problem has occurred before, but not always (251 and earlier).
Interestingly, the 255 version does not have this problem and I checked on the same settings.

RA 1.16
MAME version 256 for win 64
also check 251 same problem, 255 work ok.

**Comment by nemo93** [comment]
I do confirm the screen flashing effect on Raspberry as well, only on 3D games as mentioned.

**Comment by KamiLordus** [comment]
@nemo93 exactly the "flashing effect" caused by retroarch minimizing itself multiple times tired starting game. In the case of Tekken 2, until the intro appears.

I leave the retroarch log from turning on Tekken 2
[retroarch__2023_07_24__12_12_40.log](https://github.com/libretro/mame/files/12144729/retroarch__2023_07_24__12_12_40.log)

edit:
I checked on dx 11, gl, and vulcan all work the same. Only "alternate rendering" helps but it increases the resolution, which negatively affects the shaders.

**Comment by Tasosgemah** [comment]
There is a similar issue with emulating FM-Towns through the MAME core. It does this annoying flicker when it changes resolutions.

So i think it has to do with resolution changing.

**Comment by Tasosgemah** [comment]
More recent versions fixes the issue.

**Comment by nemo93** [comment]
I just tumbled upon a 2D game presenting the same behavior:

* brival.7z / [Burning Rival](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=brival) (running on SEGA System32 hardware)

Should I find other non 3D games I'll report back in that post.

**Comment by sonninnos** [comment]
Just update the core, the video reinit because of max geometry change is no longer an issue.

**Comment by KamiLordus** [comment]
All the games listed in the first post work fine after downloading the new update.
I also checked Burning Rival and I don't see a problem.
So I close this issue.
