### ISSUE TITLE
[.256] issue with `seta/downtown.cpp` driver

### ISSUE THREAD

**Issue by nemo93** [libretro/mame#409]
Hi, 

_thanks again_ for updating that core to latest MAME. I'm doing a sanity check on roughly **700 games** to see how things go. Below a list of games I can't get to run with the `0.256` release. Those were known to run on earlier version (`.220`-ish). Those games do run fine on MAMEUI (Windows).

## Issue

**Disclaimer**: please note that I'm using **only parent** from a non-merged set. I've triple-checked the roms by hands to be sure nothing is missing from the archive as well as CRC. 

I can't get a specific error message from the log. The core is simply closing as soon as I try running any of the below. Those games do rely on the `seta/downtown.cpp` driver.

* arbalest.7z / [Arbalester](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=arbalest)
* calibr50.7z / [Caliber .50](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=calibr50)
* downtown.7z / [DownTown](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=downtown)
* metafox.7z / [Meta Fox](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=metafox)
* tndrcade.7z / [Thundercade](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=tndrcade)
* twineagl.7z / [Twin Eagle](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=twineagl)

## Setup

Raspberry Pi4 on a vanilla Retropie (`4.8.4`). Kernel `5.10.103-v7l+`, 32-bit Raspberry OS in `fKMS mode`. Retroarch is `1.15.0` and the MAME core is up-to-date.

```ini
URL: https://github.com/libretro/mame.git
Branch: master
Commit: 7e51710f0e4f6b86c736e088a389c687f926f672
```

**Comment by stuken** [comment]
it's missing from src/mame/arcade.flt so its probably not getting compiled.

**Comment by joepogo** [comment]
I haven't had a chance to test yet but I'm assuming this affects all platforms using the 256 core now?

**Comment by grant2258** [comment]
Only android has the arcade/mess split.  I dont see any sense in splitting it to be honest as long as someone wants to maintain the file it pretty much up to them. Its make no difference to the end user but spice is the variety of life I guess. The android builds where broke just put a fix in so it wont be an android issue. arbalest has gfx issues in mame0256 its it find on the latest master on the mame github though.

**Comment by sonninnos** [comment]
Yep, I vote for just having one single MAME for android, since I'm not even seeing the mess version in online updater, even though it does exist in buildbot for arm64.. And the filesize isn't even that much smaller to begin with.

**Comment by grant2258** [comment]
are the filenames correct for core.info?

**Comment by nemo93** [comment]
I'm afraid I'm not sure to understand :sweat_smile: Let me know if there's anything I can do on my end to add that driver. 

I'm still on the `.256` version and thus far (~300 games tested) compatibility is really excellent with the many drivers I've tested even on such a low-spec device as RPi4! Fantastic job.

**Comment by grant2258** [comment]
@nemo93 if you compiled this yourself make sure you dont use the arcade target also check the logs when the game closes to see what went wrong.

**Comment by nemo93** [comment]
@grant2258 appreciate the help! I'm relying on the binary provided by Retropie (too long to compile by myself on RPi4). Here's [the script](https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/libretrocores/lr-mame.sh) that's being used for compilation. 

I'm a bit confused as I can see 2 targets being set `TARGET=mame` and `SUBTARGET=arcade` in that script. I assume the latter is taking precedence given I got issue with the aforementioned driver. I'm fine dealing with Retropie's maintainers directly yet would you be so kind to confirm the correct target to use please in order to get the `seta/downtown.cpp` driver added?

With the current binary there's absolutely nothing in the log. The core cleanly closes immediately after trying to load any of the games mentioned.

EDIT: nevermind I just see @sonninnos added a [PR](https://github.com/libretro/mame/pull/417) that will fix that issue for good. Thanks a lot!

**Comment by sonninnos** [comment]
No need to worry about it, I tested and confirmed that simply adding the device to arcade.flt does the job.
