### ISSUE TITLE
Throttle prevents fast-forwarding from working

### ISSUE THREAD

**Issue by Immersion95** [libretro/mame#413]
I know that is known and may not even be an issue but It would be great to have "throttle" allowing fast-forwarding.

VRR/Fressync work great without "throttle" but there are a few hiccups, "throttle" allows it to be perfect.

**Comment by sonninnos** [comment]
Pretty sure you can't have both by design.. One would have to use the MAME internal fast-forwarding in that case.

**Comment by Immersion95** [comment]
Great idea ! I added the button to my ctrl file :).
