### ISSUE TITLE
star sweep and killer instict

### ISSUE THREAD

**Issue by kounabi22** [libretro/mame#415]
in raspberry pi4 using retropie 
Star sweep cant insert coins when press the coin button and 
killer instict 1 wont load.
i have check that i have the correct zip.

**Comment by nemo93** [comment]
[Killer Instinct](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=kinst) is loading fine here on a similar setup of yours (RPi4/Retropie). Ensure you got the **CHD** for that game into the `roms/mame-libretro` directory as well. Should look like this:

```
roms/mame-libretro/
└─ kinst/
   └─ kinst.chd
└─ kinst.7z
```

Note: [Killer Instinct](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=kinst) will load but it's unplayable on such low-spec hardware. Keep your expectations to a minimum.

Please confirm the exact set/filename of the archive you're relying on for [Star Sweep](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=starswep)?

**Comment by kounabi22** [comment]
ok i manage to make it run killer instict ,i have delete an old cfg file.

**Comment by grant2258** [comment]
yes it seems the mameini path no longer works must me some sort of regression. Edit looks like its fine you just need to enable read configuration as well.

**Comment by nemo93** [comment]
I do confirm the issue about Star Sweep. I'll raise another ticket to keep things in one place as other games are suffering similar issue.

@kounabi22 do you mind closing that ticket to tidy things up please?
