### ISSUE TITLE
xiistag wont start

### ISSUE THREAD

**Issue by kounabi22** [libretro/mame#419]
xiistag wont start.

**Comment by grant2258** [comment]
can you please post logs of the games that are not loading

**Comment by kounabi22** [comment]
Parameters: 
Executing: /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-mame/mamearcade_libretro.so --config /opt/retropie/configs/arcade/retroarch.cfg "/home/pi/RetroPie/roms/arcade/xiistag.zip" --appendconfig /dev/shm/retroarch.cfg
ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
/opt/retropie/supplementary/runcommand/runcommand.sh: line 1319:  1524 Segmentation fault      /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-mame/mamearcade_libretro.so --config /opt/retropie/configs/arc

**Comment by grant2258** [comment]
I dont have the chd for this game so cant test what are the retroarch logs saying before the segfault?

**Comment by kounabi22** [comment]
retroarch.cfg

video_refresh_rate = "60"
video_fullscreen = "true"
video_fullscreen_x = "1280"
video_fullscreen_y = "1024"
libretro_directory = "/opt/retropie/libretrocores/lr-mame"
libretro_log_level = "1"

**Comment by grant2258** [comment]
I meant the actualy retroarch log if you dont know how to get that is fine. Have you tested all the other chd games in this driver. To debug this the logs from ra would help to see if its a wrong chd ect. 

the ones to test are in between ROM_START 

https://github.com/libretro/mame/blob/7f3a3e4da00e8c3c9621dcac95fba61af0eea2d7/src/mame/sony/taitogn.cpp#L873-L1090

**Comment by kounabi22** [comment]
i look the runcommand.sh in line 1319
------------------------------------
function launch_command() {
    local ret
    # escape $ to avoid variable expansion (eg roms containing $!)
    COMMAND="${COMMAND//\$/\\\$}"
    # launch the command
    echo -e "Parameters: $@\nExecuting: $COMMAND" >>"$LOG"
    if [[ "$CONSOLE_OUT" -eq 1 ]]; then
        # turn cursor on
        tput cnorm
        eval $COMMAND </dev/tty 2>>"$LOG"
        ret=$?
        tput civis
    else
       eval $COMMAND </dev/tty &>>"$LOG"  (this is line 1319)
        ret=$?
    fi
    return $ret
--------------------------------------------------------

**Comment by kounabi22** [comment]
yes zooo,spuzbobl dont load .

**Comment by grant2258** [comment]
hopefully someone with chds can test on other builds and see if it an issue.

**Comment by KamiLordus** [comment]
No problem on windows 64. The game works fine.
![Zrzut ekranu 2023-07-30 211345](https://github.com/libretro/mame/assets/123302593/152fbf70-98d0-4d1a-ba01-0200c55f1b14)

**Comment by msheehan79** [comment]
There was an upstream issue with Taito G-Net games on 0.256 - this has since been resolved with 0.257, so make sure you are using the latest builds.  I also confirmed working fine with the latest (Windows) version off the buildbot just now.

https://github.com/mamedev/mame/issues/11401

**Comment by grant2258** [comment]
@kounabi22 looks like youll need to update to 0257 or wait for retropie to update the binary for you. Thats why having the logs helps it also shows what version you are on.   Thanks for the info @msheehan79. 

I think the logs are in  /dev/shm/runcommand.log on retropie if you enabled the logs. Paste that log going forward will help us out a lot.

**Comment by kounabi22** [comment]
retropie is 0.256 , in my second post is what the runcommand.log say.

**Comment by grant2258** [comment]
> retropie is 0.256 , in my second post is what the runcommand.log say.

thats your run command not the RA logs

**Comment by kounabi22** [comment]
[INFO] RetroArch 1.15.0 (Git 1e5b1ba)
[INFO] === Build =======================================
[INFO] CPU Model Name: ARMv7 Processor rev 3 (v7l)

[INFO] Capabilities: NEON VFPv3 VFPv4
[INFO] Built: Apr  9 2023
[INFO] Version: 1.15.0
[INFO] Git: 1e5b1ba
[INFO] =================================================
[INFO] [Input]: Found input driver: "x".
[INFO] [Core]: Loading dynamic libretro core from: "/opt/retropie/libretrocores/lr-mame/mamearcade_libretro.so"
[INFO] [Config]: Loading config: "/opt/retropie/configs/arcade/retroarch.cfg".
[INFO] [Config]: Appending config: "/dev/shm/retroarch.cfg".
[INFO] [Environ]: SET_VARIABLES.
[INFO] [Overrides]: Redirecting save file to "/home/pi/RetroPie/roms/arcade/xiistag.srm".
[INFO] [Overrides]: Redirecting save state to "/home/pi/RetroPie/roms/arcade/xiistag.state".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: SYSTEM_DIRECTORY: "/home/pi/RetroPie/BIOS".
[INFO] [Environ]: CORE_ASSETS_DIRECTORY: "/home/pi/.config/retroarch/downloads".
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [Environ]: SET_PIXEL_FORMAT: XRGB8888.
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] [Environ]: SET_KEYBOARD_CALLBACK.
[INFO] [Content]: Content loading skipped. Implementation will load it on its own.
[libretro INFO] Starting game: "/home/pi/RetroPie/roms/arcade/xiistag.zip"
[libretro INFO] Game name: xiistag
[libretro INFO] Game description: XII Stag (V2.01J 2002/6/26 22:27)
[INFO] [Environ]: SET_ROTATION: 1
[libretro INFO] SOURCE FILE: ../../../../../src/mame/sony/taitogn.cpp
[libretro INFO] PARENT: coh3002t
[libretro INFO] NAME: xiistag
[libretro INFO] DESCRIPTION: XII Stag (V2.01J 2002/6/26 22:27)
[libretro INFO] YEAR: 2002
[libretro INFO] MANUFACTURER: Triangle Service
[libretro WARN] upd78081.655 NOT FOUND (NO GOOD DUMP KNOWN) (tried in xiistag coh3002t)
WARNING: the machine might not run correctly.
[INFO] [Replay]: Found last replay slot: #0
[INFO] [SRAM]: Skipping SRAM load.
[INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 48139.52 Hz.
[INFO] [Video]: Set video size to: 1280x1024.
[WARN] [DRM]: Couldn't get device resources.
[WARN] [DRM]: Couldn't get device resources.
[INFO] [DRM]: Found 1 connectors.
[INFO] [DRM]: Connector 0 connected: yes
[INFO] [DRM]: Connector 0 has 10 modes.
[INFO] [DRM]: Connector 0 assigned to monitor index: #1.
[INFO] [DRM]: Mode 0: (1280x1024) 1280 x 1024, 60.019741 Hz
[INFO] [DRM]: Mode 1: (1152x864) 1152 x 864, 75.000000 Hz
[INFO] [DRM]: Mode 2: (1024x768) 1024 x 768, 75.028580 Hz
[INFO] [DRM]: Mode 3: (1024x768) 1024 x 768, 60.003841 Hz
[INFO] [DRM]: Mode 4: (832x624) 832 x 624, 74.551270 Hz
[INFO] [DRM]: Mode 5: (800x600) 800 x 600, 75.000000 Hz
[INFO] [DRM]: Mode 6: (800x600) 800 x 600, 60.316540 Hz
[INFO] [DRM]: Mode 7: (640x480) 640 x 480, 75.000000 Hz
[INFO] [DRM]: Mode 8: (640x480) 640 x 480, 59.940475 Hz
[INFO] [DRM]: Mode 9: (720x400) 720 x 400, 70.081665 Hz
[INFO] [GL]: Found GL context: "kms".
[INFO] [GL]: Detecting screen resolution: 1280x1024.
[INFO] [EGL] Found EGL client version >= 1.5, trying eglGetPlatformDisplay
[INFO] [EGL]: EGL version: 1.4
[INFO] [EGL]: Current context: 0x3951800.
[INFO] [KMS]: New FB: 1280x1024 (stride: 5120).
[INFO] [GL]: Vendor: Broadcom, Renderer: V3D 4.2.
[INFO] [GL]: Version: OpenGL ES 3.1 Mesa 19.3.2.
[INFO] [GL]: Using resolution 1280x1024.
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shaders/RetroPie]: Configuration file shader path found.
[INFO] [Shaders]: Specific shader preset found at "/opt/retropie/emulators/retroarch/shader/zfast_lcd_standard.glslp".
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [udev]: Pad #0 (/dev/input/event5) supports force feedback.
[INFO] [udev]: Pad #0 (/dev/input/event5) supports 16 force feedback effects.
[INFO] [Autoconf]: Logitech Gamepad F310 configured in port 1.
[INFO] [udev]: Pad #1 (/dev/input/event6) supports force feedback.
[INFO] [udev]: Pad #1 (/dev/input/event6) supports 16 force feedback effects.
[INFO] [Autoconf]: Microsoft X-Box 360 pad configured in port 2.
[INFO] [udev]: Pad #2 (/dev/input/event7) supports force feedback.
[INFO] [udev]: Pad #2 (/dev/input/event7) supports 16 force feedback effects.
[INFO] [Autoconf]: Logitech Gamepad F310 configured in port 3.
[INFO] [udev]: Pad #3 (/dev/input/event8) supports force feedback.
[INFO] [udev]: Pad #3 (/dev/input/event8) supports 16 force feedback effects.
[INFO] [Autoconf]: Microsoft X-Box 360 pad configured in port 4.
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [Video]: Found display server: "null".
[INFO] ALSA: Using floating point format.
[INFO] ALSA: Period size: 384 frames
[INFO] ALSA: Buffer size: 1536 frames
[INFO] [Display]: Found display driver: "gl".
[ERROR] [MIDI]: snd_seq_open failed with error -2.
[ERROR] [MIDI]: Initialization failed.
[INFO] [Playlist]: Loading history file: "/opt/retropie/configs/arcade/content_history.lpl".
[INFO] [Playlist]: Loading history file: "/opt/retropie/configs/arcade/content_music_history.lpl".
[INFO] [Playlist]: Loading history file: "/opt/retropie/configs/arcade/content_video_history.lpl".
[INFO] [Playlist]: Loading history file: "/opt/retropie/configs/arcade/content_image_history.lpl".
[INFO] [Playlist]: Loading favorites file: "/opt/retropie/configs/arcade/content_favorites.lpl".
[INFO] [Playlist]: Written to playlist file: "/opt/retropie/configs/arcade/content_history.lpl".
[INFO] [KMS]: New FB: 1280x1024 (stride: 5120).
[INFO] [KMS]: New FB: 1280x1024 (stride: 5120).
[INFO] [Environ]: SET_GEOMETRY: 256x240, Aspect: 0.750.

**Comment by grant2258** [comment]
yes that is the logs we need in the future when something goes wrong. The core version isint displayed in them logs that something that needs adding.

**Comment by KamiLordus** [comment]
coh3002t missing file ?
@kounabi22 do you have this extra file in your romset?

**Comment by grant2258** [comment]
The only thing he needs to do is update the core to 257. Its broke on 256 and that's what he/she is running on retropie.

**Comment by nemo93** [comment]
I didn't realize Ray Crisis was using the same driver as XII Stag. I confirm the issue on **.257** as well. I have changed my own ticket to reflect this. I propose we close that one off and keep the discussion runnning on #429 (tidy).
