### ISSUE TITLE
vivid dolls freeze on start up

### ISSUE THREAD

**Issue by kounabi22** [libretro/mame#420]
vivid dolls freeze on start up (retropie on pi4)

**Comment by grant2258** [comment]
can you please post logs of the games that are not loading

**Comment by MistyDreams** [comment]
its runs super slow on a i7 its not frozen just slow.

**Comment by nemo93** [comment]
@kounabi22 can you please confirm @MistyDreams' claim? Also if you could check the other games relying on the [same driver](http://adb.arcadeitalia.net/lista_mame.php?game_sourcefile=aleck64.cpp&arcade_only=0&current_version=0) to be sure. If you confirm everything is working but slow on RPi then let's close the ticket off. Thanks!

**Comment by kounabi22** [comment]
yes i try two other games that use the same driver doncdoon and kurufev and the game freeze after load.

**Comment by grant2258** [comment]
It runs between 28 and 32 fps and dips lower and higher sometimes  on a Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz so give the pie some extra time to see if it moves before considering it  it broke, as it struggles and takes a while even on a faster cpu.

**Comment by kounabi22** [comment]
well i could try again but even quit buttons dont respont on pi4

**Comment by grant2258** [comment]
It could be systems running maxed out or it could well be another issue give it like 10 minutes to respond  before making judgment on it for sure.

**Comment by nemo93** [comment]
I've tested few games sharing the [same driver](http://adb.arcadeitalia.net/lista_mame.php?game_sourcefile=aleck64.cpp&arcade_only=0&current_version=0) and I do confirm there's no issue. As @grant2258 and @MistyDreams confirmed it's just super slow to the point my RPi was totally maxed out. You have similar issue with any ST-V/Titan games or the more recent 3D games (eg. Virtua Fighter 2, Bloody Roar 2) or the recent Cave games (eg. Mushihime-Sama, Ibara, etc).

There's nothing to be done here. The RPi is simply not powerful enough. I advise closing that ticket off.

**Comment by kounabi22** [comment]
yes st-v games load slow but i can quit the retroarch. 
ok i close it.
