### ISSUE TITLE
[.257] [RPi] black screen issue with several Namco drivers

### ISSUE THREAD

**Issue by nemo93** [libretro/mame#422]
Hi, 

follow-up of #237, as I've found another driver presenting similar issue I decided to create a new ticket.

**Disclaimer**: please note that I'm using **only parent** from a non-merged set. I've triple-checked the roms by hands to be sure nothing is missing from the archive as well as CRC. 

---
Games relying on the [namcona1](https://github.com/libretro/mame/blob/master/src/mame/namco/namcona1.cpp), [namconb1](https://github.com/libretro/mame/blob/master/src/mame/namco/namconb1.cpp) and [namcofl](https://github.com/libretro/mame/blob/master/src/mame/namco/namcofl.cpp) drivers won't get past the initial ROM check and/or will show a black screen right on start. I can't get a specific error message from the log given the core itself is working no problem.

### Games tested using the [namcona1](https://github.com/libretro/mame/blob/master/src/mame/namco/namcona1.cpp) driver:
* fghtatck.7z / [Fighter & Attacker](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=fghtatck) (**NA-1**)
* knckhead.7z / [Knuckle Heads](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=knckhead) (**NA-2**)
* numanath.7z / [Numan Athletics](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=numanath) (**NA-2**)

### Games tested using the [namconb1](https://github.com/libretro/mame/blob/master/src/mame/namco/namconb1.cpp) driver:
* machbrkr.7z / [Mach Breakers](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=machbrkr)
* nebulray.7z / [Nebulas Ray](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=nebulray)
* outfxies.7z / [The Outfoxies](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=outfxies)

### Games tested using the [namcofl](https://github.com/libretro/mame/blob/master/src/mame/namco/namcofl.cpp) driver:
* finalapr.7z / [Final Lap R](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=finalapr)

---
Tested on Raspberry Pi4 on a vanilla Retropie (`4.8.4`). Kernel `5.10.103-v7l+`, 32-bit Raspberry OS in `fKMS mode`. Retroarch is `1.15.0` and the MAME core is `.257`.

```ini
URL: https://github.com/libretro/mame.git
Branch: master
Commit: b8b6d0c8e2b99102fd28b908517c06fed6078bef
```

**Comment by grant2258** [comment]
can confirm on a raspberry pi with libretro core and standalone (both aarch64 builds on 64 bit os) another one that should be included on mame testers as well.

https://github.com/libretro/mame/issues/423#issuecomment-1676433633

@nemo93 tell the raspberry pi people this flag needs added that should close these two issues. I only have one chd so cant really them. 
ps make sure they credit @sonninnos for the fix.

**Comment by nemo93** [comment]
Thanks @grant2258 and @sonninnos as usual for the testing, follow-up and that flag 😃 I've liaised with Retropie maintainers and see how this could be dealt with. If you don't mind I'm leaving all those tickets opened for now. As soon as I'll be able to test and confirm, I'll close them off. Thanks again!

**Comment by grant2258** [comment]
Yes you should confirm yourself since its your issues it should be you closing them. Unfortunately I can do anything about a binary for the retropie I would need to get a different cross compiler setup for the 32 bit and its something they will get too in time.

**Comment by sonninnos** [comment]
Shouldn't we just enable it for all ARM devices then? It actually was there for Android for a commit or two until it got removed due to the build fixing.

**Comment by grant2258** [comment]
Yes should be on all arm devices the makefile works different ways for different platforms. If you have any issues adding it I can talk a look for you. Since you have build bot access and know what your doing there shouldn't be any issues.

**Comment by nemo93** [comment]
I do confirm the reported issue is gone after adding the `-fsigned-char` flag for my device/RPi4. [Thread](https://retropie.org.uk/forum/post/290184) on the Retropie's forum for reference which also contains the updated binary for that device.

Thanks a lot @sonninnos @grant2258!
