### ISSUE TITLE
[.257] can't insert coin and/or pull trigger in various games

### ISSUE THREAD

**Issue by nemo93** [libretro/mame#424]
Hi, 

follow-up of #213 and #415.

**Disclaimer**: please note that I'm using **only parent** from a non-merged set. I've triple-checked the roms by hands to be sure nothing is missing from the archive as well as CRC. 

---
You can't insert coin in some games making these unplayable. Also other games will not detect whenever you pull trigger. I can't tell if the issues are related hence I decided to put everything under the same ticket unless you ask me to do otherwise.

### Games where you can't insert coin:
* airco22b.7z / [Air Combat 22](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=airco22b) ([namco/namcos22.cpp](https://github.com/libretro/mame/blob/master/src/mame/namco/namcos22.cpp))
~* ddcrew.7z / [D. D. Crew](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=ddcrew) ([sega/segas18.cpp](https://github.com/libretro/mame/blob/master/src/mame/sega/segas18.cpp))~
* starswep.7z / [Star Sweep](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=starswep) ([namco/namcos11.cpp](https://github.com/libretro/mame/blob/master/src/mame/namco/namcos11.cpp))
* tokyowar.7z / [Tokyo Wars](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=tokyowar) ([namco/namcos22.cpp](https://github.com/libretro/mame/blob/master/src/mame/namco/namcos22.cpp))

### Games not detecting a trigger pull:
* loffire.7z / [Line of Fire](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=loffire) ([sega/segaxbd.cpp](https://github.com/libretro/mame/blob/master/src/mame/sega/segaxbd.cpp)). During gameplay trigger can't be pulled at all. Other buttons work ok (start, coin, bomb). Please note the trigger does work fine during cutscenes, on title and during gun calibration process. The other games known to run on a [similar board](https://github.com/libretro/mame/blob/master/src/mame/sega/segaxbd.cpp) all work no problem (eg. AB Cop, After Burner, After Burner II, etc).
EDIT: simply calibrate BOTH guns to prevent that issue.

---
Tested on Raspberry Pi4 on a vanilla Retropie (`4.8.4`). Kernel `5.10.103-v7l+`, 32-bit Raspberry OS in `fKMS mode`. Retroarch is `1.15.0` and the MAME core is `.257`.

```ini
URL: https://github.com/libretro/mame.git
Branch: master
Commit: b8b6d0c8e2b99102fd28b908517c06fed6078bef
```

**Comment by MistyDreams** [comment]
what are you using as a controller? I had to clear my cfg file with the input changes if you where using 0251 before i reccomend you do the same

**Comment by nemo93** [comment]
> what are you using as a controller? 

Xbox One over BlueTooth using the Xpadneo driver. Works like a charm either with other MAME games or other emus.

>I had to clear my cfg file with the input changes if you where using 0251 before i reccomend you do the same

Good idea. Yet I always ensure _to clear all_ my directories of any files. Therefore I got neither `.cfg` nor `nvram` when I do my testing. As you said this to prevent any overlap or clash of any kind from an older version.

**Comment by MistyDreams** [comment]
I tested tested the first three they are fine on my x86 machine but Im on 257 not exactly a great comparison using a different version number. If your issue persists into 257 it should be looked into.

**Comment by nemo93** [comment]
Issues confirmed on `.257` as well.

**Comment by MistyDreams** [comment]
To be honest using linux sometimes my controller stops working for no apparent reason but a restart fixes that and I dont think its related to this issue but sure is annoying.

**Comment by grant2258** [comment]
I haven't had time to test the rest but ddcrew shouldn't be on this list, player2 coin works fine, It can be set to individual coin shoots in the dip settings its on common by default. Line of fire I originally thought there was an issue but its fine on libretro and standalone 64 bit arm after calibrating the sites properly. 

airco22b
starswep
tokyowar

Are the only games In this report I have issues on arm64 on both standalone and libretro arm64. Im pretty sure the other two are user fixable ones if the games are setup correctly. The 3 that are failing aren't libretro specific issues and should be posted on mame testers as well as they are upstream issues.

**Comment by grant2258** [comment]
https://github.com/libretro/mame/issues/423#issuecomment-1676433633 fixes the 3 problematic issues.

**Comment by nemo93** [comment]
I do confirm the reported issue is gone after adding the `-fsigned-char` flag for my device/RPi4. [Thread](https://retropie.org.uk/forum/post/290184) on the Retropie's forum for reference which also contains the updated binary for that device.

Thanks a lot @sonninnos @grant2258!

Note: @grant2258 you were right regarding DD Crew and Line of Fire. For DD Crew you have to rely on a specific DIP setting for the coin chute to make it work. Open Mame menu (`TAB` by default), go to DIP Settings and select `Individual` instead of `Common` for the **Coin Chute**. Line of Fire was a matter of calibrating **BOTH** guns for everything to properly run...
