### ISSUE TITLE
[.257] [RPi] Time Crisis ROM check fails

### ISSUE THREAD

**Issue by nemo93** [libretro/mame#425]
Hi, 

follow-up of #347.

**Disclaimer**: please note that I'm using **only parent** from a non-merged set. I've triple-checked the roms by hands to be sure nothing is missing from the archive as well as CRC. 

---
It's a [known issue](https://github.com/mamedev/mame/issues/8492) apparently. The ROM check test always fails at `SUBCPU START WAIT` therefore not allowing the game to start.

![timecris-230731-094740](https://github.com/libretro/mame/assets/8100500/c2d20ef3-b4fa-40d3-bb44-134e81d774f9)

* timecris.7z / [Time Crisis](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=timecris) ([namco/namcos22.cpp](https://github.com/libretro/mame/blob/master/src/mame/namco/namcos22.cpp))

---
Tested on Raspberry Pi4 on a vanilla Retropie (`4.8.4`). Kernel `5.10.103-v7l+`, 32-bit Raspberry OS in `fKMS mode`. Retroarch is `1.15.0` and the MAME core is `.257`.

```ini
URL: https://github.com/libretro/mame.git
Branch: master
Commit: b8b6d0c8e2b99102fd28b908517c06fed6078bef
```

**Comment by StormedBubbles** [comment]
Hey, this is an issue with the Raspberry Pi in every available version of libretro MAME as well as upstream standalone MAME too. It is very confusing to me because the Windows version of lr-mame loaded Time Crisis fine last time I checked (around version .245).

**Comment by StormedBubbles** [comment]
I just checked that this is the same as of lr-mame .257 commit 1ede3ae on Raspberry Pi 4B.

**Comment by nemo93** [comment]
I do confirm the reported issue is gone after adding the `-fsigned-char` flag for my device/RPi4. [Thread](https://retropie.org.uk/forum/post/290184) on the Retropie's forum for reference which also contains the updated binary for that device.

Thanks a lot @sonninnos @grant2258!
