### ISSUE TITLE
Main cpu overclock option problem.

### ISSUE THREAD

**Issue by KamiLordus** [libretro/mame#426]
"Main CPU overclock" is not working properly (tested game Metal Slug 2)
Setting the value to 150, saving in menage cores options and then restarting the game works incorrectly because the game runs just as slow as with the default value.
Changing the value during the game from 150 to default and back to 150 works fine, the game runs noticeably faster. Although after saving the settings (main cpu overclock 150) and restarting the game, it will be slow again.

RA 1.16 
MAME core 257
Windows 11

**Comment by sonninnos** [comment]
Whoops, it was simply doing stuff in wrong order, so it was an easy fix.
