### ISSUE TITLE
Namco system screen misalignment

### ISSUE THREAD

**Issue by lim2222** [libretro/mame#430]
version affected 9f327c70
last working version 1ede3ae1
![gunbalina-230810-062609](https://github.com/libretro/mame/assets/35925370/4d0b55a3-d2f1-4df2-815b-10b7f21669b3)
![knpuzzle-230810-062404](https://github.com/libretro/mame/assets/35925370/1054a612-d7b4-4159-83bc-9579c969a7c8)
![ptblank2-230810-062752](https://github.com/libretro/mame/assets/35925370/72253840-93c8-4e7b-8ffc-db90fc58e108)
![taiko6-230810-063918](https://github.com/libretro/mame/assets/35925370/e6eaaced-bd40-431a-8ca7-95764e22f122)
![tekken-230810-062519](https://github.com/libretro/mame/assets/35925370/0b838c75-bdd1-41cc-995a-079a595a6d99)
![tektagt-230810-062451](https://github.com/libretro/mame/assets/35925370/5f972eb9-1595-49ca-b17a-4eb381c1e0ad)

**Comment by sonninnos** [comment]
I confirmed only `ptblank2` to work, so let me know if others still act up.

**Comment by lim2222** [comment]
Thanks for quick fixes,all become normal as usual.
