### ISSUE TITLE
[Request] Mame menu key binding

### ISSUE THREAD

**Issue by nemo93** [libretro/mame#434]
Hello, I'm using lr-mame on RPi device especially builds for retrogaming. Meaning I don't have a keyboard attached to it, only a (Xbox One) controller. 

Every time I'd like to open the Mame menu to set some DIP switches or key bindings it's a little bit tricky as I never know when I'll be able to get that menu to open :-) Basically I have to hit my Retroarch GUI combo (Select + X) several times before that menu eventually shows up!

**Feature request**: to add a binding in the Retroarch GUI (under the Core Options or Control section perhaps?) allowing users to assign a specific key/button (or a combination) to open the Mame menu (eg. Select + Y). Currently it is assigned to the `TAB` key.

**Bonus**: it would be nice to add a similar binding to the Service key/switch. This would allow easier in-game configuration like with the [Midway boards](http://adb.arcadeitalia.net/lista_mame.php?game_sourcefile=midtunit.cpp&arcade_only=0&current_version=0) (ie. Mortal Kombat 1& 2) which start with a very low sound level.

Thanks!

**Comment by sonninnos** [comment]
Surely you should be able to map it how you wish in the MAME internal menu already?

**Comment by MistyDreams** [comment]
press select + y at the same for the tab menu at the same time for the tab menu that what its set too. Im not sure if the per game mapping throws this setting off i haven't tested because I dont use that option.

**Comment by sonninnos** [comment]
The per game thing changes the RetroPad buttons, so it should change the combo too. I don't think the per game option should even be on by default.

**Comment by MistyDreams** [comment]
I really dont think it should be there at all, a custom input could be done a cleaner way. Its not an option i use anyway @nemo93 just turn that option off and youll get a consistent tab menu.  It would be wise to clear your config files as they will wonky without the remapping the had previously, that's only if youve changed any input settings. 

This is an example of how we should be doing it if its to be done.

https://github.com/mamedev/mame/blob/b877d9c15ecb224cc52e070d7929fc26ac31323e/src/osd/sdl/osdsdl.cpp#L306C1-L423C2

**Comment by nemo93** [comment]
> Surely you should be able to map it how you wish in the MAME internal menu already?

@sonninnos Correct. Yet given how random it is to bring that menu it's a pain to be honest. Also mentioning that internal menu somewhere in RA GUI could serve as a reminder that such menu even exists (eg for new users).

@MistyDreams I don't rely on per-game settings. I'll see if turning off that option you mentioned makes any difference.

Thanks both for your answers. If it's something that can't be easily implemented or simply you don't want to implement, no problem with that :-) Just let me know and I'll close that ticket off (or feel free to do so).

**Comment by MistyDreams** [comment]
@nemo93 the tab menu is mapped to select + y (x on the xbone contoller) by default in the general inputs for the tab menu. Unless its something else I missed that you where asking for. For the service key which one do you mean f2 or 9 ?

If you provide a mapping you would like to which service (There are five service buttons ) I can put a pull request in new mappings can be added if @sonninnos agrees

https://github.com/libretro/mame/blob/b187489b66dff418d326ec2a49e04d1c67ef37a2/src/osd/libretro/retromain.cpp#L335-L361

**Comment by sonninnos** [comment]
Do we really need to add more hard-coded combos when the combo can already be defined manually however one pleases?

Sure we perhaps could add a combo for the first service button, but some need more than one, and defining more than one will get messy quick.. But again it is not a huge problem to solve without them being the default.

> Also mentioning that internal menu somewhere in RA GUI could serve as a reminder that such menu even exists (eg for new users).

It is in the core info, which is pretty much the only place:
![retroarch_2023_08_17_15_05_34_401](https://github.com/libretro/mame/assets/45124675/67cffc67-c00a-4b8b-8a7f-53de1b021afa)

**Comment by MistyDreams** [comment]
I tend to agree on the messy bit, thats only because I have access to a keyboard and dont use only controllers. People on android and other controller only platforms might see things differently and would be appreciative of a service button. The 9 and f2 are the most common needed. I would imagine something like start+select+a for service start+select+b for service1 so you cant accidentally trigger it. I would also suggest start+select+x combo for the tab menu as some might use select + x for the ra menu. I dont use this controller only setup so someone using it could suggest a better option if thats not a good idea.

**Comment by nemo93** [comment]
Thanks @sonninnos again. I didn't see that menu! Anyhow I consider there are already plenty to configure your keys/buttons the way you want. No need to waste more time on that.

EDIT: in fact my issue was due to the fact Retropie comes with a default Select+X setting to open RA GUI (Start+Select closes the current running core). As @MistyDreams pointed out this created conflict. After assigning Service to L3 and Mame Menu to R3 all my problems are gone. Thanks again!
