### ISSUE TITLE
Oriental Legend 2 (PGM2) doesn't work on latest commits

### ISSUE THREAD

**Issue by Kelvfimer** [libretro/mame#436]
Hello

I noticed that Oriental Legend 2 from PGM2 is not working anymore on Mame Retroarch. 

On regular mame it works and on old retroarch MAME 251 it also worked.

It states that it can't find the rom files, but they are there.

[libretro ERROR] ol2_fa.igs036 NOT FOUND (tried in orleg2)
ol2_v104fa.u7 NOT FOUND (tried in orleg2)
ig-a_text.u4 NOT FOUND (tried in orleg2)
ig-a_bgl.u35 NOT FOUND (tried in orleg2)
ig-a_bgh.u36 NOT FOUND (tried in orleg2)
ig-a_bml.u12 NOT FOUND (tried in orleg2)
ig-a_bmh.u16 NOT FOUND (tried in orleg2)
ig-a_cgl.u18 NOT FOUND (tried in orleg2)
ig-a_cgh.u26 NOT FOUND (tried in orleg2)
ig-a_sp.u2 NOT FOUND (tried in orleg2)
xyj2_nvram NOT FOUND (tried in orleg2)

It reproes in Windows PC Retroarch and in Linux Emuelec n2+ retroarch.

Repro is easy only load the 7z or zip file orleg2

Here they are the log files. 

PC Logs
[retroarch.log](https://github.com/libretro/mame/files/12389157/retroarch.log)

Emuelec Linux odroid n2+ logs
[retroarchemuelec.log](https://github.com/libretro/mame/files/12389158/retroarchemuelec.log)

I tested with different orleg2 roms.

thx so much for your support.

**Comment by sonninnos** [comment]
Boots fine here with 0.255 romset.

Edit: Ah, had a look at your log, and pretty sure this game isn't the only one that fails to load with your settings, which skips all essential paths, like the rom path.

**Comment by Kelvfimer** [comment]
yes mame.ini was not right on both. thx for your answer.
