### ISSUE TITLE
Fail compiling last git source in last retropie on pi4.

### ISSUE THREAD

**Issue by jlopezvil** [libretro/mame#437]
Last attempt to compile current git libreto mame ends with this error... 
Archiving libfrontend.a...
make: *** [makefile:1356: linux] Error 2
Removing additional swap
Could not successfully build lr-mame - MAME emulator - MAME (current) port for libretro (/home/pi/RetroPie-Setup/tmp/build/lr-mame/mamearcade_libretro.so not found).
/home/pi

Attached log file

[rps_2023-08-20_211849.log](https://github.com/libretro/mame/files/12395973/rps_2023-08-20_211849.log)

**Comment by sonninnos** [comment]
That final error is not the actual error, but this is:

```
Compiling src/emu/validity.cpp...
../../../../../src/emu/validity.cpp: In function ‘void {anonymous}::validate_integer_semantics()’:
../../../../../src/emu/validity.cpp:179:31: error: static assertion failed: PTR64 flag enabled, but was compiled for 32-bit target

  static_assert(sizeof(void *) == 8, "PTR64 flag enabled, but was compiled for 32-bit target\n");
                ~~~~~~~~~~~~~~~^~~~
make[2]: *** [emu.make:2274: ../../../../libretro/obj/libretro/src/emu/validity.o] Error 1
make[1]: *** [Makefile:76: emu] Error 2
```

So when did it work before? It builds fine on buildbot and on my machine.. Also that gcc version seems awfully old: `GCC 8.3.0 detected`. And there are also a lot of c++ notes and warnings that shouldn't be there.

I have no idea how there could be any 32-bit vs 64-bit shenanigans after running `make clean`, which looks like it is run based on the log.

**Comment by jlopezvil** [comment]
There or four commits ago, with v257, it compiled ok

**Comment by jlopezvil** [comment]
My retro pie is Last on 32bits

**Comment by sonninnos** [comment]
Nothing even remotely related in the last 3-4 commits that could affect that.. Buildbot also builds some 32bit platforms.

**Comment by jlopezvil** [comment]
Maybe was v256. Im not sure of it. But fáil is on log and my retro pie is same on v256 sure was compiled ok

Also my retro pie is 32bits. No idea why there is a Ptr64 Flag....

**Comment by jlopezvil** [comment]
Sorry, also what package must add or update for better compiling?

**Comment by sonninnos** [comment]
Beats me. Any ideas about that PTR64 thing @grant2258 ?

**Comment by jlopezvil** [comment]
Sorry, also what package must add or update for better compiling?

**Comment by grant2258** [comment]
GCC is detecting 32 bits and telling you that you have set 64bits. Youll need to inform the the retro pie folk so adjust the flags appropriately.  I dont use retro pie per but I can tell you from your logs your are using a 64 bit image. I just checked your logs the retropie script is up to date. 

```
RetroPie-Setup version: 4.8.5 (a9602fcb)
System: rpi4 (aarch64) - Raspbian GNU/Linux 10 (buster) - Linux retropie 6.1.41-v8+ #1667 SMP PREEMPT Wed Jul 26 17:59:29 BST 2023 aarch64 GNU/Linux
```

**Comment by jlopezvil** [comment]
My retro pie is 32 bits updated to Last retro pie script... There no exists retro pie 64 bit. And Hardware is rapsberri pi4.

**Comment by jlopezvil** [comment]
What Flag must use in the Script call?

**Comment by jlopezvil** [comment]
Maybe error is in source prebuild code...

**Comment by grant2258** [comment]
To be honest I dont know what retropie is doing I use raspberry pi os 64 bit and cross compile mame on another machine. Mame was compiled a few days ago for retropie here https://github.com/libretro/mame/issues/425#issuecomment-1680293498 its has the fsinged char fix. You'll need to seek help for retropie on there forums about your specific issue and there has been no changes I can see in the last days that would even touches the build. I dont see why your showing as aarch64 in your logs either because thats saying its 64bit.

```
Compiling src/emu/validity.cpp...
../../../../../src/emu/validity.cpp: In function ‘void {anonymous}::validate_integer_semantics()’:
../../../../../src/emu/validity.cpp:179:31: error: static assertion failed: PTR64 flag enabled, but was compiled for 32-bit target
```

Is seems it sets this flag on 64 bit platfroms its something there end that they need to look into.

https://github.com/RetroPie/RetroPie-Setup/blob/a9602fcb4cb2e5e92a673788a2bf68f76ff9d420/scriptmodules/libretrocores/lr-mame.sh#L22C3-L22C44

**Comment by jlopezvil** [comment]
I Ithink error Maybe is in RetroPie setup file lr-mame.sh
Line ... Isplatform "64..."

function _get_params_lr-mame() {
    local params=(OSD=retro RETRO=1 NOWERROR=1 OS=linux TARGETOS=linux CONFIG=libretro NO_USE_MIDI=1 TARGET=mame PYTHON_EXECUTABLE=python3)
    isPlatform "64bit" && params+=(PTR64=1)
    echo "${params[@]}"} 


Is erroneusly detecting plataforma as 64... Maybe processor is but RetroPie is 32bit version

**Comment by grant2258** [comment]
Yes that was the code i linked to above change PTR64=1 to PTR64=0 for now if you want to compile. Im not sure if you need to recompile from start when changing this. If you have issues after compiling just do a clean compile. Try asking cmitu at retropie he is one of the more knowledgeable devs there and very approachable, when you point out issues.

**Comment by jlopezvil** [comment]
same error with PTR64=0

**Comment by jlopezvil** [comment]
[rps_2023-08-22_100623.log](https://github.com/libretro/mame/files/12410477/rps_2023-08-22_100623.log)

Here error is more clever ,,,  And flag is PTR64=0 at start .. But after it detects is PTR64=1 .. Maybe in prebuild o preprocess of compile?

**Comment by grant2258** [comment]
It really not on us too fix this issue. I could fix it but its up to retropie how they compile there cores. They do things a certain way. There is varies ways to make the set the ptr64 the makefile itself goes through some logic to set it and so does the lua scripts. If you want to debug it set VERBOSE=1 youll see what its calling and why its setting following the code. The retropie guys know what they are doing. If your not cleaning the previous BUILD you should also use REGENIE=1 else it uses the old makefiles

**Comment by jlopezvil** [comment]
Please, say me how can i get to compile it, please....

**Comment by grant2258** [comment]
I just downloaded and installed buster it took a long time to update and its not setting PTR64 it compiles fine with no issues.  I got the image here https://github.com/RetroPie/RetroPie-Setup/releases/download/4.8/retropie-buster-4.8-rpi4_400.img.gz what image are you using?

**Comment by grant2258** [comment]
If you installed bullseye 64 bit lite change this 

https://github.com/RetroPie/RetroPie-Setup/blob/a9602fcb4cb2e5e92a673788a2bf68f76ff9d420/scriptmodules/libretrocores/lr-mame.sh#L21

too
```
local params=(OSD=retro RETRO=1 NOWERROR=1 TARGETOS=linux CONFIG=libretro NO_USE_MIDI=1 TARGET=mame PYTHON_EXECUTABLE=python3 VERBOSE=1 NOASM=1 PLATFORM=arm REGENIE=1)
```
Also change PTR64=1 TO PTR64=0 in the line below it. (line 22)

**Comment by jlopezvil** [comment]
IM using 
RetroPie-Setup version: 4.8.5 (a9602fcb)
System: rpi4 (aarch64) - Raspbian GNU/Linux 10 (buster) - Linux retropie 6.1.41-v8+ #1667 SMP PREEMPT Wed Jul 26 17:59:29 BST 2023 aarch64 GNU/Linux

Retropie 4,8 with updates ....

**Comment by grant2258** [comment]
Log started at: Tue 22 Aug 22:49:07 BST 2023

RetroPie-Setup version: 4.8.5 (a9602fcb)
System: rpi4 (armv7l) - Raspbian GNU/Linux 10 (buster) - Linux retropie 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux

With full updates and fresh install your on kernel 6.1 and a with 64bit architecture. Your using bullseye or some other distro

**Comment by grant2258** [comment]
@sonninnos feel free to close at any point the user image isint the the retropie image. @jlopezvil youll need to ask the retropie people why you have a 6.1 kernel on buster 32bit that claims its 64bit. Installing the right image for retropie is something the forums can help you with.

**Comment by jlopezvil** [comment]
Issue was solved reinstaling kernel .. Kernel was the problem .. 
Now is compiling ....

> How to get back to safety
If you have done an rpi-update and things are not working as you wish, if your Raspberry Pi is still bootable you can return to the stable release using:

sudo apt-get update
sudo apt install --reinstall libraspberrypi0 libraspberrypi-{bin,dev,doc} raspberrypi-bootloader raspberrypi-kernel
You will need to reboot your Raspberry Pi for these changes to take effect.

https://www.raspberrypi.com/documentation/computers/os.html#using-apt


@grant2258 I have seen in https://files.retropie.org.uk/images/weekly/  there is bullseye image for rpi4. It is safe to use .. It works with emus? Maybe better stay at buster?

**Comment by grant2258** [comment]
> sudo apt-get update
> sudo apt install --reinstall libraspberrypi0 libraspberrypi-{bin,dev,doc} raspberrypi-bootloader raspberrypi-kernel
> You will need to reboot your Raspberry Pi for these changes to take effect.

This is 100% the wrong way to fix a retropie issue. The scripts customizes the distro you choose to work as it should with retropie. I dont use retropie and only tested the buster stable image when you presented this issue. The image files you linked are beta testing images.  Im not sure how well they work, the forum should have posts and updates about the beta. Retropie is the best place to ask. From what little reading I done it appears like bullseye 64 bit is being made to run with the kernel set to 32 bit mode.
