### ISSUE TITLE
[.257] [RPi] `konami/tmnt2.cpp` driver - not working

### ISSUE THREAD

**Issue by nemo93** [libretro/mame#439]
Hi, 

**Disclaimer**: please note that I'm using **only parent** from a non-merged set. I've triple-checked the roms by hands to be sure nothing is missing from the archive as well as CRC. 

---
Games relying on the [`konami/tmnt2.cpp`](https://github.com/libretro/mame/blob/master/src/mame/konami/tmnt2.cpp) driver will cause **lr-mame** to quit right on start. This despite having the "magic" flag added (b187489b66dff418d326ec2a49e04d1c67ef37a2). 

Thus far and since the addition of that flag everything tested has been running great. I'll keep on testing but seems that it's one of a few or perhaps the _only_ driver having issue.

One of my favorite game of all time is part of the bunch, sadly (Turtles in Time!) :-( **Please note all those games were working fine without `-fsigned-char`.**

Just a few games sharing that [driver](http://adb.arcadeitalia.net/lista_mame.php?game_sourcefile=tmnt2.cpp&arcade_only=0&current_version=0):

* lgtnfght.7z / [Lightning Fighters](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=lgtnfght)
* ssriders.7z / [Sunset Riders](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=ssriders)
* tmnt2.7z / [Teenage Mutant Ninja Turtles - Turtles in Time](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=tmnt2)

---
Tested on Raspberry Pi4 on a vanilla Retropie (`4.8.5`). Kernel `5.10.103-v7l+`, 32-bit Raspberry OS in `fKMS mode`. Retroarch is `1.15.0` and the MAME core is `.257` compiled with [`-fsigned-char`](https://github.com/libretro/mame/commit/b187489b66dff418d326ec2a49e04d1c67ef37a2). The exact binary used could be downloaded from [that post](https://retropie.org.uk/forum/post/290179).

---

[punkshot.txt](https://github.com/libretro/mame/files/12444910/punkshot.txt)
[lgtnfght.txt](https://github.com/libretro/mame/files/12444911/lgtnfght.txt)
[ssridersubc.txt](https://github.com/libretro/mame/files/12444912/ssridersubc.txt)

**Comment by grant2258** [comment]
Ill can cross compile a version for you to try, it will be based on the stable buster image in the homepage raspberry pi 400/4 md5: b5daa6e7660a99c246966f3f09b4014b fully updated from https://retropie.org.uk/download/. Thats the only sysroot I have for retropie. you using the stable image. I think the issue is the way its compiled can only confirm that if you test a  build I can make for you.

edit: @nemo93 This will remain up for 31 days. Its also a full build so you can run consoles or computers if you want to. 
https://anonymfile.com/nq8zW/mame0257-libretro-buster-arm32.zip

**Comment by sonninnos** [comment]
Log might still help to show where it crashes even if no proper debug build log is possible.

**Comment by grant2258** [comment]
op stated the log was empty. Ill need to compile the full version again I archived the wrong one and done a make clean the one in the download only has the tmnt2 driver.  It boots the game with no issues. Ill build mame0257 and mame0258 beyond that retropie will need to fix there own builds. @nemo93 took the time to test things, I dont mind cross compiling for now.

**Comment by sonninnos** [comment]
It can't possibly crash so soon that there is nothing in it..

**Comment by grant2258** [comment]
No idea I use my own binaries so I know what im working with. I don't have any issues with the one I compiled though.

**Comment by kadireksi** [comment]
Same problem also exists on android build.
Here is the log i have:

Using old --libretro behavior. Setting libretro_directory to "/data/user/0/com.retroarch.aarch64/cores/" instead.
RetroArch 1.16.0 (Git 6733d6d)
=== Build =======================================
Capabilities: ASIMD 
[INFO] Version: 1.16.0
[INFO] Git: 6733d6d
[INFO] Built: Aug 11 2023
[INFO] =================================================
[Input]: Found input driver: "android".
[Environ]: SET_PIXEL_FORMAT: RGB565.
[Core]: Version of libretro API: 1, Compiled against API: 1
[Core]: Geometry: 320x240, Aspect: 1.333, FPS: 60.00, Sample rate: 48000.00 Hz.
[Audio]: Set audio input rate to: 48000.00 Hz.
[Video]: Set video size to: 960x720.
[Video]: Starting threaded video driver..
Android EGL: GLES version = 2.
[EGL] Falling back to eglGetDisplay
[EGL]: EGL version: 1.4
[GL]: Found GL context: "egl_android".
[GL]: Detecting screen resolution: 0x0.
[EGL]: Current context: 0x6ee0862400.
[GL]: Vendor: ARM, Renderer: Mali-G72.
[GL]: Version: OpenGL ES 3.2 v1.r38p1-01bet0-mbs2v41_0.49c562ebe5faf1a47d2b8e7043cf01b0.
[GL]: Using resolution 810x1734.
[GL]: Default shader backend found: glsl.
[Shader driver]: Using GLSL shader backend.
[GL]: Stock GLSL shaders will be used.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GL]: Using 4 textures.
[GL]: Loaded 1 program(s).
[Joypad]: Found joypad driver: "android".
[Video]: Found display server: "android".
[OpenSL]: Requested audio latency: 128 ms.
[OpenSL]: Setting audio latency: Block size = 768, Blocks = 32, Total = 24576 ...
[Audio]: Started synchronous audio driver.
[Display]: Found display driver: "gl".
[Playlist]: Loading history file: "/storage/emulated/0/Android/data/com.retroarch.aarch64/files/content_history.lpl".
[Playlist]: Loading history file: "/storage/emulated/0/Android/data/com.retroarch.aarch64/files/content_music_history.lpl".
[Playlist]: Loading history file: "/storage/emulated/0/Android/data/com.retroarch.aarch64/files/content_image_history.lpl".
[Playlist]: Loading favorites file: "/storage/emulated/0/Android/data/com.retroarch.aarch64/files/content_favorites.lpl".
[Core]: Using content: "/storage/emulated/0/RetroArch/system/mame/roms/favori/ssriders.zip".
[Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[Core]: Unloading core..
[Core]: Unloading core symbols..
Threaded video stats: Frames pushed: 1373, Frames dropped: 0.
RetroArch 1.16.0 (Git 6733d6d)
=== Build =======================================
Capabilities: ASIMD 
[INFO] Version: 1.16.0
[INFO] Git: 6733d6d
[INFO] Built: Aug 11 2023
[INFO] =================================================
[Input]: Found input driver: "android".
[Core]: Loading dynamic libretro core from: "/data/user/0/com.retroarch.aarch64/cores/mamearcade_libretro_android.so"
[Environ]: SET_VARIABLES.
[Environ]: SET_CONTROLLER_INFO.
[Environ]: SET_SUPPORT_NO_GAME: yes.
[Overrides]: Redirecting save file to "/storage/emulated/0/RetroArch/saves/ssriders.srm".
[Overrides]: Redirecting save state to "/storage/emulated/0/RetroArch/states/ssriders.state".
[Environ]: GET_LOG_INTERFACE.
[Environ]: SYSTEM_DIRECTORY: "/storage/emulated/0/RetroArch/system".
[Environ]: CORE_ASSETS_DIRECTORY: "/storage/emulated/0/RetroArch/downloads".
[Environ]: GET_SAVE_DIRECTORY.
[Environ]: SET_PIXEL_FORMAT: XRGB8888.
[Environ]: SET_INPUT_DESCRIPTORS:
[Environ]: SET_KEYBOARD_CALLBACK.
[Content]: Content loading skipped. Implementation will load it on its own.
Starting game: "/storage/emulated/0/RetroArch/system/mame/roms/favori/ssriders.zip"
Driver not found: ssriders
System not found: favori
[Environ]: SET_ROTATION: 0
Unknown system 'ssriders'

"ssriders" approximately matches the following
supported machines (best match first):

sraider           Space Raider                                           (Universal, 1982)
strider           Strider (USA, B-Board 89624B-2)                        (Capcom, 1989)
raiders           Raiders                                                (Century Electronics, 1983)
rriders           Ring Riders (Software version v2.2)                    (Gaelco, 2004)
sstriker          Sorcer Striker                                         (Raizing, 1993)
shtrider          Shot Rider                                             (Seibu Kaihatsu, 1985)
spcrider          Space Riders                                           (Atari, 1978)
strider2          Strider 2 (Euro 991213)                                (Capcom, 1999)
striderj          Strider Hiryu (Japan)                                  (Capcom, 1989)
sstrikerk         Sorcer Striker (Korea)                                 (Raizing (Unite Trading license), 1993)
sidebs            Side by Side (Ver 2.7 J)                               (Taito, 1996)
gpriders          GP Rider (World, FD1094 317-0163)                      (Sega, 1990)
raiders5          Raiders5                                               (UPL, 1985)
ridersrf          Rider's Surf                                           (JocMatic, 1986)
ssi               Super Space Invaders '91 (World, revised code, Rev 1)  (Taito Corporation Japan, 1990)
shtridera         Shot Rider (Sigma license)                             (Seibu Kaihatsu (Sigma license), 1984)
[Content]: Failed to load content
[Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[Core]: Unloading core..
[Core]: Unloading core symbols..
[Core]: Saved core options file to "/storage/emulated/0/RetroArch/config/MAME/MAME.opt".
[Environ]: SET_PIXEL_FORMAT: RGB565.
[Core]: Version of libretro API: 1, Compiled against API: 1
[Core]: Geometry: 320x240, Aspect: 1.333, FPS: 60.00, Sample rate: 48000.00 Hz.
[Audio]: Set audio input rate to: 48000.00 Hz.
[Video]: Set video size to: 960x720.
[Video]: Starting threaded video driver..
Android EGL: GLES version = 2.
[EGL] Falling back to eglGetDisplay
[EGL]: EGL version: 1.4
[GL]: Found GL context: "egl_android".
[GL]: Detecting screen resolution: 0x0.
[EGL]: Current context: 0x6ed5b1d680.
[GL]: Vendor: ARM, Renderer: Mali-G72.
[GL]: Version: OpenGL ES 3.2 v1.r38p1-01bet0-mbs2v41_0.49c562ebe5faf1a47d2b8e7043cf01b0.
[GL]: Using resolution 810x1734.
[GL]: Default shader backend found: glsl.
[Shader driver]: Using GLSL shader backend.
[GL]: Stock GLSL shaders will be used.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GL]: Using 4 textures.
[GL]: Loaded 1 program(s).
[Joypad]: Found joypad driver: "android".
[Video]: Found display server: "android".
[OpenSL]: Requested audio latency: 128 ms.
[OpenSL]: Setting audio latency: Block size = 768, Blocks = 32, Total = 24576 ...
[Audio]: Started synchronous audio driver.
[Display]: Found display driver: "gl".
[Playlist]: Loading history file: "/storage/emulated/0/Android/data/com.retroarch.aarch64/files/content_history.lpl".
[Playlist]: Loading history file: "/storage/emulated/0/Android/data/com.retroarch.aarch64/files/content_music_history.lpl".
[Playlist]: Loading history file: "/storage/emulated/0/Android/data/com.retroarch.aarch64/files/content_image_history.lpl".
[Playlist]: Loading favorites file: "/storage/emulated/0/Android/data/com.retroarch.aarch64/files/content_favorites.lpl".
[Config]: Saved new config to "/storage/emulated/0/Android/data/com.retroarch.aarch64/files/retroarch.cfg".
[Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[Core]: Unloading core..
[Core]: Unloading core symbols..
Threaded video stats: Frames pushed: 124, Frames dropped: 0.

**Comment by kadireksi** [comment]
And in addition the latest build of mame and mess core does not start empty (launching without any content), the previous build was launching internal mame ui successfully.

**Comment by sonninnos** [comment]
That can't possibly be the same thing. That log does not segfault, and it says "Unknown system 'ssriders'" as if it isn't built in, even though it should very well be. Also I can launch fine without content.

**Comment by grant2258** [comment]
@nemo93 here is the full build. https://anonymfile.com/PoYPd/mame0257-libretrobuster-arm32.zip details in the readme. I have no issues on retropie with this build or raspberry os 64 bit with tmnt2 or ssriders @sonninnos  it might be a good idea to add the mame version and git info to see if people are using outdated cores in the logs.

**Comment by kadireksi** [comment]
![Screenshot_20230826_011425_RetroArch (AArch64)](https://github.com/libretro/mame/assets/3360268/94da402d-c0d3-4444-8b78-69fac6334e55)

Here is a part of the log when i start the mame core without content (latest Android build):

Starting game from command line: "��t�n"
Parse path failed: "��t�n"
Parse systemname failed: "��t�n"
Game not found: "��t�n"
Driver not found: "��t�n"

**Comment by sonninnos** [comment]
Thanks, and whoops, it does not manifest in Windows, but luckily does when running through `gdb`. My bad, will fix soon.

**Comment by kadireksi** [comment]
Thanks, and btw huge thanks for your great efforts

**Comment by grant2258** [comment]
@kadireksi this does seem like a separate issue. It seems mame is getting confused. Can you boot with another game and turn enable softlist off, and also turn off soflist automatic media type. That will probably patch you up for now.

**Comment by sonninnos** [comment]
Ok, I fixed the empty garbage path thing, and also fixed fps from dropping to half when pausing or launching without content.

**Comment by kadireksi** [comment]
@sonninnos 
thanks, mame and mess ui launching fine again now.

@grant2258 
Disabled software lists and automatic media type but nothing changed, other games load fine from Playlist and internal mame ui( both software list enabled or disabled).
ssriders / [Sunset Riders]
tmnt2 / [Teenage Mutant Ninja Turtles - Turtles in Time]
don't even show in mame ui available list.
Thanks.

**Comment by sonninnos** [comment]
It simply appears that `tmnt2.cpp` is not included in `arcade.flt`, which applies to Android only since it is split to "Arcade" and "MESS".

Edit: Ok, pushed it after confirming adding it did the job with arcade subtarget.

**Comment by nemo93** [comment]
All, thanks as usual for jumping in. Truly appreciated! My original post was incomplete and just wrong at various levels. I've edited it accordingly as well as providing some logs. Clearly my current binary didn't know anything about the `tmnt2` driver as highlighted below (same with the other games relying on that driver):

```
[libretro ERROR] Driver not found: lgtnfght
```

@sonninnos: thanks again. I believe this will do the trick. I'll get my hands on a new binary and confirm it works prior to closing that ticket off.

@grant2258: thanks too. I've tried with your binary. The `tmnt2` games do work yet any other games tested from any other drivers do not \o/ Similar as above that binary doesn't recognize the drivers tested...

[battlera.txt](https://github.com/libretro/mame/files/12444937/battlera.txt)
[btlkroad.txt](https://github.com/libretro/mame/files/12444938/btlkroad.txt)

**Comment by kadireksi** [comment]
@sonninnos 
Thank you, downloaded the new mame core from artifacts and tested ssriders and tmnt2, they both show in the ui and run well :)

**Comment by grant2258** [comment]
nice work @sonninnos was a multiple issue confusion thing going on there. @nemo93 here is the latest fixes since i posted the last binary. Its still the full build though. @nemo93 none of this issue is to do with the- fsigned  flag in case you 
are wondering.

https://anonymfile.com/56eXg/mame0257-libretrobuster-arm32.zip

> @grant2258: thanks too. I've tried with your binary. The `tmnt2` games do work yet any other games tested from any other drivers do not \o/ Similar as above that binary doesn't recognize the drivers tested...

All the links are different you probably just downloaded the first one that only had tmnt2.cpp use the latest links provided they are all different

**Comment by grant2258** [comment]
> It simply appears that `tmnt2.cpp` is not included in `arcade.flt`, which applies to Android only since it is split to "Arcade" and "MESS".

Make sense on the retro pi that compiles the arcade build as well, I compile the full version. I looks like a little regression made its way in with the path changes that you fixed up promptly. The thing that threw me was no log seemed like a completely different issue.

**Comment by nemo93** [comment]
Closing as the issue is now resolved thanks to the latest commit. Thanks again all for your help and assistance as usual. 

For the record an updated binary for Pi4/Retropie (32bit - arcade only) can be found [here](https://retropie.org.uk/forum/post/290364).

**Comment by grant2258** [comment]
new build for mame0258 libretro for vanilla buster retropie stable image https://anonymfile.com/3Dk/mame0258-libretrobuster-arm32.zip no idea why these links go down will need to look for a reliable upload site. Seems like the older links are gone. Ive contacted the site to see whats going on. Will see if I can fine anything more reliable, works out else ill just upload it to my github release page.
