### ISSUE TITLE
[.257][Android] vertical games unwanted rotation 

### ISSUE THREAD

**Issue by kadireksi** [libretro/mame#440]
Hi,
When i start the vertical games from playlist they start normal according to phone's rotation;
![Screenshot_20230826_200101_RetroArch (AArch64)](https://github.com/libretro/mame/assets/3360268/6532ad1c-8344-4bc5-be58-a5b5561910ed)

But when i start the same games from mame ui the games start rotated( also mame ui rotates).
![Screenshot_20230826_200149_RetroArch (AArch64)](https://github.com/libretro/mame/assets/3360268/03b2f6f9-e8ff-45c8-8e4e-de8fc51798c5)
![Screenshot_20230826_200212_RetroArch (AArch64)](https://github.com/libretro/mame/assets/3360268/0333692e-dee2-4279-a9d0-b9c61c3d6336)

I couldn't see any differences in the log files but if you want i can provide. 

Thanks.

**Comment by sonninnos** [comment]
Yep, "libretro" rotation can't know how to rotate, since MAME internal launching skips that part, so you must use the "internal" rotation. Not platform related. Maybe it could and should be forced in that case.

**Comment by kadireksi** [comment]
Tried internal rotation after clearing all configuration files for a fresh start, vertical games still start rotated, when i change rotation from mame ui the game rotates to the right direction but mame ui still stays rotated wrong , if this is what expected i will close the issue.

Thanks

**Comment by sonninnos** [comment]
Yes, rotating internally does not rotate the internal UI. And you should not need to touch that internal rotation at all when using "internal" core option mode.

I can change games via the internal menu just fine regardless of the starting rotation as long as the core option is in "internal" mode. Menu and games are always rotated correctly. And the core option does not apply on-the-fly.

**Comment by kadireksi** [comment]
Ok, closing the issue 

Thanks again
