### ISSUE TITLE
Touchscreen lightgun doesn't work properly on Android 0.258 version

### ISSUE THREAD

**Issue by PantaRei1983** [libretro/mame#442]
I tried various games (Point Blank series, Bang!, Zero Point, Steel Gunner etc.) on two android smartphones: Xiaomi MI 11 and old Redmi Note 5... Lightgun on touchscreen mode doesn't work properly on last 0.258 version (maybe related to new core v2 options?).

On 0.257 and older version touchscreen lightgun works great.

**Comment by sonninnos** [comment]
The core option update didn't change any existing configs though, at least I didn't notice. And no input code was changed.

Edit: LOL found the typo, fix coming asap.
