### ISSUE TITLE
[Features request] some ideas to improve mame core.

### ISSUE THREAD

**Issue by KamiLordus** [libretro/mame#443]
1. I noticed that "Automatic load fast foward", a new mame core option, has a short description of how it works.
Is it possible to add such a description for other options?
![Zrzut ekranu 2023-09-02 191315](https://github.com/libretro/mame/assets/123302593/18a1da28-c54b-464e-970f-3316863ec9b3)

2. If possible, add a bios change option for a particular game, without having to edit the files.

3. In racing games, we have a gear shift indicator. At standard image resolution, the pointer is rendered at a very low resolution. Is it possible to increase the resolution for this screen element?
![Zrzut ekranu 2023-09-02 190107](https://github.com/libretro/mame/assets/123302593/d42a21e1-71a4-4efa-a0e7-87f7229bc515)

**Comment by sonninnos** [comment]
1. Of course it is possible to add sublabels to any option now. I did not feel it was my job to come up with something for every option at once.
2. Isn't that possible in the MAME internal menu already depending on the machine?
3. The only way is to not use the native resolution by using alternate renderer at a higher fixed resolution, which of course has its own problems. Maybe it still could be hacked to be at a certain size that would stay readable though..

**Comment by KamiLordus** [comment]
1. There is no rush, but it would be nice to add more descriptions over time :)
2. Yes, but the bios change in this menu is not saved permanently. The next time you start the game, we have the default bios. Only editing mame.ini changes the bios permanently.
It's not a huge problem, but it would be a good idea to add this capability someday. At the core of FB Neo, this is a nice option.
3. Unfortunately, I expected this. Higher resolution looks bad for shaders. FB Neo resigned from this indicator and replaced it with another one. But it's probably not the best solution either.
