### ISSUE TITLE
Compile options...

### ISSUE THREAD

**Issue by jlopezvil** [libretro/mame#445]
About last commit from @sonninnos  ..   https://github.com/libretro/mame/commit/861cee072de04a9b6f24b91da72c9c6a97e66346

Id like to know what will be the option to compile only arcade sources as mentions the commits ... 

Its only with SUBTARGET = arcade ?

**Comment by sonninnos** [comment]
Yes, the method is the same as it has always been building for Android separately. Only the list changed. Look in `.gitlab-ci.yml`.
