### ISSUE TITLE
Unable to type many keys in MAME 0.258 core and RetroArch 1.16.0

### ISSUE THREAD

**Issue by n6il** [libretro/mame#449]
I have found that in the latest MAME 0.258 core and RetroArch 1.16.0 I am completely unable to type many keys no matter what MAME is doing.  Here is a recipe for reproducing the issue:

1. For example, load any computer core in MAME such as c64, apple2ep, coco3, etc.  
2. Enable Game focus mode but the issue happens even when Game Focus is disabled.
3. Attempt to type the following, none of which work: `.`(Period) or `;`(Semi-Colon)
4. Enable MAME Controls (if remapped type the remapped version)
5. Press TAB to bring up MAME menu (if remapped type the remapped version)
6. Go to File Manager
7. Select any available cartridge, tape, or disk
8. Try typing the following, none of which work: `.`(Period)  `;`(Semi-Colon) `{`(Left Brace) `}` (Right Brace)
9. Press `Esc` a few times to go back to the MAME menu
10. Go to Input Settings
11. Input Assignments (this system)
12. Scroll down to `. >`(Period/Greater Than) - Note that the default says `n/a` 
13. Scroll down to `; :`(Semi-Colon/Colon) - Note the default says `.`(Period)  - (c64 `:`(Colon) is incorrectly mapped to `.`(Period))

This demonstrates that things are strangely mapped.  If you attempt to correct the Period or Semi-Colon keys, you will find that you are unable to type them.  If you scroll around through all the MAME input settings, nothing else is mapped to Period or Semi-Colon.  If you scroll around through the RetroArch menus, you will find the same, nothing else is mapped to Period or Semi-Colon.

I have 1.16.0 installed both on my M1 Pro MacBook Pro and on my M1 iPad Air and I have the same problem on both platforms.
It doesn't seem to matter which roms I run inside of MAME either.

**Comment by sonninnos** [comment]
Did those keys ever work in earlier versions? Indeed those keys work fine in other cores such as VICE, and this core uses the exact same libretro keyboard event callback, so something is just a bit off with the default keyboard mapping in the core.

**Comment by n6il** [comment]
> Did those keys ever work in earlier versions? Indeed those keys work fine in other cores such as VICE, and this core uses the exact same libretro keyboard event callback, so something is just a bit off with the default keyboard mapping in the core.

Yes, I tried VICE and DOSbox, and both seem to be working as expected.

**Comment by n6il** [comment]
> Did those keys ever work in earlier versions? Indeed those keys work fine in other cores such as VICE, and this core uses the exact same libretro keyboard event callback, so something is just a bit off with the default keyboard mapping in the core.

MAME 2003 seems to work correctly, can go to the Input panel and typing `.;{} `works
MAME 2010 doesn't seem to work.

**Comment by sonninnos** [comment]
Okeydoke, I made sure all keys can be pressed in C64. Let me know if I missed something.

**Comment by n6il** [comment]
I thoroughly tested this using the `ct486` "PC/AT 486 with CS4031 chipset"  PC emulation and running the program called CheckIt.  Almost all of the keys registered in CheckIt's keyboard test.  The two keys which did not register for me were `Insert` and `Num Lock`, I think you should confirm this.  I ran this test on a Mac with an external standard PC 104 keyboard. I do know that the Mac keyboard might send different keys.  `Print Screen` sends `F13`, `Scroll Lock` sends `F14` and `Break` sends `F15` - but that's on my end I can remap those keys so the emulation sees them properly.  More concerned about `Insert` and `Num Lock` which I can't type with this setup. If it works for you then it could again be on my end.

I'm attaching the bios and a hard disk image in case you wish to repeat my test.  Just like on a real PC You'll need to insert the hard drive, reboot, and go into the bios to set or detect the HD (It's type 14), then it should boot MS-DOS and you can run CheckIt and run the keyboard test.
[ct486.zip](https://github.com/libretro/mame/files/12592254/ct486.zip)
[atide14t40mb-msdos5_chd.zip](https://github.com/libretro/mame/files/12592261/atide14t40mb-msdos5_chd.zip)

**Comment by sonninnos** [comment]
Hmm, both Insert and NumLock are working here. This menu is great for testing:
![retroarch_2023_09_13_06_31_08_059](https://github.com/libretro/mame/assets/45124675/edb6fdce-9a99-419b-a45a-059796190372)

**Comment by n6il** [comment]
I figured out what's going on... and it's a Mac thing.

Attaching a picture, the standard PC104 kb on top and an Apple Extended USB keyboard below:

Print Screen -> F13  (When I press Print Screen on the PC104KB attached to the Mac, the mac reads it as F13)
Scroll Lock -> F14
Break -> F15
Insert -> Help
Num Lock -> Clear

MAME is can see the F keys up to F15 but not F16, Help or Clear -- I would never expect MAME to see those keys anyway.

Thanks much fixing the original issue for double checking to make sure.

![IMG_8090](https://github.com/libretro/mame/assets/8146869/c2686929-7d89-4449-88c1-772b822d1cd4)

**Comment by sonninnos** [comment]
Ok, great. Then I guess it should be the job of the frontend to send proper keys with that particular platform. Or maybe this core could read both. But that would mean doing it for all cores..

**Comment by sonninnos** [comment]
Unfortunately adding the missing `RETROK_HELP` and `RETROK_CLEAR` to this core as duplicates (for example PUAE does this with Insert, which just happens to be Help in Amiga), they will replace Insert and NumLock respectively, since they must use the same internal MAME ids `ITEM_ID_INSERT` and `ITEM_ID_NUMLOCK`..
