### ISSUE TITLE
Guardian Force Doesn't Work (Works in Standalone 0.191)

### ISSUE THREAD

**Issue by Awakened0** [libretro/mame#45]
The 0.191 update should have fixed this game, but it's still getting stuck on a black screen after the title screen on the latest nightly build. I tested 0.191 stand alone and it works there.

Also, in RetroArch's menu, it still says 0.190.

Cave games like Ibara and Deathsmiles don't crackle anymore with hard sync frames 0 :D

**Comment by r-type** [comment]
it works fine with libretro mame 0.191 for linux , and mame in-game menu says 0.191

**Comment by Awakened0** [comment]
Ahh, must be a build problem then. The buildbot built the Win64 core earlier today, so I assumed it built 0.191.

**Comment by r-type** [comment]
yes your are right , it seem it's the 0.190 in the windows x86_64 build!
![mamewin](https://user-images.githubusercontent.com/3614417/32078190-50e5be16-baa6-11e7-889b-26068a607ac5.png)

**Comment by Awakened0** [comment]
I can't get it to build in msys2:

```
collect2.exe: error: ld returned 1 exit status
make[3]: *** [mamearcade.make:507: ../../../../../mamearcade_libretro.dll] Error 1
make[2]: *** [Makefile:391: mamearcade] Error 2
make[2]: Leaving directory '/home/user/mame/build/projects/retro/mamearcade/gmake-mingw64-gcc'
make[1]: *** [makefile:996: windows_x64] Error 2
make[1]: Leaving directory '/home/user/mame'
make: *** [Makefile.libretro:172: build] Error 2
```

**Comment by r-type** [comment]
seem all platform missing  osd_setup_osd_specific_emu_options(emu_options&) undefined ref then build failed.  So not sure why the linux build fine.

http://p.0bl.net/76631

**Comment by r-type** [comment]
https://github.com/mamedev/mame/commit/3f144b28611d1e5be616511d9fe557a583c5ddbc#diff-7dce5727574b98612651315fb5f3c2ba

@Awakened0
 https://github.com/libretro/mame/commit/578bff00eb4d2bbf01682b4563c681f09a83da03
wait and see if it build fine with that.

**Comment by Awakened0** [comment]
I got it to build now. It shows 0.191, the cave games are much faster than before when I unlock the framerate and Guardian Force works.

Thanks as always for fixing MAME build issues, @r-type !
