### ISSUE TITLE
Modifier keys don't register properly in MAME OSD/Menus MAME 0.258/RetroArch 1.16.0

### ISSUE THREAD

**Issue by n6il** [libretro/mame#451]
Here is another keyboard related issue. In the MAME OSD/Menus the modifier keys (Shift/Ctrl/Alt) don't work properly.  Take Shift for example.  Instead of modifying the next input to upper case or symbols, it prints a high-bit character along with the unshifted character instead.

1. Load any computer core in MAME such as c64, apple2ep, coco3, etc.
2. Enable Game focus mode but the issue happens even when Game Focus is disabled.
4. Enable MAME Controls (if remapped type the remapped version)
5. Press TAB to bring up MAME menu (if remapped type the remapped version)
6. Go to File Manager
7. Select any available cartridge, tape, or disk
8. Try to type something with capital letters: Shift-B should type `B` but prints `Îb` instead
9. Try to type something with symbols (Shift-3 should type `#` but types `Î3`, Shift-Comma should type `<` but types `Î,`)

Please Note: This issue is in the MAME Menu/OSD only. The actual emulated machines seem to get (almost) all the key presses properly.  I thoroughly tested the keyboard input on `ct486` MAME emulation.

I have 1.16.0 and latest MAME installed both on my M1 Pro MacBook Pro and on my M1 iPad Air and I have the same problem on both platforms.

**Comment by n6il** [comment]
I've tested this on Linux, iOS, and macOS all with the same result. This issue does not happen with running mame directly on Linux or macOS, so it is definitely something wrong in the libretro version of mame.

**Comment by n6il** [comment]
@sonninnos There seems to be a regression here, both in the stable 1.19.1 and 2024-04-05 nightly `eea93942`.  Typing shift/control/alt keys results in the strange characters coming up again.

**Comment by sonninnos** [comment]
Still works fine here.

**Comment by n6il** [comment]
> Still works fine here.
> 
> 

In that case let me do a bit more thorough testing to make sure I haven't done wrong on my end.
