### ISSUE TITLE
TI99 -ioport peb command line broken

### ISSUE THREAD

**Issue by Tartifless** [libretro/mame#455]
When trying to plug 32kmem and speech module in ioport with lr-mame 0.258, retroarch exits with the following message:
[libretro ERROR] Error: unknown option: -<UNADORNED2>

The command line i send is :
-ioport peb -ioport:peb:slot2 32kmem -ioport:peb:slot3 speech

I tried with 0.249 (i had a backup of this version), and it was working fine.

It seems the usage of modules for ioport with TI99 is broken with latest mame core version.

@sonninnos

**Comment by Tartifless** [comment]
Quick update ==> tested with MAME 0.258 standalone and it works fine, so seems to be restricted to the core.

**Comment by sonninnos** [comment]
I copypasted that commandline, tried as both CLI command and in a `cmd` file, got no such errors, but instead  this:

![retroarch_2023_09_28_10_48_30_538](https://github.com/libretro/mame/assets/45124675/5b813583-3237-424c-8def-36138387e093)

Of course it needs `ti99_4` in the beginning:
```
ti99_4 -ioport peb -ioport:peb:slot2 32kmem -ioport:peb:slot3 speech
```

**Comment by Tartifless** [comment]
Is it possible that this is related with the length of the CL ?

When running:
start retroarch.exe -L "C:\RetroBat\emulators\retroarch\cores\mame_libretro.dll" "ti99_4a -skip_gameinfo -rompath C:\RetroBat\bios;C:\RetroBat\roms\ti99 -pluginspath C:\RetroBat\bios\mame\plugins -nvram_directory C:\RetroBat\saves\mame\nvram -cfg_directory C:\RetroBat\bios\mame\cfg -inipath C:\RetroBat\bios\mame\ini -hashpath C:\RetroBat\bios\mame\hash -artpath C:\RetroBat\saves\mame\artwork -snapshot_directory C:\RetroBat\screenshots -ioport peb -ioport:peb:slot3 speech alpiner"

It fails

If i run the same and remove just one path, it works (whatever the path i remove).

**Comment by sonninnos** [comment]
Sure there is and must be a limit in the parsing, and that length is just insane. You can shorten it immediately by removing the path from `-L`, since it only needs `mame`. `-skip_gameinfo` is also pointless since that is the hardcoded default in this core.

Current command line parsing size appears to be 512, while many other cases have 1024, so sure it could be changed.

**Comment by Tartifless** [comment]
Hello,

Yes I figured that out, I already removed the nvram path and pluginpath.

I am sharing the same code for standalone mame and libretro core.
So the paths are mostly for the standalone, to force them to the same paths as the core.

I guess at one point I will just have to activate these commands only for the standalone.

Can you confirm that the core uses the retroarch system and saves paths per default for cfg, ini, nvram, etc ? Can I find the information about paths used by the core somewhere ?

**Comment by sonninnos** [comment]
Of course it does unless you enable "MAME INI Paths".

All path parsing related is in https://github.com/libretro/mame/blob/master/src/osd/libretro/libretro-internal/retro_init.cpp and there in `Set_Path_Option()`.

All parsing and parameters are also revealed in the log when log level is debug.

**Comment by Tartifless** [comment]
Thanks, this is great info and it will enable me to cleanup the code then and put only the necessary paths for the core versus standalone

**Comment by sonninnos** [comment]
I can still increase the sizes if it helps.

**Comment by Tartifless** [comment]
I am always for an alignment between standalone and core if possible!

I don't know if mame standalone has such a limitation in length.

**Comment by Tartifless** [comment]
But anyway I was able to reduce drastically. Retrobat's bios path is equal to retroarch's system path and same for \saves and \screenshots path, so I could remove inipath, cfgpath, nvrampath, screenshotpath and hashpath already, plus -skip_gameinfo.
