### ISSUE TITLE
[REQUEST] add tag between version updates if possible.

### ISSUE THREAD

**Issue by ghost** [libretro/mame#46]
Please if possible add tags between version. Reason is that not every has the luxury of updating their current rompacks to match latest core release versions, and when that happens, current roms wont run anymore or run properly.

Being able to compile that very last commit would be of help for those who are able to compile them and share it for those that needs them.

Thanks.

**Comment by markwkidd** [comment]
@retro-wertz I have created this doc with MAME commit hashes as an alternative to having the releases tagged in the repository: https://docs.libretro.com/development/cores/core-specific/mame/

**Comment by tcamargo** [comment]
Closing old issues. Please reopen if it is still relevant.
