### ISSUE TITLE
The frame run ahead function does not work properly in mame 0.260.

### ISSUE THREAD

**Issue by guljam** [libretro/mame#460]
I enjoy the Mr driller series, and Mr.driller 2 and G versions based on Namco System 10 worked without problems in version mame 0.255 core.

Starting from version 0.257, input is problematic and cannot be played.
Specifically, the frame run ahead function seems to be problematic.

If you insert a coin, the screen plays normally. Standby screen audio is running.

Mr.Driller 1, which runs on namco system 12, also has the same problem.

To reproduce the problem:

1. Run a fully initialized retroarch
2. Download mame 0.260 core
3. Run any of Mr.driller 1, 2, or G (mrdrilr, mrdrilr2, mrdrilrg)
4. After execution, check that there is no problem with play operation.
5. Turn on frame run ahead function, value is 2~3
6. No problems running
7. Restart retroarch while maintaining the settings
8. Play Mr.Driller again
9. If there is no input after inserting the coin, the Standby screen continues to repeat. Game play is not possible.

**Comment by sonninnos** [comment]
Run-ahead relies on savestates, and those are not and have never been totally reliable, so saying that "input is completely messed up" is not exactly fair, since input works fine without run-ahead. At least with other systems. So please edit the title to be very specific.

**Comment by guljam** [comment]
@sonninnos 

Is the run ahead function retroarch itself an issue?
However, a bug occurs in mame 0.260 core, but it works properly in version 0.255. Since this issue occurs in Mr. Driller, it may be a problem with the namco system driver. If it is not relevant, I will close the issue.

**Comment by sonninnos** [comment]
Well the libretro-side savestate or input stuff hasn't changed between those versions, so namco driver might be to blame.

**Comment by guljam** [comment]
OK
I think I am the only one with a feature issue related to frame run ahead, so I will close the issue. Thank you.
