### ISSUE TITLE
Cannot load Any content

### ISSUE THREAD

**Issue by vus7294** [libretro/mame#463]
[retroarch__2023_12_08__22_17_43.log](https://github.com/libretro/mame/files/13614407/retroarch__2023_12_08__22_17_43.log)

![스크린샷 2023-12-08 222125](https://github.com/libretro/mame/assets/13133961/b6492b92-01dd-44cb-b56e-73c9d31bd6d9)
![스크린샷 2023-12-08 222334](https://github.com/libretro/mame/assets/13133961/77441f36-9cb3-4593-bc9c-58ca65bfe1d7)

I have that Bios and Game at Same Direction, but What is Problem? Even CHD Games are Failed.

**Comment by sonninnos** [comment]
Seems pretty clear, and boots fine here.
```
[libretro ERROR] m534002c-59.ic353 NOT FOUND (tried in tgmj coh3002c)
cp10.ic652 NOT FOUND (tried in tgmj coh3002c)
78081g503.ic655 NOT FOUND (NO GOOD DUMP KNOWN) (tried in tgmj coh3002c)
atej_04.2h NOT FOUND (tried in tgmj coh3002c)
ate-05m.3h NOT FOUND (tried in tgmj coh3002c)
ate-06m.4h NOT FOUND (tried in tgmj coh3002c)
ate_02.2e NOT FOUND (tried in tgmj coh3002c)
ate-01m.3a NOT FOUND (tried in tgmj coh3002c)
cp11 NOT FOUND (tried in tgmj coh3002c)
dl-1425.bin NOT FOUND (tried in qsound_hle tgmj coh3002c)
[libretro ERROR] Fatal error: Required files are missing, the machine cannot be run.
```

![retroarch_2023_12_08_16_16_16_415](https://github.com/libretro/mame/assets/45124675/50d336fc-3652-4d7b-822f-441731549245)

**Comment by vus7294** [comment]
I said, i Have All of require Rom file and bios at Rom Direction and Failed.

I'll retry with Reinstall retroarch

**Comment by sonninnos** [comment]
Maybe don't mix 7zs and zips, as in blame the romset?

**Comment by vus7294** [comment]
I use the Same Romset as Mobile version(works flawlessly) and i tried with Standalone ARCADE64 with that rom files and no problem. I'll try reinstall Libretro

**Comment by vus7294** [comment]
Reserved with Reinstall Retroarch Completely
