### ISSUE TITLE
strider 2 black screen 

### ISSUE THREAD

**Issue by kounabi22** [libretro/mame#470]
when strider 2 is loaded by libretro-mame i get a black screen and nothing more... dip switches and mame menu work.
when i try mame game works

all this in pi5-batocera.

**Comment by grant2258** [comment]
I use the standalone on my pi5 its works fine there, ill cross compile the latest libretro mame  and let you know if its working for me. It will probably an hour for the  compile to complete.

**Comment by grant2258** [comment]
Im happy to say it works fine on a raspberry pi5  on bookworm raspberry pi os (latest mame 0262 from this repository compiled myself).

**Comment by kounabi22** [comment]
ok .ty i will try it.

**Comment by sonninnos** [comment]
Hmm, I get black screen too on Windows. Only get this same log warning that groovymame also shows, but it does not hang:
```
[libretro WARN] 78081g503.ic655 NOT FOUND (NO GOOD DUMP KNOWN) (tried in strider2 coh3002c)
WARNING: the machine might not run correctly.
```

![retroarch_2024_02_23_18_23_55_690](https://github.com/libretro/mame/assets/45124675/8506a257-142f-479f-924b-083521a47dfb)


Edit: Hah, first guess was right. I tried renaming "plugins" dir from `system/mame`, and it does not hang..

And indeed culprit is the hiscore plugin. Disabling that alone does the trick.

**Comment by grant2258** [comment]
testing https://github.com/mamedev/mame/pull/12034  might be worth checking if it  fixes the galaxian hi score issue. It should also hopefully fix the xbox port threading issues.  The next version of mame is round the corner so ill wait till then to test it out.

**Comment by joepogo** [comment]
Hey @grant2258, just now seeing this and is really great news~! I guess this means we can turn the option back on for threading i presume and we can gain that speed benefit back with no crashing?

**Comment by grant2258** [comment]
@joepogo some arm devices where having the same issue the pi5 was one, and the pi4 was fine. Thankfully the pi5 is fine now so hopefully it goes well for your issues as well.

**Comment by joepogo** [comment]
Thanks for your response @grant2258 ! I'm gonna hop on dev mode shortly and test it out! If it still does not work, i wonder if i can post in that mamedev thread to advise them the xbox is still crashing on discrete games. I am thinking it is most likely fixed and with the newest mame pushed to retroarch i think all i need to do is update the core and then turn threading back on and see.

**Comment by joepogo** [comment]
Hey @grant2258 , just tested this on the newest updated mame and it still crashes back to dash on discrete games. Was this commit merged yet?

**Comment by joepogo** [comment]
Well, i posted on the thread but they do not support "hacked up mame cores" 😁

Oh well, I tried.

**Comment by grant2258** [comment]
I use standalone on the pi5 for mame, let me double check the libretro port is actually working on the pi5 will take a bit to compile. If your on mame0263 the changes will be there that we where talking about not sure if the buildbot is updated or not.

**Comment by joepogo** [comment]
@grant2258 i went and updated the mame current core yesterday for retroarch on xbox so i am almost certain it is now at .263. I will confirm this again later this evening and make sure it is. :)

**Comment by grant2258** [comment]
The pi5 is working just tested (libretro core compiled myself) dkong and galaxian are working as I was using standalone.

You can see what version of mame your on if you open the mame menu and pick about mame. I can see why mame devs are saying its libretros problem to fix there own bugs, it doesn't help the end users though.

looks like the build was finished 5 hours ago https://git.libretro.com/libretro/mame/-/pipelines/254749 not sure how long the build bot takes to filter through. It likely your where still on 262 the timestamps of posting so it still might be fixed can only hope.

**Comment by joepogo** [comment]
Hey @grant2258 , just checked it's at .263 and it still crashes when turning on threads on Xbox. 😔 

Pretty strange considering how in that mamedev thread above I posted in someone replied today and said that fix should basically work for all devices now without crashing and that retroarch uses different "threads" than mame. 

So now I'm really confused, is it retroarch side or mame side? 🤔

**Comment by grant2258** [comment]
Well Ra does insert itself as the main thread. I would need to look at the code a little for the xboxone code to answer that with any certainty though. I will get back to you on this and let you know if it is worth following up with an RA issue.

I would certainly open an issue on RA or whoever looks after the uwp port. The threading certainly does need fixed on uwp port. 

https://github.com/libretro/RetroArch/blob/952ac2a57a7a23ba518364753c28c390159e02b0/uwp/uwp_async.h#L32-L38

**Comment by joepogo** [comment]
@grant2258 is it possible to temporarily disable retroarch threading when using mame and use mame threading on Xbox as a workaround?

Hopefully that makes sense.

**Comment by grant2258** [comment]
Retroarch inserts itself between the os and the emulator @joepogo the best you can do is make an issue on the the retroarch git and hope someone that is familiar with the platform picks it up. It seems from the comments shown above, its workaround that someone might be able to tweak on the RA end.

**Comment by joepogo** [comment]
Thanks for your response @grant2258. At the risk of sounding ignorant is this an issue that needs to be opened in the actual RA issues or Mame for RA issues? I am not sure of what verbage to use but want to make sure that i open it in the correct place and state exactly what the issue is. 

At least we now know according to the mame guys that the problem is not mame, but RA. We have been slowly chipping away at figuring out this issue since 2022. I was happy to at least get confirmation that all devices should no longer crash on mame after that fix they pushed.

I appreciate any of your time with this grant, i think we are starting to see the light at the end of the tunnel for us xbox users lol. :P

**Comment by grant2258** [comment]
@joepogo I would personally say post a issue as its backed issue on the uwp port, therefore to me it belongs in the retroarch issues rather than this repo. Maybe @sonninnos can chime in where the issue is best placed in his opinion.
