### ISSUE TITLE
Analog buttons support

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/mame#48]
Mame could now support analog buttons as [they've been added into Retroarch.](https://github.com/libretro/RetroArch/pull/5697)

[Support in beetle-saturn as reference.](https://github.com/libretro/beetle-saturn-libretro/pull/88)

**Comment by Awakened0** [comment]
Yeah, it'd be great for triggers for acceleration and break in driving games. Right now I have to do a workaround with an override where I map my controller's triggers to up and down on the retropad's right stick. Then I map those to accel and brake in MAME's menu.

**Comment by Tatsuya79** [comment]
Done. https://github.com/libretro/mame/pull/85
