### ISSUE TITLE
[ANDROID] RA Savestates not working, but Mame proprietary Savestates does.

### ISSUE THREAD

**Issue by illando** [libretro/mame#482]
The entire RA Savestates system is not working using the actual Android version of the MAME core (1.18.0 MAME 0.265), like it’s actually possible on other platforms (I tested MacOS and Linux versions of RA).
Btw it seems working perfectly mapping some buttons to use the internal MAME Savestates systems.

As far as I know the two systems should work exactly the same.
Would be possible to re-activate the RA system please?

Thanks.

**Comment by agugu2000** [comment]
I'm not sure how the official team thinks. Perhaps it's because not every game can use savestates, so they turned it off.
I think this should not be an issue, the way to turn it off is in the core info file.
So the answer on how to turn it on is above.

**Comment by Locutus73** [comment]
I can confirm the issue.
Here's Arcade (MAME) on my PC
![image](https://github.com/user-attachments/assets/e07f1326-f39b-4874-8275-aa53049385cb)
And here's Arcade (MAME) on Android 13
![Screenshot_20240812-131306](https://github.com/user-attachments/assets/cf2d34a1-a107-48d8-823e-0836a8244793)
Sorry for the Italian GUI, but basically there's Deterministic savestates support in Win and no support at all in Android.
Interestingly enough on Android RetroArch uses /data/user/0/com.retroarch/cores/mamearcade_libretro_android.so core and there's no corresponding /data/user/0/com.retroarch/info/mamearcade_libretro_android.info
I tried copying mame_libretro.info into mamearcade_libretro_android.info and deleting core_info.cache but, again, I got no savestates (and run-ahead, rewind, etc.) with the Arcade (MAME) core.

Thank you in advance.

**Comment by kadireksi** [comment]
.info files don't use "android" tag, should be mamearcade_libretro.info

**Comment by Locutus73** [comment]
mamearcade_libretro.info has savestates disabled. Previously I tried to replace mamearcade_libretro.info with mame_libretro.info, but I didn’t delete the core_info.cache. I’ll try again deleting the cache and report back.

**Comment by Locutus73** [comment]
BINGO! I did another attempt: I renamed /data/user/0/com.retroarch/info/mamearcade_libretro.info to mamearcade_libretro.original and copied mame_libretro.info into mamearcade_libretro.info like I did before **but** this time I deleted core_info.cache too and this time I have Deterministic savestate support in Arcade (MAME) on Android.
![Screenshot_20240813-110216](https://github.com/user-attachments/assets/15fde0bb-68ee-49c6-8fe5-031e10e4b21d)
Ghosts'n Goblins struggles with +1 preemptive frame, but... at least I have savestates and performance was not the point here...
Now, if the info bundle for the online updater gets updated, does the update process clear the core_info.cache? All this stuff resides inside the private sandbox which isn't end user accessible.

Thank you!

**Comment by Locutus73** [comment]
BTW, _Settings->Core->Bypass Core Info Save States Features->Enabled_ should do the trick without fiddling with info files. Still, if mamearcade_libretro.info is wrongly reporting savestates as unsupported, IMHO it's still worth correcting that.

**Comment by sonninnos** [comment]
That can't be done here, but in the super repo where the info files are.

**Comment by Locutus73** [comment]
> That can't be done here, but in the super repo where the info files are.

Do I open an issue there?

**Comment by agugu2000** [comment]
open  info  file as text,
feature is controlled by  following code：
savestate = "true"
savestate_features = "deterministic"

**Comment by Locutus73** [comment]
Yeah, I got it, it’s basically what I did previously (copying the info file and deleting the cache). Problem is those files are in the app private sandbox which isn’t end user accessible in Android. That’s something IMHO worth correcting in the online update package (in the super repo).

**Comment by agugu2000** [comment]
changing  path of  infos is doable,but cores  not.
I don't know why the feature is disabled.Before it's fixed,modify the info file is a solution 
![Uploading Screenshot_2024-08-13-22-56-19-891_com.retroarch.aarch64.jpg…]()

**Comment by agugu2000** [comment]
changing path of infos is doable,but cores not.
I don't know why the feature is disabled.Before it's fixed,modify the info file is a solution
![Screenshot_2024-08-13-22-56-19-891_com retroarch aarch64](https://github.com/user-attachments/assets/5fa3ab26-1944-4c52-a168-f9360c5e9202)

**Comment by Locutus73** [comment]
> changing path of infos is doable,but cores not. I don't know why the feature is disabled.Before it's fixed,modify the info file is a solution

Oh, right, right… regardless I fixed it inside the sandbox and _Settings->Core->Bypass Core Info Save States Features->Enabled_ is an alternative solution.
My point is that probably that info file should be fixed in future releases.

**Comment by illando** [comment]
Guys, after reading this thread, I tried the Bypass Core info solution, and I tested all my mame roms (almost 50 games, various system) and none of them have problems with savestates or rewind functions.
Maybe it’s really time to fix that info file ad declare the android mame core capable of save and load states.

**Comment by sonninnos** [comment]
I shall repeat myself then:

> That can't be done here, but in the super repo where the info files are.

https://github.com/libretro/libretro-super

**Comment by illando** [comment]
@sonninnos I’m sorry. I did not understand what this super repo is till now.
Thanks a lot.
