### ISSUE TITLE
Analog Deadzone Option

### ISSUE THREAD

**Issue by Awakened0** [libretro/mame#49]
I have some analog drift on my controller's left stick in games like Enduro Racer or OutRun. It seems fine in stand alone MAME with joystick_deadzone set to the default 0.3 though. I tried setting read config on (verified it working by changing the brightness) and making sure it was set the same as stand alone in mame.ini, but still got the drift. Is the libretro port ignoring that option?

Ideally, I'd like to be have analog deadzone as a core option for easy access.

**Comment by barcoboy** [comment]
I was experiencing the same problem.  The only way I found I could solve it was by putting a hard coded value in the file src/emu/emuopts.h and re-compiling.  I changed line 425 to read:

float joystick_deadzone() const { return 0.3; }

And now my mame.ini file is updated with that value, instead of it always being 0.

**Comment by tcamargo** [comment]
Does it still happen on 0.222?

**Comment by Awakened0** [comment]
I've switched over to Final Burn completely since this. Don't really want to mess around with the MAME cores anymore myself, but maybe someone else is still interested in this issue.

**Comment by barcoboy** [comment]
Just tested with RetroArch 1.8.9 and MAME core 0.222, and the parameter is now respected.

However, I did notice a small bug with the menu system.  If I select the option with my action button, I get a list of choices from 0.0 to 0.9 in 0.1 step increments, and can select any one.  But if I use the left and right directions to increment/decrement and select the value in the menu choice, pressing left on 0.0 and the value changes to 1.0, which is not a valid choice. Going down a few entries to say 0.8 and then going back up with the right direction, the value goes to 0.8, 0.9, back to 1.0, then 0.0, and back up to 0.9, but then afterwards correctly rolls back to 0.0.  This happens regardless of what menu driver is selected.

**Comment by tcamargo** [comment]
@barcoboy Thx for the feedback. I guess it is an upstream problem. Could you test with standalone mame?

**Comment by barcoboy** [comment]
No, the secondary issue I mentioned is in RetroArch, not MAME.  The analog deadzone option is working correctly, which was the original issue.

**Comment by Awakened0** [comment]
Ok, if the deadzone option works, I can close this.
