### ISSUE TITLE
4-way Joystick Simulation no longer works

### ISSUE THREAD

**Issue by msheehan79** [libretro/mame#494]
The core option for 4-way Joystick simulation is not working with the current version of the core (just tested with the latest 0.269 update).

I believe it is due to the original V1 Core Options having values of "4way", "strict" and "qbert" whereas the more recent versions of the core have updated the values to simply "enabled" and "disabled".  I haven't dug too deeply into the code yet but that is where I would assume the issue lies.

The last core I have where it worked as expected was 0.257, which still had the V1 core options.  The next version I had a copy of was 0.263 and it was broken there.

Also worth noting for testing - the 4-way simulation only seems to apply to Analog joysticks, so when I was testing with my controller D-Pad even with the setting enabled I could move diagonally in games with dpad, but I could see the 4-way restriction working with the analog stick on the old version of the core.  This is also how it works in upstream Mame too, not sure if there is a way to adjust that so 4-way applies consistently to both analog and dpad controls (probably a different issue but worth noting as I was not aware of this aspect of the setting)

**Comment by sonninnos** [comment]
Oops, fixing soon.

**Comment by msheehan79** [comment]
@sonninnos Thanks for fixing that so quickly!  Just tested the new build, working as expected now.

Also adding here for reference re: my comments about 4-way only working for the analog stick - I was able to get the core to respect 4-way simulation for the dpad by remapping the dpad to the analog stick as a game Remap file.  So that seems to be a pretty reasonable way to enforce 4-way on both the analog stick and dpad using RetroArch's native functionality.
