### ISSUE TITLE
[NeoGeo] no games are working

### ISSUE THREAD

**Issue by nemo93** [libretro/mame#501]
Hello,

I just started fiddling with this MAME core on my Windows 10 and any classic Arcade games are running perfectly. It's unfortunately not the case with any of the NeoGeo roms. I tried like 20 of them to be sure but whenever I launch a rom I get back to my frontend (ES-DE). 

I'm sure all the NeoGeo roms are proper as they work fine either with FBA or with "standalone" MAME binary. I'm relying on non-merged sets.

Examples of games not running:
3countb
2020bb
alpham2
androdun
aof
aof2
aof3
...

Using latest RetroArch and updated core. Anything I've missed? Let me know if more details should be provided. Thanks!

**Comment by riggles1** [comment]
They work like they should, Win10 64bit here. Not sure what you're doing wrong. A log file should say what's going on. Could be that you have merged roms specified in the playlist, but nonmerged trying to be loaded.

As a test, update the core to 270 again, download merged and the latest 270 non-merged roms for the games you're trying to run.

**Comment by nemo93** [comment]
Thanks for the swift feedback! Indeed these roms are working fine after I've made sure to run the latest 270 non-merged set and core. Also the trick was to switch off the `Softlist` toggle in the Core Options. I'm not certain what this means exactly but anyhow it's perfectly working now! Thanks again and really appreciate the work done on that core.
