### ISSUE TITLE
mame_libretro.dll for Mame 0.270 Windows 64bit

### ISSUE THREAD

**Issue by mahmutelmas06** [libretro/mame#506]
As title says i need mame_libretro.dll for Mame 0.270 Windows 64bit
Can anyone share with me?

**Comment by kadireksi** [comment]
0.270 te çalışıp 0.271 de bozulan bir şey mi var?

**Comment by mahmutelmas06** [comment]
> 0.270 te çalışıp 0.271 de bozulan bir şey mi var?

Evet. Çok değil ama romların bazıları açmıyor.  Hepsini denemedim.

**Comment by kadireksi** [comment]
Retroarch içinden güncelleme yaptıysan önceki versiyonun yedeğini almıştır, onu kullanabilirsin,  çalışmayan romlardan birinin 0.271 için olanını yeniden indirip deneyebilirsin, hiçbir yöntem de çalışmazsa yarın kaynağı indirip derleyebilirim senin için

**Comment by mahmutelmas06** [comment]
Retroarch yedeği de 0.269 da almış en son.
271 için olan rom işe yarıyor. Çalışmayan roma denk geldikçe 271 sürümünü indirmem gerekecek.
Teşekkür ederim

**Comment by kadireksi** [comment]
Hayırlı olsun, bir sıkıntın olursa yazabilirsin ,birde 'issue' yu kapatmayı unutma :)
