### ISSUE TITLE
272 Breaks MAME built in mappings.

### ISSUE THREAD

**Issue by riggles1** [libretro/mame#512]
MAME input settings don't save like they should when launching different games as of 272.
In the core with a game launched>MAME "Tab" menu>"Input Settings">"Input Assignments">"General" 

My menu navigation buttons were completely changed, setting them again works for this game, but load another game and they're completely different, even if I set general inputs in here correctly, they'll end up different in another game.

I've deleted the .cfg's in saves>mame>cfg, for the purpose of testing.
Something isn't being read correctly out of those configs. 

Thanks for checking my issue report! :)

**Comment by sonninnos** [comment]
I'm not noticing anything here. Previous mappings still work after multiple restarts.

**Comment by riggles1** [comment]
Strange, I'll compile a previous version again (deleted 270 that I was using).
No RA remaps, removed .cfg's.

MAME menu navigation mappings specifically "default.cfg" set your buttons for accept, back etc.
It saves and works, but close content and switch to another game and those mame general input menu navigation buttons are scrambled for that other game.

**Comment by riggles1** [comment]
(my fault, core override present for one game, to prevent it from reading mame ini, something along those lines)
