### ISSUE TITLE
Mouse cursor should not be visible

### ISSUE THREAD

**Issue by AaronBPaden** [libretro/mame#52]
When opening up a game in mame, the mouse shows up in the middle of the screen, at least on Linux. This doesn't seem to be a problem with upstream; if I start a game with sdlmame the mouse cursor is hidden as expected.

**Comment by Tatsuya79** [comment]
I see the mouse cursor when there is a "ChangeAV" call in the logging with Mame.
If a game just ask for "Set_Geometry" then it's not there (you don't see a "video signal re-init" happening too).

I'm using exclusive fullscreen too, win7 x64.
related to https://github.com/libretro/RetroArch/issues/4586
