### ISSUE TITLE
Mame esc key crashes RA

### ISSUE THREAD

**Issue by telanus** [libretro/mame#54]
If one accidentally exit the mame core using the standard escape key, while RA's exit key is mapped to anything beyond the standard escape key IE the Pause Break key, mame will bring RA down with a either a `Segmentation fault (core dumped)` or it'll give either an abbreviated backtrace or an unabridged version that floods the terminal rendering it useless.

The abbreviated backtrace: https://pastebin.com/3MR6ksCS

Running the latest nightly of the testing ppa

**Comment by tcamargo** [comment]
Closing old issues. Please reopen if it is still relevant.
