### ISSUE TITLE
stvbios roms hang retroarch with mame armhf core

### ISSUE THREAD

**Issue by grgohr** [libretro/mame#56]
All roms using stvbios (http://www.progettoemma.net/index.php?&gioco=stvbios) hang the armhf build of retroarch with mame cores > 2003 = leaves retroarch inactive with a white frame border on load.
no error message in the retroarch console, romsets load properly. the core works great with other roms non stvbios-related.

those roms load fine with mame2003 though (same issue with mame16_libretro.so, mame2014_libretro.so and mame2010_libretro.so)

seems to be the same issue reported there : https://forums.libretro.com/t/mame-stvbios-games/6137

cf https://github.com/libretro/mame2014-libretro/issues/61
builds tested from nightly https://answers.launchpad.net/~libretro/+archive/ubuntu/testing/+packages?field.name_filter=mame

**Comment by tcamargo** [comment]
Could you please test with a newer build of lr-mame? Thx!
