### ISSUE TITLE
Add support for cheats?

### ISSUE THREAD

**Issue by jmfergeau** [libretro/mame#58]
Sorry to open an issue for that, but i don't understand why the mame2003 core is apparently the only one supporting cheats. Plus, a very old cheat file format that is not used since, like 10 years ago. (Now mame uses a 7zipped xml file which is waaay less heavy, 1.7Mb instead of 13)

Any technical reasons that makes impossible the cheat support for the other core instances?

**Comment by r-type** [comment]
mame cheat are supported in this core using lua plugging .

**Comment by jmfergeau** [comment]
What does it mean? That the usual xml cheat files (or even the old cheat files) are not compatible with this method and that cheat codes must be formatted using lua and not xml?

**Comment by tcamargo** [comment]
See https://github.com/libretro/mame/issues/82

**Comment by palmerj** [comment]
Can I please to get some clarity on this issue? Specifically:

* how do you enable the lua plugin system with this libretro mame build? Do you need to recompile?
* does the normal xml cheat files work? Note this seems to be the case if you read http://www.mamecheat.co.uk/forums/viewtopic.php?f=10&t=12237

**Comment by palmerj** [comment]
For now I'm using the old cheat system and enabling the cheat option via the retroarch OSD
