### ISSUE TITLE
MAME 2009 (Wii U version) game slowdown problems

### ISSUE THREAD

**Issue by dagreatbuzzsaw** [libretro/mame#62]
I couldn't find a thread for MAME 2009 (0.135u4) so I put my request here.

There is an issue with the MAME 2009 core in my Wii U Retroarch.

Mortal Kombat 2 and Ultimate Mortal Kombat 3 go through SEVERE slowdown when they boot up.

The first Mortal Kombat for MAME boots up fine and works great though the audio is a bit choppy.

Thanks!

**Comment by inactive123** [comment]
MAME 2009 is a lot slower than MAME 2003. That is really the only reason for this.

If you want these games you mentioned to run at fullspeed, stick to MAME 2003.

**Comment by markwkidd** [comment]
There is a MAME 2009 repository here: https://github.com/r-type/mame2009-libretro
