### ISSUE TITLE
MAME (current) MacOS does not build in libretro-super

### ISSUE THREAD

**Issue by estefan3112** [libretro/mame#63]
Hey guys, the MAME (current) core for Retroarch MacOS dates back from November 2016. I opened an issue in libretto-super some time ago (issue #736 in this repo), but it is not answered. I provided some information about my failed attempt to compile a Retroarch core. Is there any chance that MAME (current) will build again for MacOS? Many thanks, it's a real loophole on my Mac. Cheers!

**Comment by cold-brewed** [comment]
I recently submitted a PR (#94) that should fix the issue. Could you try to build this again?

**Comment by estefan3112** [comment]
The core now builds in libretro-super. In the Nighties repo, the build is now version 206. Many thanks
