### ISSUE TITLE
mame_libretro.dll [libretro ERROR] Driver j:/emulationstation not found -1

### ISSUE THREAD

**Issue by danyboy666** [libretro/mame#64]
retroarch version: 1.7.1 (build feb 19 2018)
mame lb core version: 0.195
emulationstation version V2.80RP-DEV

Ok I know it's a challenge to get cdimono1 to work with emulationstation. On any platform for that matter. 

Anywais I was able succesfully to launch zelda advanture by CLi using a simple txt dummy filebut I can't get the game to load at all from within emulation station.

```
<!-- This is the EmulationStation Systems configuration file.
All systems must be contained within the <systemList> tag.-->

<systemList>
~\.emulationstation\roms
<system>
    <name>cdimono1</name>
    <fullname>Philips CD-I</fullname>
    <path>~.emulationstation\roms\cdimono1</path>
	<extension>.txt</extension>
    <command>%HOME%\.emulationstation\systems\retroarch\retroarch.exe -c %HOME%\.emulationstation\systems\retroarch\config\mame_libretro.cfg  -L %HOME%\.emulationstation\systems\retroarch\cores\mame_libretro.dll "%ROM_RAW%"</command>
    <platform>cdimono1</platform>
    <theme>cdimono1</theme>
</system>
</systemList>
```

The configuration file in the path never worked I suspect the -L have precendence over everything and retroarch load automatically the correct core cfg.

From the help file

> -L, --libretro=FILE   Path to libretro implementation. Overrides any config setting.
      --subsystem=NAME  Use a subsystem of the libretro core. Multiple content
                        files are loaded as multiple arguments. If a content
                        file is skipped, use a blank ("") command line argument.
                        Content must be loaded in an order which depends on the
                        particular subsystem used. See verbose log output to learn
                        how a particular subsystem wants content to be loaded.

Working log (boot from cli)
[log_1](https://gist.github.com/danyboy666/52c0d002c397ebcf8ea6f8ec3a6eb8ca)

Non-working output (boot from emulationstation front end)
[log_2](https://gist.github.com/danyboy666/27ca9967c3da7d3867a0693700ff93a2)
![sans titre](https://user-images.githubusercontent.com/8345498/38002597-3c27b15a-3201-11e8-82c4-1ac3e85f86bb.jpg)

I've tried absolute path in es_systems.cfg I,ve tried multiple folder configuration too nothing seem to work. 

For some reason mame_libretro doesnt accept the launch command sub parameter cdimono1 -cdrm but since i was able to luanch the game from cli withou no issue i doubt it's the problem in this case. 

btw this is my folder structure

path 
`J:\emulationstation\.emulationstation\roms\cdimono1\`

files
-> cdimono1.zip
-> zeldaadv.txt 
-> zelda's adventure (1995)(philips)(eu).chd

system path has the mame folder with hash files inside the  hash folder

I've tried complicated folder structures too and none seem to please es and always spits out the same errors.

Any ideas what is going on? 

p.s I wonder why the .chd files shows up in es since I specified only .txt extension? The gamelist is parsed anywais?

**Comment by danyboy666** [comment]
Nevermind this threadI now call a script which fixes the rom path. For anyone trying to setup Philips CD-i on the windows version of ES read this thread and create a bat file and call it cdimono1.bat in \retroarch\scripts directory

```
echo off

set ROMPATH=%~d0\emulationstation\.emulationstation\roms\cdimono1\
set arg1=%1

%~d0\emulationstation\.emulationstation\systems\retroarch\retroarch.exe -L %~d0\emulationstation\.emulationstation\systems\retroarch\cores\mame_libretro.dll %ROMPATH%%arg1%.txt
```

edit your es_system.cfg like so

```
<system>
    <name>cdimono1</name>
    <fullname>Philips CD-I</fullname>
    <path>J:\emulationstation\.emulationstation\systems\retroarch\content\mame\cdimono1</path>
	<extension>.txt</extension>
<!--	<command>%HOME%\.emulationstation\systems\retroarch\retroarch.exe -L %HOME%\.emulationstation\systems\retroarch\cores\mame_libretro.dll %ROM%</command>  -->
	<command>%HOME%\.emulationstation\systems\retroarch\scripts\cdimono1.bat %BASENAME%</command>
    <platform>cdimono1</platform>
    <theme>cdimono1</theme>
</system>
```

use this folder scructure : 

**J:\emulationstation\.emulationstation\roms\cdimono1\**
   -> **cdimono1.zip**
   -> **zeldaadv.txt**
   -> **zelda's adventure (1995)(philips)(eu).chd**
Also you need to have the **mame/hash/*.xml**  folder in **retroarch/system/** directory. 
No other setting swill work. No sub folders work either. Excep a folder structure like : roms/mame/cdimono1/ or roms/content/mame/cdimono1/ .

It's important that the chd is named exaclty as the ones mame\hash\cdi.xml. I've tested this multiple ways and it comes down to mame can't translate the rom path properly. If you use the proper windows syntaxe with backslashes though it will work. Ence why this little script. This method and other than naming the dummy file with a different extension nothing will work. Other than that you can press the TAB key to configure your controller to work with cdi/mame games but you keyboard should work right off the bat.

Edit: For linux you need something like this 

**/opt/retropie/configs/cdimono1/emulators.cfg**

```
mame_libretro = "/opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-mame/mame_libretro.so --config /opt/retropie/configs/cdimono1/retroarch.cfg /home/gameuser/RetroPie/roms/cdimono1/%BASENAME%.txt"
default = "mame_libretro"
```

Use retroarch gui  to download the pre compiled mame_libretro core. mame Version 0.195

**Comment by tcamargo** [comment]
Is that a problem in lr-mame?
