### ISSUE TITLE
Mame 195 for android needed recompiled with separate properties 

### ISSUE THREAD

**Issue by sanchezmike01** [libretro/mame#65]
Basically I need mame195 for android recompiled with separate properties than the current version to play handheld games....on android to play those new handheld game roms u need to have the boot to bios option enabled.....if that option is set to enabled then you cant boot any mess games....so there is conflict there....the only way to have them both working is to have 1 mame195 for mess and arcade games and to have another mame195 with separate properties to play any handheld games where different options can be set but wont interfere with one another...will be offering a $20 bounty and posting on bounty source......sanchez_mike01@yahoo.com        https://www.bountysource.com/issues/56505407-mame-195-for-android-needed-recompiled-with-separate-properties

**Comment by tcamargo** [comment]
Still relevant? Did you try a new build?

**Comment by sonninnos** [comment]
I'm going to guess this is no longer relevant.
