### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by felipesanches** [libretro/mame#66]
I am new to this project (even though I've been dealing with upstream MAME sources for several years).

I want to build MAME libretro core to run on a RaspberryPi 3. I expected to see some minimal instructions on the README.md file in this repo.

**Comment by felipesanches** [comment]
And I am willing to cross-compile it from my laptop running a GNU/Linux distro.

**Comment by felipesanches** [comment]
@r-type 

I see on the verbose g++ build logs that there's a `--PLATFORM=x86`. I wonder if can/need to change this in order to cross-build mame to run on the Raspberry Pi 3.

I considered passing `PLATFORM=armv8` on the  make invokation, as well as trying to set this inside `Makefile.libretro`. I also tried the same with `ARCH` as well as `LiBRETRO_CPU` to no avail.

I have no idea how to build it. :-(

**Comment by felipesanches** [comment]
![screenshot at 2018-06-02 21 34 01](https://user-images.githubusercontent.com/213676/40882035-0e3aea42-66c6-11e8-9697-f1c21b8f6485.png)

![screenshot at 2018-06-02 21 04 03](https://user-images.githubusercontent.com/213676/40882037-174f55f0-66c6-11e8-9c24-c0be461ad47b.png)

**Comment by tcamargo** [comment]
Closing old issues. Please reopen if it is still relevant.
