### ISSUE TITLE
No hiscore within mame libretro mame core .194 using roms/chd  .193, standalone works.

### ISSUE THREAD

**Issue by 702demon** [libretro/mame#67]
Hello I've been having a issue with hiscore within mame  Libretro mame core .194 my current rom set is .193, within standalone mame .193 hiscore functions as intended. I figure my issue has something to do with file or directory placement or structure. I currently have mame .194 standalone placed within the retroarch system folder. please any help is appreciated.

**Comment by tcamargo** [comment]
Still relevant? If so, please, reopen this issue.
