### ISSUE TITLE
Hide nagscreen and  Hide warnings broken

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/mame#7]
When I enable "Hide nagscreen" mame crashes with:

Error: unknown option -skip_nagscreen

Hide warnings is broken too.

**Comment by andres-asm** [comment]
I think we shouldn't have those in mainline
we should keep mainline as close to master as possible to avoid having to re-port all the time
we have enough mame cores as it is

**Comment by Enverex** [comment]
Twin hard removed the nag-screen completely but didn't remove all of the nag-screen option code so it's kinda in a zombie state right now.

I'll sort this out and submit a PR.

EDIT: At least I thought he did, the comments may be on the old fork as I can't find them here anymore.

**Comment by Enverex** [comment]
Added as PR https://github.com/libretro/mame/pull/8

**Comment by Enverex** [comment]
If you'd like to hide all of the screens on the GIT version still, just use this patch before building. It's hopefully simple enough that it won't require altering for a long time to come - https://gist.github.com/Enverex/420fda0bc0cd5a50d9d90ce8dad89822

**Comment by r-type** [comment]
we should close this one now.
