### ISSUE TITLE
Crash when running MAME MCR based games

### ISSUE THREAD

**Issue by barcoboy** [libretro/mame#71]
Not able to run any games that use the MCR based hardware on the MAME core.  Examples of such games are:

Demolition Derby
Kick
Tapper
Timber

Upon trying to start one these games, libretro crashes and exits.  MAME 0.200 on the same system (Slackware64 14.2) runs the games without any issues.

Last line of the log reads as follows:

retroarch: ../../../../../src/emu/devfind.h:465: ObjectClass* object_finder_base<ObjectClass, Required>::operator->() const [with ObjectClass = midway_ssio_device; bool Required = false]: Assertion `m_target' failed.

Removing the assert from line 465 in devfind.h and recompiling fixes the issue and the games seem to run normally, but that is probably not the correct way to fix the problem.

**Comment by Awakened0** [comment]
You might want to try those again in 0.203, since it fixed Pac-Man and Ms. Pac-Man crashing for me.

**Comment by tcamargo** [comment]
Try again with a recent build. #125 probably fixed it.

**Comment by barcoboy** [comment]
Yes, I meant to comment on this a while ago... the problem was resolved a number of builds back.  

Closing.
