### ISSUE TITLE
Just a question about this vs mamedev.

### ISSUE THREAD

**Issue by undeadindustries** [libretro/mame#72]
How up-to-date is libretro/mame vs mamedev/mame?

Meaning, right now, mamedev is on .201. When would libretro get those updates?

Just curious. Thanks!

**Comment by Tatsuya79** [comment]
It's whenever R-Type has the time to do it, which happened just now.

**Comment by andres-asm** [comment]
It seems it's a case of git fetch upstream, git rebase upstream/master, anyone should be able to do it.

**Comment by r-type** [comment]
in fact , it's easy but painful to build and check ....

1)  fork libretro/mame git

2)  configuring upstream mamedev/mame remote for this fork
https://help.github.com/articles/configuring-a-remote-for-a-fork/

3) git fetch upstream -> to retreive last commit from upstream

4) git merge XYZW  (XYZW is the last release tag ,for now last release tag is 4dc302ed05eb03242f514afa6a57876bf15baed9)

5) resolve conflicts if any.

6) build and try result  to see if everything go fine

7) if any problem , look at the change and fix it.

8 )  git push origin master -> commit the change to your fork.

And yes anyone should be able to do it !
but it seem that when i have no time to do it shortly after an upstream release, no one does or care ...

**Comment by Tatsuya79** [comment]
Thanks for doing that regularly.

**Comment by undeadindustries** [comment]
Thank you! I was just asking because I found, with MAME, "latest" didn't always mean newest.

Thanks again.
