### ISSUE TITLE
Pac-Man and Ms. Pac-Man Crashing on 0.201

### ISSUE THREAD

**Issue by Awakened0** [libretro/mame#75]
Testing on Win10. The same ROMs work fine in 0.201 stand alone. Verbose log output:

https://hastebin.com/gedosumomi.cs

**Comment by sweatypickle** [comment]
you can add spyhunter to this. Same conditions as above.

**Comment by Awakened0** [comment]
These two work again on 0.203. Haven't tried Spy Hunter, but maybe that's fixed too.

**Comment by PixelCrusader** [comment]
Spy Hunter launches now.

**Comment by Awakened0** [comment]
Cool, closing this now :D
