### ISSUE TITLE
Launching Taito Zoom ZSG-2 Games Causes RetroArch to Crash.

### ISSUE THREAD

**Issue by PixelCrusader** [libretro/mame#76]
Windows 7 64 bit, AMD Radeon HD 6450, Intel i5-2320 CPU @ 3.00GHz
RetroArch 1.7.4 1155e11 - MAME 0.201

So far tested with G-Darius, RayStorm and RayCrisis. Attempting to launch these games within RetroArch will cause it to crash with an error:

Microsoft Visual C++ Runtime Library
This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information.

This behavior is not occuring in mainline MAME .201 and didn't occur in the .200 Libretro core.

**Comment by Awakened0** [comment]
You might want to try those again in 0.203, since it fixed Pac-Man and Ms. Pac-Man crashing for me.

**Comment by PixelCrusader** [comment]
RetroArch 1.7.5 7c93a0934e - MAME 0.203

The problem persists. Launching one of those games still causes RetroArch to crash. The games still launch properly in standalone MAME .203

Thanks for trying to help, though.

**Comment by Awakened0** [comment]
Ah, too bad : /

**Comment by Tatsuya79** [comment]
Just noticed those games crashing, psyvariar too...

Some big changes in that driver since 0.201:
https://github.com/mamedev/mame/commits/master/src/devices/sound/zsg2.cpp

**Comment by Tatsuya79** [comment]
Log shows:
```
File: ../../../../../src/emu/sound.cpp, Line 708
Expression: basesample >= input_stream.m_output_base_sampindex
```

[drmingw.txt](https://github.com/libretro/mame/files/3697804/drmingw.txt)

**Comment by Tatsuya79** [comment]
@tcamargo this is working now as well. :smiley: 

Fixed with https://github.com/libretro/mame/pull/125

**Comment by PixelCrusader** [comment]
Just checked and yeah, it’s fixed on my end too. Looks like that’s a wrap. Thanks everyone, @tcamargo .
