### ISSUE TITLE
[Android] Fails to build

### ISSUE THREAD

**Issue by hizzlekizzle** [libretro/mame#78]
This has been happening for a while, I think. This appears to be the relevant error:
```
In file included from ../../../../../src/mame/drivers/alpha68k.cpp:1:
In file included from ../../../../../src/emu/emu.h:104:
/home/buildbot/buildbot/android/libretro-mame/build/projects/retro/mame/gmake-android-arm/../../../../../src/emu/devcb.h:1258:12: error: 'consume' is a protected member of 'devcb_write<unsigned char, '\xFF'>::builder_base'
                { m_sink.consume(); }
                         ^
/home/buildbot/buildbot/android/libretro-mame/build/projects/retro/mame/gmake-android-arm/../../../../../src/emu/devcb.h:1497:11: note: in instantiation of function template specialization 'devcb_write<unsigned char, '\xFF'>::first_transform_builder<devcb_write<unsigned char, '\xFF'>::delegate_builder<device_delegate<void (address_space &, unsigned int, unsigned char, unsigned char)> >::wrapped_builder, (lambda at /home/buildbot/buildbot/android/libretro-mame/build/projects/retro/mame/gmake-android-arm/../../../../../src/emu/devcb.h:255:52)>::first_transform_builder<(lambda at /home/buildbot/buildbot/android/libretro-mame/build/projects/retro/mame/gmake-android-arm/../../../../../src/emu/devcb.h:255:52)>' requested here
                        return first_transform_builder<wrapped_builder, std::remove_reference_t<T> >(this->m_target, this->m_append, wrapped_builder(std::move(*this)), std::forward<T>(cb), this->exor(), in_mask, out_mask);
                               ^
/home/buildbot/buildbot/android/libretro-mame/build/projects/retro/mame/gmake-android-arm/../../../../../src/emu/devcb.h:255:42: note: in instantiation of function template specialization 'devcb_write<unsigned char, '\xFF'>::delegate_builder<device_delegate<void (address_space &, unsigned int, unsigned char, unsigned char)> >::transform<(lambda at /home/buildbot/buildbot/android/libretro-mame/build/projects/retro/mame/gmake-android-arm/../../../../../src/emu/devcb.h:255:52)>' requested here
                        auto trans(static_cast<Impl &>(*this).transform([val] (offs_t offset, T data, std::make_unsigned_t<T> &mem_mask) { mem_mask >>= val; return data >> val; }));
                                                              ^
/home/buildbot/buildbot/android/libretro-mame/build/projects/retro/mame/gmake-android-arm/../../../../../src/emu/devcb.h:1142:8: note: declared protected here
                void consume() { m_consumed = true; }
                     ^
/home/buildbot/buildbot/android/libretro-mame/build/projects/retro/mame/gmake-android-arm/../../../../../src/emu/devcb.h:1267:11: error: 'consume' is a protected member of 'devcb_write<unsigned char, '\xFF'>::builder_base'
                        m_sink.consume();
                               ^
/home/buildbot/buildbot/android/libretro-mame/build/projects/retro/mame/gmake-android-arm/../../../../../src/emu/devcb.h:255:9: note: in instantiation of member function 'devcb_write<unsigned char, '\xFF'>::first_transform_builder<devcb_write<unsigned char, '\xFF'>::delegate_builder<device_delegate<void (address_space &, unsigned int, unsigned char, unsigned char)> >::wrapped_builder, (lambda at /home/buildbot/buildbot/android/libretro-mame/build/projects/retro/mame/gmake-android-arm/../../../../../src/emu/devcb.h:255:52)>::first_transform_builder' requested here
                        auto trans(static_cast<Impl &>(*this).transform([val] (offs_t offset, T data, std::make_unsigned_t<T> &mem_mask) { mem_mask >>= val; return data >> val; }));
                             ^
/home/buildbot/buildbot/android/libretro-mame/build/projects/retro/mame/gmake-android-arm/../../../../../src/emu/devcb.h:1142:8: note: declared protected here
                void consume() { m_consumed = true; }
                     ^
2 errors generated.
alpha.make:627: recipe for target '../../../../libretro/obj/libretro/src/mame/drivers/alpha68k.o' failed
make[2]: *** [../../../../libretro/obj/libretro/src/mame/drivers/alpha68k.o] Error 1
Makefile:109: recipe for target 'alpha' failed
make[1]: *** [alpha] Error 2
make[1]: *** Waiting for unfinished jobs....
```
Rest of the log is here:
http://p.0bl.net/41004

**Comment by markwkidd** [comment]
I have started a bounty for this issue with a donation of $10: https://www.bountysource.com/issues/63665169-android-fails-to-build

@grant2258 or @nayslayer, any chance one of you would like to earn $10 plus your shot at glory?

**Comment by c0d3x27** [comment]
> I have started a bounty for this issue with a donation of $10: https://www.bountysource.com/issues/63665169-android-fails-to-build
> 
> @grant2258 or @nayslayer, any chance one of you would like to earn $10 plus your shot at glory?

the problem is in the code. some part are privates and others arent.

**Comment by Immersion95** [comment]
Is this why we only have an old version of the MAME core ?

**Comment by tcamargo** [comment]
http://paste.libretro.com/215233
It seems a problem in android SDK. Any android devs around?


`/home/buildbot/buildbot/android/libretro-mame/src/osd/libretro/retroprefix.h -o "../../../../libretro/obj/libretro/3rdparty/bgfx/3rdparty/dear-imgui/imgui.o" -c "../../../../../3rdparty/bgfx/3rdparty/dear-imgui/imgui.cpp"
In file included from ../../../../../3rdparty/bgfx/3rdparty/dear-imgui/imgui.cpp:770:
In file included from ../../../../../3rdparty/bgfx/3rdparty/dear-imgui/imgui.h:46:
In file included from /home/buildbot/tools/android/android-ndk-r20//sources/cxx-stl/llvm-libc++/include/string.h:61:
In file included from /home/buildbot/tools/android/android-ndk-r20//sysroot/usr/include/string.h:36:
In file included from /home/buildbot/tools/android/android-ndk-r20//sysroot/usr/include/bits/strcasecmp.h:37:
In file included from /home/buildbot/tools/android/android-ndk-r20//sysroot/usr/include/sys/types.h:39:
/home/buildbot/tools/android/android-ndk-r20//sysroot/usr/include/bits/pthread_types.h:38:3: error: unknown type name 'size_t'
  size_t stack_size;
  ^
/home/buildbot/tools/android/android-ndk-r20//sysroot/usr/include/bits/pthread_types.h:39:3: error: unknown type name 'size_t'
  size_t guard_size;
  ^
In file included from ../../../../../3rdparty/bgfx/3rdparty/dear-imgui/imgui.cpp:770:
In file included from ../../../../../3rdparty/bgfx/3rdparty/dear-imgui/imgui.h:46:
In file included from /home/buildbot/tools/android/android-ndk-r20//sources/cxx-stl/llvm-libc++/include/string.h:61:
In file included from /home/buildbot/tools/android/android-ndk-r20//sysroot/usr/include/string.h:36:
/home/buildbot/tools/android/android-ndk-r20//sysroot/usr/include/bits/strcasecmp.h:68:53: error: unknown type name 'size_t'; did you mean 'ssize_t'?`

**Comment by markwkidd** [comment]
Is there a consensus that the bounty should be awarded? I admit I haven't been following this issue closely.

**Comment by tcamargo** [comment]
This PR made possible to build for android again. https://github.com/libretro/mame/pull/175 closed a link problem and games are running. i plan to transfer this bounty to another.

**Comment by tcamargo** [comment]
Also, see https://github.com/libretro/mame/issues/174.
