### ISSUE TITLE
Loading titles from the MAME software list causes RA to hang indefinitely

### ISSUE THREAD

**Issue by Shoegzer** [libretro/mame#81]
First, I wasn't entirely sure whether this issue belongs with RA or MAME, so please move if it's better suited as an RA issue.

RA's MAME core supports loading from MAME software lists by putting the corresponding software hash files in the SYSTEMDIR/mame/hash directory.  While this DOES work for some systems e.g. nes, other titles such as from the n64 and snes software lists only cause RA to display the MAME "Initializing" splash screen and then hang indefinitely, never actually loading the game.

To reproduce, follow this example for snes:

1. Copy the RA/MAME hash files to SYSTEMDIR/mame/hash directory.  This should include snes.xml
2. Copy the MAME snes BIOS (snes.zip) to the RA/MAME BIOS directory
3. Copy a snes game of choice to the RA/ROM directory (note: game should match the corresponding hash from snes.xml)
4. Launch game zip with RA/MAME core and select "Load Archive"
5. Observe game hanging at initializing screen

Tested with RA 1.7.5 and MAME .201 core, on linux x64 running with 4.15 kernel

**Comment by ghost** [comment]
I've noticed something similar when attempting to run Neo Geo CD games through MAME on my Nvidia Shield (Android). I see the same "initializing" screen for a split second however instead of hanging, Retroarch just crashes entirely. RetroArch 1.75 and MAME 0.197 core here.

**Comment by tcamargo** [comment]
Possibly dup of https://github.com/libretro/mame/issues/158.

**Comment by Shoegzer** [comment]
@tcamargo you're probably right that this issue report is a dup, though just want to be sure given that I opened this specifically for RA/mame's loading against software list hash files.  I beleive (can't recall 100% now) that at the time I opened this, mame roms were loading okay.  I'll throw out an option to reopen and re-examine/close whenever #158 is resolved, though ultimately it's your call.

**Comment by tcamargo** [comment]
Maybe it is a different issue. I personally don't use mess. I wish to look into #158 first.

**Comment by Shoegzer** [comment]
@tcamargo well there's no more "mess" per se, it's all just "mame" now, as mame emulates lots of consoles like a2600, nes, snes,  genesis etc. in the same mame binary as arcade systems.  If we're thinking this is different though, maybe we leave this open for now?

**Comment by tcamargo** [comment]
@Shoegzer My builds only compile the arcade profile.

**Comment by Shoegzer** [comment]
@tcamargo I gotcha, I was just referring to mame in general, or if you will the default RA mame core that's just called "mame".    I haven't heard the term "mess" used in quite a while which threw me off.
