### ISSUE TITLE
UNABLE TO OPEN MAME INTERNAL MENU / Windows 10

### ISSUE THREAD

**Issue by hostile1975** [libretro/mame#88]
Tab button used to open Mame internal menu but Its not working anymore

**Comment by hostile1975** [comment]
L2 or R2 also dont work

**Comment by leoxxx** [comment]
https://forums.libretro.com/t/how-to-open-the-mame-menu/19577
The same issue in android.

**Comment by leoxxx** [comment]
I find it in "mame_libretro.info". It's "Select + X". You can watch mame info to find it.

**Comment by hostile1975** [comment]
Thanks leoxxx,
so I close it
