### ISSUE TITLE
Pressing Esc or shift+enter (open menu) and resuming causes the MAME software list to open

### ISSUE THREAD

**Issue by i30817** [libretro/mame#89]
Just like if we had requested the software list to open.

I'll suggest that maybe the default should be to never open the software list myself, or expose that shortcut to a retroarch binding. Same thing as mapping the coin insert.

I'm trying to find a mame.ini option to disable the softwarelist/mame GUI completely in the hope it disables the annoying reset but i haven't had much luck. Even if i do find one for disabling the gui i fear the 'reset' shortcut would remain and open it anyway.

The MAME core says these things when this happens:
```
exit scope, restart empty driver
SOURCE FILE: ../../../../../src/emu/drivers/empty.cpp
PARENT: 0
NAME: ___empty
DESCRIPTION: No Driver Loaded
YEAR: 2007
MANUFACTURER: MAME
```
As i said, i'm looking for a way to turn it into a exit. Reset can be handled from the retroarch playlist. And should, since the core obviously does a poor job of it by going from a game to a 'empty' driver.

**Comment by Immersion95** [comment]
Best way is to remap the UI cancel button to another key combo/button combo in the MAME gui, it solves this issue.

It currently is set to Echap/Start+Select

Or maybe I didn't understand the issue ?

**Comment by i30817** [comment]
Start+select is one of the (optional) hardcoded key combinations that retroarch uses to open the menu, which in my case i defined as 'shift+enter' in my 'retropad'. What appears to be the bug is that retroarch isn't filtering out certain combinations before they're given to the core or at least configuring the core default keybinding options not to clash with default retroarch combinations.

Of course i can change MAME keybindings, but neither i nor the next unknowing user should need to care.

I haven't verified if the problem still exists, i haven't got a MAME set right now to test.

edit: i had previously edited the retroarch cfg (since the setting is not available in the UI for fears lusers can't exit the program in non-desktop installs) to replace 'escape' from exit program to open menu (since it was near F1 and i sometimes missed on my savestate spam).

Escape for a confirmation-less exit right next to f1 (open menu) is quite frankly awful usability and i'm surprised people can even tolerate it; I guess most people are not using keyboards to control games.
