### ISSUE TITLE
Please enable custom folder for mame bios, roms and softwares

### ISSUE THREAD

**Issue by legluondunet** [libretro/mame#9]
Hello,

when you use mame, in the mame.ini config file, I can specify differents folders for my bios, roms and softwares folders. Could you add this feature to libretro mame module.
Thank you for your help.

LGDN.

**Comment by r-type** [comment]
I don’t know what to answer , this port should be able to handle mame.ini files already.
have you tried to enable read_configuration core options  ?

**Comment by legluondunet** [comment]
with "enable read_configuration" core options, mame libretro module found my roms folder, but not my CHD or software list folders.

**Comment by r-type** [comment]
works fine here , it's a problem related to your mame.ini.
just add the path to your mame.ini and it should work.

**Comment by legluondunet** [comment]
this is my retroarch log trying to launch a Mame chd game named aera51:
http://pastebin.com/0haXWUat

as you can see Libreto Mame module found my aim roms directory:
`RetroArch [libretro DEBUG] ::  /home/legluondunet/Autres_applications/Jeux/Emulateurs/Mame/Roms/ROMs`

But not the 2 others from my mame.ini file:
...
rompath                   /home/legluondunet/Autres_applications/Jeux/Emulateurs/Mame/Roms/ROMs;/home/legluondunet/Autres_applications/Jeux/Emulateurs/Mame/Roms/CHDs;/home/legluondunet/Autres_applications/Jeux/Emulateurs/Mame/Roms/Software List ROMs
...

I verified with original Mame and it can load this game.

**Comment by legluondunet** [comment]
this is the content of my mame.ini file located in /home/legluondunet/.mame/mame.ini:
http://pastebin.com/v1TeSGhC

I specified samples and artwork directory too in mame.ini. But Libretro Mame module didn't find them neither:

RetroArch [libretro DEBUG] ::  -samplepath
RetroArch [libretro DEBUG] ::  /home/legluondunet/.config/retroarch/bios/mame/samples
RetroArch [libretro DEBUG] ::  -artpath
RetroArch [libretro DEBUG] ::  /home/legluondunet/.config/retroarch/bios/mame/artwork
RetroArch [libretro DEBUG] ::  -cheatpath
RetroArch [libretro DEBUG] ::  /home/legluondunet/.config/retroarch/bios/mame/cheat
RetroArch [libretro DEBUG] ::  -inipath
RetroArch [libretro DEBUG] ::  /home/legluondunet/.config/retroarch/bios/mame/ini
RetroArch [libretro DEBUG] ::  -hashpath
RetroArch [libretro DEBUG] ::  /home/legluondunet/.config/retroarch/bios/mame/hash

**Comment by r-type** [comment]
bizarre,
works fine for me either if i load aera51.zip or aera51.chd
but I notice you loaded a 7z maybe that the problem.

Edit: test with CHD compressed in 7z, same error than you .
but works fine with chd or zip.

notice also that the size of the CHD is 498Mo and the size of the 7Z is  503 Mo so honestly what the purpose to have it in 7z .

**Comment by r-type** [comment]
par ailleurs vu le pseudo (qui me rappelle téléchat) tu n'aura pas de mal a lire ceci :)

**Comment by legluondunet** [comment]
My CHD files are not in 7zip format:

$ ll ~/Autres_applications/Jeux/Emulateurs/Mame/Roms/CHDs/area51/
497632790 nov.  30  2015 area51.chd
500902311 nov.  30  2015 area51t.chd

but the roms and software list roms.

When MAME launches Area51 game, it searches in the roms folder for area.7z (or area.zip) and in the CHD folder for the CHD files area.chd. 
Could you try to put roms and chds in two different folder like me, update your mame.ini config file. Does libretro find your CHD? (we can keep the area game for example).

PS: j'étais fan de téléchat ;)

**Comment by r-type** [comment]
yes, it doesn't work.
only working for me if i use cmdline like :
retroarch -L mame_libretro.so  "area51 -rp /path/to/chd;/path/to/roms"
retroarch -L mame_libretro.so "area51 -inipath /path/to/ini;ini"

it seems the way we deal rom loading (at launch add an -rp /path/to/current/game )
predominate the rompath setting in mame.ini .

**Comment by crocket** [comment]
Where should I put mame.inf?

**Comment by legluondunet** [comment]
Hello, this issue is still active, even if I put several directory in the mame.ini file, located in "/home/legluondunet/.config/retroarch/system/mame/ini/", Retroarch doesn't care, it seems only seeing the current game directory content.

**Comment by legluondunet** [comment]
It is not clean nor convenient to put all the Mame roms in the same folder.
The ideal way is to leave the Mame roms set as it is available on internet, separated in four folders:

CHDs (merged)
ROMs (split or merged)
Software List ROMs (split or merged)
Software List CHDs (merged)

Retroarch Mame core should be able to find the necessary roms in this four folders.

**Comment by NelsonRosenberg** [comment]
+1 on this issue. I wanted to add the bios files to a separate folder, I enabled mame_read_config = "enabled" in the core-options and configured the two paths in the `rompath` variable of my retroarch/system/ini/mame.ini file but nothing happens. Would be nice to be able to do this.

**Comment by welblade** [comment]
This issue is still around.
Nothing can be done to fix it?

**Comment by mase76** [comment]
I have similar issues. I have multiple rom and chd paths configured. But only the first is read. Also the <game>.ini contains only that one path.
Another thing is, that some resource paths are overwritten with the default path, others are kept as I configured them. For example the artwork path is always changed back to default.

**Comment by Langerz82** [comment]
I would like multiple ROM paths as well as the ROMS I have that arent loading are moved to a missing folder but sometimes BIOS files get moved as well, so it would be good to include the missing ROMs folder as well in the search path.
If nobody is working on this perhaps I can make a patch. My dev skills are so-so though ha so if I try don't expect it to be very clean. XD

edit:
I found a way to enable multiple folders in linux. By creating soft-links to the directory for example:
```
mkdir foo
cd foo
touch foo.txt
cd ..

mkdir bar1
cd bar1
touch bar1.txt
cd ..

mkdir bar2
cd bar2
touch bar2.txt
cd ..

ln -sf bar1/* foo
ln -sf bar2/* foo
```
Now the folder foo should show foo.txt, bar1.txt and bar2.txt. Hope this helps.

**Comment by dgasaway** [comment]
Reading `rompath` from mame.ini would be great, but even something simple like adding `system/mame/bios` to the MAME search path would be a huge improvement.

**Comment by haimbilia** [comment]
+1 on this issue, i can't believe people are mixing game roms with bios roms in the same folder. and then try to update their rom set.

**Comment by sonninnos** [comment]
While this does not allow the reading of the path as whatever, it does help in a way that it removes the need to do so: https://github.com/libretro/mame/pull/353
