### ISSUE TITLE
0.205 crashes on core load (Windows)

### ISSUE THREAD

**Issue by ghost** [libretro/mame#91]
There seems to be some new networking code that's causing problems?

```
warning:

=======================================
VERIFIER STOP 000000000000E100: pid 0x1D7C: Illegal networking API called from DllMain

        00007FFDACCA03D0 : Networking function being called from DllMain
        000000001AAACFDC : Name of Dll making invalid call if not NULL
        0000000000000000 : Not used
        0000000000000000 : Not used


=======================================
This verifier stop is continuable.
After debugging it use `go' to continue.

=======================================


Thread 1 received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffda758214a in vrfcore!VerifierStopMessageEx ()
   from C:\Windows\SYSTEM32\vrfcore.dll
(gdb) x/20s 0x1aaacfdc
0x1aaacfdc:     "m"
0x1aaacfde:     "a"
0x1aaacfe0:     "m"
0x1aaacfe2:     "e"
0x1aaacfe4:     "_"
0x1aaacfe6:     "l"
0x1aaacfe8:     "i"
0x1aaacfea:     "b"
0x1aaacfec:     "r"
0x1aaacfee:     "e"
0x1aaacff0:     "t"
0x1aaacff2:     "r"
0x1aaacff4:     "o"
0x1aaacff6:     "."
0x1aaacff8:     "d"
0x1aaacffa:     "l"
0x1aaacffc:     "l"
0x1aaacffe:     ""
0x1aaacfff:     ""
0x1aaad000:     <error: Cannot access memory at address 0x1aaad000>
(gdb) bt
#0  0x00007ffda758214a in vrfcore!VerifierStopMessageEx ()
   from C:\Windows\SYSTEM32\vrfcore.dll
#1  0x00007ffdacc9364d in ?? () from C:\Windows\SYSTEM32\vfnet.dll
#2  0x00007ffdacc9c64d in ?? () from C:\Windows\SYSTEM32\vfnet.dll
#3  0x00000000218c36b6 in asio::detail::winsock_init_base::startup(asio::detail::winsock_init_base::data&, unsigned char, unsigned char) [clone .part.75] ()
   from C:\Users\bp\Downloads\RetroArch\cores\mame_libretro.dll
#4  0x00000000268b5436 in _GLOBAL__sub_I_http.cpp ()
   from C:\Users\bp\Downloads\RetroArch\cores\mame_libretro.dll
#5  0x0000000021df9292 in __do_global_ctors ()
```

**Comment by r-type** [comment]
hi,
thanks for reporting ,
I can't test it on a true windows for now, so i've just tested it with wine.

![mame205](https://user-images.githubusercontent.com/3614417/51090469-b87b9080-177c-11e9-87d2-e5395488dbad.png)

i will try on a windows 10 machine tomorrow  to see what is going wrong.

**Comment by r-type** [comment]
![image](https://user-images.githubusercontent.com/3614417/51176805-29769180-18be-11e9-9694-580bd4c771fd.png)
Hi can you elaborate, which game , all ?
as it works here on windows 10 x64

**Comment by ghost** [comment]
Ok it's not technically a crash, I had AppVerifier turned on and it was triggering a breakpoint with the above message. So the core still runs, but it is doing something it's not supposed to do.

**Comment by r-type** [comment]
Does it crash the same with upstream? 
as it seem to be a problem with websockets and Asio when dll.

similar to http://codename26.rssing.com/chan-8623770/all_p180.html#item3591

**Comment by andres-asm** [comment]
I'm still having this issue here.

**Comment by r-type** [comment]
@fr500  does it crash for you ? 
if yes , can you help me to fix this as i'm not a windows user and it's not easy to me to test on a real windows.

**Comment by tcamargo** [comment]
Does it still happen on mame-0.222?

**Comment by sonninnos** [comment]
Pretty sure this no longer applies.
