### ISSUE TITLE
Xbox One Controller not working in the core

### ISSUE THREAD

**Issue by ghost** [libretro/mame#92]
First, the controller works fine in other cores, just plug and play without remaping and when I needed I could remap without any problems. 

Now in MAME 0.206 core, when I try to remap like in other cores (pressing <- or -> in the remap) it doesn't change to anything, just three dashes (- - -). And by default the only buttons that are working are: Left Analog (up, down, left, right), Start, Select, and misteriously, B is working. 
Everything else, A, X, Y, Left Bumper, Left Trigger, Right Bumper, Right Trigger, L3, R3, Right Analog doesn't do anything ingame by default, and I'm not able to remap them.

I'm using MAME 0.206 core, in RetroArch 1.7.6, Windows 10 x64

**Comment by bootsector** [comment]
Can't use (or map) DPAD to to anything on a 8BitDo M30 controller. Ubuntu 18.04.

**Comment by bootsector** [comment]
So I've added this to the <SAVE_DIR>/mame/cfg/default.cfg:

```
<?xml version="1.0"?>
<mameconfig version="10">
    <system name="default">
        <input>
            <port type="P1_JOYSTICK_UP">
                <newseq type="standard">
                    JOYCODE_1_BUTTON11
                </newseq>
            </port>
            <port type="P1_JOYSTICK_DOWN">
                <newseq type="standard">
                    JOYCODE_1_BUTTON12
                </newseq>
            </port>
            <port type="P1_JOYSTICK_LEFT">
                <newseq type="standard">
                    JOYCODE_1_BUTTON13
                </newseq>
            </port>
            <port type="P1_JOYSTICK_RIGHT">
                <newseq type="standard">
                    JOYCODE_1_BUTTON14
                </newseq>
            </port>
    	</input>
    </system>
</mameconfig>
```

Now it works. It looks like DPAD defaults in MAME are screwed up.

**Comment by c0d3h4x0r** [comment]
I was having the exact same problem as bootsector, and I can confirm that user's workaround also works for me.

**Comment by tcamargo** [comment]
See #126. It should remove the need for that extra mapping file.
