### ISSUE TITLE
build failed with unused variable

### ISSUE THREAD

**Issue by treaves** [libretro/mame#95]
src/osd/modules/render/drawretro.cpp:77

Someone allowed the code to be committed with commented out code.  Line 77 sets up a pitch variable which is never used as lines 78 through 87 are commented out.  This is causing compilation on odroid to fail (and any other environment rating warnings as errors).

**Comment by andres-asm** [comment]
That means you're treating warnings as errors.

**Comment by treaves** [comment]
Retroarch is, as this is being installed (updated) via that menu option.

**Comment by andres-asm** [comment]
not sure of what you're talking about
you were mentioning a build error, my comment is about that build error.

**Comment by treaves** [comment]
I know what the build error means, as I stated such in my original post.  And I'm not treating warnings as errors as I'm not the one who setup the compile.  The retroarch/es/lrmame menu system / configruation does.

**Comment by markwkidd** [comment]
@treaves If you're building this core from within the RetroPie menu system, then you need to report this issue in the RetroPie setup repository at https://github.com/RetroPie/RetroPie-Setup/issues

It's impossible to say without looking at their menu system how it's being built, and it's nothing that can be addressed in any of the libretro repositories

Their core build scripts don't involve RetroArch at all, and may or may not be using the libretro Makefiles depending on the particular core.

**Comment by treaves** [comment]
O.K., I checked out from master, issued make, and the same failure occurred.  The projects makefile apparently doesn't configure this, so it's left up to the individual OS/compiler combo's.

**Comment by r-type** [comment]
i agree we can just remove this unused variable "pitch",
but can you just try at least to to do a
```
make  OSD="retro" verbose=1 RETRO=1 NOWERROR=1  NOASM="1"  CONFIG=libretro NO_USE_MIDI="1" SUBTARGET=tiny 
```
to see what' s going on.

for reference you can look at here to see how we call make.

https://github.com/libretro/mame/tree/master/src/osd/libretro/libretro-internal

**Comment by treaves** [comment]
I'll give this a try now, thanks.  I'll use your suggested settings @r-type , but, do you know if there are more specific ones for a Raspberry Pie or ODroid?  Neither is listed.

**Comment by treaves** [comment]
I found what the ODroid uses to compile, and it does indeed compile fully now.  So thanks for that.  When I run any ROM however, it fails with the following.  Perhaps I should open a new defect.

```
[INFO] === Build =======================================
Capabilities: NEON VFPv3 VFPv4
Built: Feb  4 2019
[INFO] Version: 1.7.6
[INFO] Git: 9750719
[INFO] =================================================
[INFO] Loading dynamic libretro core from: "/opt/retroarena/libretrocores/lr-mame/mamearcade_libretro.so"
[ERROR] Failed to open libretro core: "/opt/retroarena/libretrocores/lr-mame/mamearcade_libretro.so"
[ERROR] Error(s): /opt/retroarena/libretrocores/lr-mame/mamearcade_libretro.so: undefined symbol: driver_ad4ctl
```

**Comment by r-type** [comment]
can you past the cmd you use to build ? also it seem driver_ad4ctl is undefined ,
are you sure you used the TARGET=mame SUBTARGET=arcade and all built fine?

so can you look at your bin to see if there is undefined symbol 
``` nm -u mamearcade_libretro.so |egrep -v "@@"```

**Comment by treaves** [comment]
The command used is 
`make OSD=retro RETRO=1 NOWERROR=1 OS=linux TARGETOS=linux CONFIG=libretro NO_USE_MIDI=1 TARGET=mame  SUBTARGET=arcade -j1`

By 'built fine' I simply mean that the make command finished and produced the mamearcade_libretro.so file.  I do not know if it is possible for the build to experience issues and still complete.

The output of the nm command is more than 3000 lines, so, I'll not post it. :).  I can send it if wanted, but, I think something is amiss with my build.

**Comment by r-type** [comment]
then if it 3000 lines that is something goes wrong with your lib as it mean that all the mame func are undefined.
can you at least only try with a drivers and not all the mame arcade , for debug purpose
```
make OSD=retro RETRO=1 NOWERROR=1 OS=linux TARGETOS=linux CONFIG=libretro NO_USE_MIDI=1 SUBTARGET=pacman SOURCES=src/mame/drivers/pacman.cpp
```
(or what driver you like)

**Comment by treaves** [comment]
Well, trying just this, I get the same failure I get when running the .so provided with the distro (but I don't get the missing symbol error):
```
[libretro INFO] Starting game:/home/pigaming/RetroArena/roms/mame-libretro/pacma
n.zip
[libretro INFO] Game name: pacman, Game description: Pac-Man (Midway)
[libretro ERROR] System not found: mame-libretro
[libretro WARN] Driver mame-libretro not found -1
[libretro INFO] Creating frontend for game: pacman
[libretro INFO] Softlists: 0
Unknown system 'mame-libretro'

"mame-libretro" approximately matches the following
supported machines (best match first):
```

**Comment by treaves** [comment]
Well, I've discovered that my ROM's - in the mame-libretro folder as they should be - when moved to the arcade folder fail with:
```
[libretro ERROR] System not found: arcade
[libretro WARN] Driver arcade not found -1
[libretro INFO] Creating frontend for game: galaga
[libretro INFO] Softlists: 0
Unknown system 'arcade'
```

So something odd is going on.  The system not know matches the folder where the ROM is located.

**Comment by tcamargo** [comment]
Closing old issues. Please reopen if it is still relevant.
