### ISSUE TITLE
Rewind and Restart completely non-functional?

### ISSUE THREAD

**Issue by PlugMeister068** [libretro/mame#96]
So the current version of the MAME core as of this writing (0.207) as well as MAME 2016 seem to be completely immune to RetroArch's rewind function. I checked to make sure that there are no accidental double bindings of my rewind button in the OSD, and I also checked to make sure that rewind was enabled in the first place. Is this intentional, a known problem with a known solution, or is it the exact opposite?

EDIT: Using "Restart" from the RetroArch menu also does nothing.

**Comment by barcoboy** [comment]
If you start a game, then go back to the menu system, go to the "Rewind" menu, and turn off and immediately turn back on the Rewind option, then resume the game, you will find that rewinding then works.  It also works if you start a game with the option disabled, then go into the menus and enable it, and resume the game.

Should be an easy fix to get this working when the game starts.

**Comment by tcamargo** [comment]
Could you please test a newer build?

**Comment by barcoboy** [comment]
Just tested with RetroArch 1.8.9 and MAME core 0.222.  Rewind functions the same as per my comment above, and trying to restart the core still has no effect.

**Comment by sonninnos** [comment]
Rewind will never be perfect since it relies on savestates, but restart has been working for a while.
